function result = run_coreless_motor_identification_demo()
%RUN_CORELESS_MOTOR_IDENTIFICATION_DEMO End-to-end synthetic-data demo.
% Run from this folder or through:
%   matlab -batch "run('identification/coreless_motor_12v_identification/run_coreless_motor_identification_demo.m')"

thisDir = fileparts(mfilename("fullpath"));
oldPath = path;
cleanup = onCleanup(@() path(oldPath));
addpath(thisDir);

cfg = coreless_motor_12v_config();
data = synthesize_coreless_motor_12v_data(cfg);
result = identify_coreless_motor_mechanics(data, cfg);

resultsDir = fullfile(thisDir, "results");
if ~exist(resultsDir, "dir")
    mkdir(resultsDir);
end

writetable(data, fullfile(resultsDir, "synthetic_coreless_motor_12v_data.csv"));
writetable(result.windows, fullfile(resultsDir, "identification_windows.csv"));
write_report(fullfile(resultsDir, "identification_report.txt"), result, cfg);

fprintf("\nCoreless motor 12V mechanical identification demo\n");
fprintf("--------------------------------------------------\n");
fprintf("Window count      : %d\n", result.window_count);
fprintf("Torque RMSE       : %.6g Nm\n", result.rmse_Nm);
fprintf("J true / estimate : %.6g / %.6g kg*m^2 (error %.2f%%)\n", ...
    cfg.motor.J_kgm2, result.J_kgm2, 100 * result.relative_error.J);
fprintf("B true / estimate : %.6g / %.6g Nm/(rad/s) (error %.2f%%)\n", ...
    cfg.motor.B_Nm_per_radps, result.B_Nm_per_radps, ...
    100 * result.relative_error.B);
fprintf("Tc true / estimate: %.6g / %.6g Nm (error %.2f%%)\n", ...
    cfg.motor.Tc_Nm, result.Tc_Nm, 100 * result.relative_error.Tc);
fprintf("Tbias estimate    : %.6g Nm\n", result.Tbias_Nm);
fprintf("Results written to: %s\n\n", resultsDir);
end

function write_report(reportPath, result, cfg)
fid = fopen(reportPath, "w");
assert(fid > 0, "Unable to open report file: %s", reportPath);
cleanup = onCleanup(@() fclose(fid));

fprintf(fid, "Coreless motor 12V mechanical identification demo\n");
fprintf(fid, "Date generated by MATLAB script\n\n");
fprintf(fid, "Experiment\n");
fprintf(fid, "  Ts_s              = %.9g\n", cfg.experiment.Ts_s);
fprintf(fid, "  pulseCurrent_A    = %.9g\n", cfg.experiment.pulseCurrent_A);
fprintf(fid, "  pulseTime_s       = %.9g\n", cfg.experiment.pulseTime_s);
fprintf(fid, "  repeatCount       = %d\n\n", cfg.experiment.repeatCount);

fprintf(fid, "Motor truth\n");
fprintf(fid, "  J_kgm2            = %.9g\n", cfg.motor.J_kgm2);
fprintf(fid, "  B_Nm_per_radps    = %.9g\n", cfg.motor.B_Nm_per_radps);
fprintf(fid, "  Tc_Nm             = %.9g\n", cfg.motor.Tc_Nm);
fprintf(fid, "  Tbias_Nm          = %.9g\n\n", cfg.motor.Tbias_Nm);

fprintf(fid, "Estimate\n");
fprintf(fid, "  J_kgm2            = %.9g\n", result.J_kgm2);
fprintf(fid, "  B_Nm_per_radps    = %.9g\n", result.B_Nm_per_radps);
fprintf(fid, "  Tc_Nm             = %.9g\n", result.Tc_Nm);
fprintf(fid, "  Tbias_Nm          = %.9g\n", result.Tbias_Nm);
fprintf(fid, "  rmse_Nm           = %.9g\n", result.rmse_Nm);
fprintf(fid, "  window_count      = %d\n\n", result.window_count);

fprintf(fid, "Relative error\n");
fprintf(fid, "  J                 = %.6f\n", result.relative_error.J);
fprintf(fid, "  B                 = %.6f\n", result.relative_error.B);
fprintf(fid, "  Tc                = %.6f\n", result.relative_error.Tc);
fprintf(fid, "  Tbias_abs         = %.9g\n", result.relative_error.Tbias);
end
