%% Smoke test for speed_pi_model
%
% Builds the pure speed PI core model and simulates it from a temporary harness.
% The harness is not a production model; it only verifies finite outputs,
% iq_ref limiting, and speed tracking.

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

run(fullfile(script_dir, 'build_speed_pi_model.m'));

cfg = evalin('base', 'speed_pi_config');
model = cfg.modelName;
model_file = fullfile(script_dir, [model '.slx']);

load_system(model_file);
harness = build_speed_pi_smoke_harness(cfg, model);
cleanup_harness = onCleanup(@() close_harness_without_saving(harness));

sim_out = sim(harness, ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SaveOutput', 'off');

wm_ref = sim_out.get('log_wm_ref').Data;
wm_meas = sim_out.get('log_wm_meas').Data;
iq_ref = sim_out.get('log_iq_ref').Data;

defaults = evalin('base', 'speed_pi_defaults');
iq_limit = double(defaults.test.iq_limit);
final_wm_ref = double(wm_ref(end));
final_wm_meas = double(wm_meas(end));
final_speed_error = final_wm_ref - final_wm_meas;
iq_values = double(iq_ref(:));
all_values = [double(wm_ref(:)); double(wm_meas(:)); iq_values];

fprintf('\nSpeed PI smoke test result:\n');
fprintf('  wm_ref final  = %.6g rad/s\n', final_wm_ref);
fprintf('  wm_meas final = %.6g rad/s\n', final_wm_meas);
fprintf('  speed error   = %.6g rad/s\n', final_speed_error);
fprintf('  iq_ref range  = [%.6g, %.6g] A\n', min(iq_values), max(iq_values));
fprintf('  iq_limit      = %.6g A\n', iq_limit);

if any(~isfinite(all_values))
    error('Speed PI smoke test failed: non-finite value detected.');
end

if any(abs(iq_values) > iq_limit + 1e-4)
    error('Speed PI smoke test failed: iq_ref exceeded iq_limit.');
end

if abs(final_speed_error) > 0.5
    error('Speed PI smoke test failed: final speed error is too large.');
end

if max(iq_values) < 0.1
    error('Speed PI smoke test failed: iq_ref did not respond.');
end

fprintf('Speed PI smoke test passed.\n');

close_harness_without_saving(harness);
clear cleanup_harness;

function harness = build_speed_pi_smoke_harness(cfg, referenced_model)
harness = 'speed_pi_smoke_harness';
if bdIsLoaded(harness)
    close_system(harness, 0);
end
new_system(harness);
set_param(harness, ...
    'DataDictionary', cfg.dictionaryName, ...
    'StopTime', 'speed_pi_simcfg.stop_time', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'speed_pi_simcfg.Ts_speed', ...
    'ParameterPrecisionLossMsg', 'none');

add_typed_constant(harness, 'wm_ref', [45 45 115 70], ...
    'speed_pi_test.wm_ref', cfg.speedTypeName, cfg.sampleTime);
add_typed_constant(harness, 'iq_limit', [45 165 115 190], ...
    'speed_pi_test.iq_limit', cfg.currentTypeName, cfg.sampleTime);

add_block('simulink/Discrete/Unit Delay', [harness '/wm_meas_state'], ...
    'Position', [705 235 775 265], ...
    'InitialCondition', 'speed_pi_test.wm_initial', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Signal Routing/Bus Creator', [harness '/speed_input_bus_creator'], ...
    'Position', [180 45 195 190], ...
    'Inputs', '3', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.inputBusName, ...
    'NonVirtualBus', 'on');
add_block('simulink/Ports & Subsystems/Model', [harness '/SpeedPiModelRef'], ...
    'Position', [265 90 460 185], ...
    'ModelName', referenced_model);
add_block('simulink/Signal Routing/Bus Selector', [harness '/speed_output_selector'], ...
    'Position', [510 95 525 170], ...
    'OutputSignals', 'iq_ref');

add_block('simulink/Math Operations/Gain', [harness '/iq_to_torque'], ...
    'Position', [570 100 650 130], ...
    'Gain', 'speed_pi_test.torque_constant', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.realTypeName);
add_typed_constant(harness, 'load_torque', [570 150 650 175], ...
    'speed_pi_test.load_torque', cfg.realTypeName, cfg.sampleTime);
add_block('simulink/Math Operations/Gain', [harness '/viscous_torque'], ...
    'Position', [570 235 650 265], ...
    'Gain', 'speed_pi_test.B', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.realTypeName);
add_block('simulink/Math Operations/Sum', [harness '/net_torque'], ...
    'Position', [700 120 730 185], ...
    'Inputs', '+--', ...
    'AccumDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.realTypeName);
add_block('simulink/Math Operations/Gain', [harness '/inv_inertia'], ...
    'Position', [770 135 850 165], ...
    'Gain', '1/speed_pi_test.J', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.speedTypeName);
add_block('simulink/Math Operations/Gain', [harness '/speed_delta'], ...
    'Position', [885 135 965 165], ...
    'Gain', 'speed_pi_simcfg.Ts_speed', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.speedTypeName);
add_block('simulink/Math Operations/Sum', [harness '/speed_next'], ...
    'Position', [1000 175 1030 225], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', cfg.speedTypeName, ...
    'OutDataTypeStr', cfg.speedTypeName);

add_scalar_logger(harness, 'log_wm_ref', [235 35 315 65], 'wm_ref/1');
add_scalar_logger(harness, 'log_wm_meas', [805 235 895 265], 'wm_meas_state/1');
add_scalar_logger(harness, 'log_iq_ref', [570 60 650 90], 'speed_output_selector/1');

name_line(add_line(harness, 'wm_ref/1', 'speed_input_bus_creator/1', ...
    'autorouting', 'on'), 'wm_ref');
name_line(add_line(harness, 'wm_meas_state/1', 'speed_input_bus_creator/2', ...
    'autorouting', 'on'), 'wm_meas');
name_line(add_line(harness, 'iq_limit/1', 'speed_input_bus_creator/3', ...
    'autorouting', 'on'), 'iq_limit');
add_line(harness, 'speed_input_bus_creator/1', 'SpeedPiModelRef/1', ...
    'autorouting', 'on');
add_line(harness, 'SpeedPiModelRef/1', 'speed_output_selector/1', ...
    'autorouting', 'on');
add_line(harness, 'speed_output_selector/1', 'iq_to_torque/1', 'autorouting', 'on');
add_line(harness, 'iq_to_torque/1', 'net_torque/1', 'autorouting', 'on');
add_line(harness, 'load_torque/1', 'net_torque/2', 'autorouting', 'on');
add_line(harness, 'wm_meas_state/1', 'viscous_torque/1', 'autorouting', 'on');
add_line(harness, 'viscous_torque/1', 'net_torque/3', 'autorouting', 'on');
add_line(harness, 'net_torque/1', 'inv_inertia/1', 'autorouting', 'on');
add_line(harness, 'inv_inertia/1', 'speed_delta/1', 'autorouting', 'on');
add_line(harness, 'speed_delta/1', 'speed_next/1', 'autorouting', 'on');
add_line(harness, 'wm_meas_state/1', 'speed_next/2', 'autorouting', 'on');
add_line(harness, 'speed_next/1', 'wm_meas_state/1', 'autorouting', 'on');
end

function close_harness_without_saving(harness)
if bdIsLoaded(harness)
    set_param(harness, 'Dirty', 'off');
    close_system(harness, 0);
end
end

function add_typed_constant(model, block_name, position, value, data_type, sample_time)
add_block('simulink/Sources/Constant', [model '/' block_name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', sample_time);
end

function add_scalar_logger(model, variable_name, position, src_port)
add_block('simulink/Sinks/To Workspace', [model '/' variable_name], ...
    'Position', position, ...
    'VariableName', variable_name, ...
    'SaveFormat', 'Timeseries');
add_line(model, src_port, [variable_name '/1'], 'autorouting', 'on');
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
