%% Build green-joint current PI MBD model
%
% Scope is intentionally narrow:
%   dq current reference/feedback -> physical Vdq PI -> unit-circle Vdq
%
% Clarke/Park, current filtering, inverse Park, SVPWM, ADC sector handling,
% and PWM register writes remain outside this generated module.

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

assert_green_joint_safe_rebuild_environment();
run(fullfile(script_dir, 'generate_green_joint_current_loop_dictionary.m'));
contract = evalin('base', 'green_joint_current_loop_contract');

model = contract.model;
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

if exist(model_file, 'file')
    delete(model_file);
end

new_system(model);
set_param(model, ...
    'DataDictionary', contract.dictionary, ...
    'StopTime', '0.001', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(contract.sample_time_s, '%.12g'), ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'ParameterPrecisionLossMsg', 'none', ...
    'InlineParams', 'off', ...
    'CodeInterfacePackaging', 'Reusable function', ...
    'ModelReferenceNumInstancesAllowed', 'Multi');

add_algorithm_boundary(model, contract);

save_system(model, model_file);

fprintf('Built green-joint current PI MBD model:\n  %s\n', model_file);

function add_algorithm_boundary(model, contract)
subsystem = [model '/' contract.step_function];
add_block('simulink/Ports & Subsystems/Subsystem', subsystem, ...
    'Position', [210 85 410 175]);
delete_line(subsystem, 'In1/1', 'Out1/1');
delete_block([subsystem '/In1']);
delete_block([subsystem '/Out1']);

set_param(subsystem, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function', ...
    'RTWFcnNameOpts', 'User specified', ...
    'RTWFcnName', contract.step_function, ...
    'RTWFileNameOpts', 'User specified', ...
    'RTWFileName', contract.step_function);

input_bus = contract.buses{1}.name;
output_bus = contract.buses{2}.name;

add_block('simulink/Sources/In1', [subsystem '/loop_in'], ...
    'Position', [40 150 70 170], ...
    'OutDataTypeStr', ['Bus: ' input_bus], ...
    'BusOutputAsStruct', 'on');
add_block('simulink/Sinks/Out1', [subsystem '/loop_out'], ...
    'Position', [1170 150 1200 170], ...
    'OutDataTypeStr', ['Bus: ' output_bus]);

add_block('simulink/Signal Routing/Bus Selector', [subsystem '/input_selector'], ...
    'Position', [110 85 130 245], ...
    'OutputSignals', 'id_ref,iq_ref,id_fbk,iq_fbk,vbus');

add_line(subsystem, 'loop_in/1', 'input_selector/1', 'autorouting', 'on');
add_current_pi_algorithm(subsystem, contract, output_bus);
add_line(subsystem, 'pi_output_bus_creator/1', 'loop_out/1', 'autorouting', 'on');

add_block('simulink/Sources/In1', [model '/loop_in'], ...
    'Position', [55 120 85 140], ...
    'OutDataTypeStr', ['Bus: ' input_bus], ...
    'BusOutputAsStruct', 'on');
add_block('simulink/Sinks/Out1', [model '/loop_out'], ...
    'Position', [520 120 550 140], ...
    'OutDataTypeStr', ['Bus: ' output_bus]);

add_line(model, 'loop_in/1', [contract.step_function '/1'], 'autorouting', 'on');
add_line(model, [contract.step_function '/1'], 'loop_out/1', 'autorouting', 'on');
end

function add_current_pi_algorithm(subsystem, contract, output_bus)
ts = num2str(contract.sample_time_s, '%.12g');

add_voltage_limit_blocks(subsystem);

add_pi_axis(subsystem, 'd', ...
    'input_selector/1', 'input_selector/3', ...
    'CurDKp', 'CurDKi', ts, 70);
add_pi_axis(subsystem, 'q', ...
    'input_selector/2', 'input_selector/4', ...
    'CurQKp', 'CurQKi', ts, 250);

add_circular_voltage_limit(subsystem);
add_voltage_normalization(subsystem);

add_block('simulink/Signal Routing/Bus Creator', ...
    [subsystem '/pi_output_bus_creator'], ...
    'Position', [1085 95 1100 270], ...
    'Inputs', '9', ...
    'UseBusObject', 'on', ...
    'BusObject', output_bus, ...
    'NonVirtualBus', 'on');

name_line(add_line(subsystem, 'vd_cmd/1', 'pi_output_bus_creator/1', ...
    'autorouting', 'on'), 'vd_cmd');
name_line(add_line(subsystem, 'vq_cmd/1', 'pi_output_bus_creator/2', ...
    'autorouting', 'on'), 'vq_cmd');
name_line(add_line(subsystem, 'voltage_mag/1', 'pi_output_bus_creator/3', ...
    'autorouting', 'on'), 'voltage_mag');
name_line(add_line(subsystem, 'vd_norm/1', 'pi_output_bus_creator/4', ...
    'autorouting', 'on'), 'vd_norm');
name_line(add_line(subsystem, 'vq_norm/1', 'pi_output_bus_creator/5', ...
    'autorouting', 'on'), 'vq_norm');
name_line(add_line(subsystem, 'voltage_mag_norm/1', 'pi_output_bus_creator/6', ...
    'autorouting', 'on'), 'voltage_mag_norm');
name_line(add_line(subsystem, 'vd_mod/1', 'pi_output_bus_creator/7', ...
    'autorouting', 'on'), 'vd_mod');
name_line(add_line(subsystem, 'vq_mod/1', 'pi_output_bus_creator/8', ...
    'autorouting', 'on'), 'vq_mod');
name_line(add_line(subsystem, 'voltage_mag_mod/1', 'pi_output_bus_creator/9', ...
    'autorouting', 'on'), 'voltage_mag_mod');
end

function add_voltage_limit_blocks(subsystem)
add_block('simulink/Math Operations/Gain', [subsystem '/voltage_limit'], ...
    'Position', [175 350 245 380], ...
    'Gain', 'VoltageLimitRatio * VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Sources/Constant', [subsystem '/voltage_epsilon'], ...
    'Position', [175 405 245 435], ...
    'Value', 'VoltageEpsilon', ...
    'OutDataTypeStr', 'T_GJVoltage', ...
    'SampleTime', '-1');
add_minmax(subsystem, 'voltage_limit_guard', [285 365 345 420], 'max');

add_line(subsystem, 'input_selector/5', 'voltage_limit/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_limit/1', 'voltage_limit_guard/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_epsilon/1', 'voltage_limit_guard/2', 'autorouting', 'on');
end

function add_pi_axis(subsystem, axis, ref_port, fbk_port, kp_name, ki_name, ts, y)
error_name = [axis '_current_error'];
kp_block = [axis '_kp'];
ki_block = [axis '_ki'];
state_name = [axis '_integrator_state'];
pre_sat_name = [axis '_pre_sat_voltage'];
back_calc_name = [axis '_back_calc_error'];
kaw_name = [axis '_kaw'];
rate_name = [axis '_integrator_rate'];
delta_name = [axis '_integrator_delta'];
next_name = [axis '_integrator_next'];

add_block('simulink/Math Operations/Sum', [subsystem '/' error_name], ...
    'Position', [175 y 205 y + 35], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_GJCurrent', ...
    'OutDataTypeStr', 'T_GJCurrent');
add_block('simulink/Math Operations/Gain', [subsystem '/' kp_block], ...
    'Position', [245 y 315 y + 30], ...
    'Gain', kp_name, ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/' ki_block], ...
    'Position', [245 y + 60 315 y + 90], ...
    'Gain', ki_name, ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Discrete/Unit Delay', [subsystem '/' state_name], ...
    'Position', [360 y + 100 425 y + 130], ...
    'InitialCondition', 'single(0)', ...
    'SampleTime', ts);
add_block('simulink/Math Operations/Sum', [subsystem '/' pre_sat_name], ...
    'Position', [465 y + 10 495 y + 55], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Sum', [subsystem '/' back_calc_name], ...
    'Position', [725 y + 70 755 y + 115], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/' kaw_name], ...
    'Position', [790 y + 78 860 y + 108], ...
    'Gain', 'PiCorrectionGain', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Sum', [subsystem '/' rate_name], ...
    'Position', [895 y + 63 925 y + 108], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/' delta_name], ...
    'Position', [960 y + 70 1030 y + 100], ...
    'Gain', ['single(' ts ')'], ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Sum', [subsystem '/' next_name], ...
    'Position', [1065 y + 85 1095 y + 130], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');

add_line(subsystem, ref_port, [error_name '/1'], 'autorouting', 'on');
add_line(subsystem, fbk_port, [error_name '/2'], 'autorouting', 'on');
add_line(subsystem, [error_name '/1'], [kp_block '/1'], 'autorouting', 'on');
add_line(subsystem, [error_name '/1'], [ki_block '/1'], 'autorouting', 'on');
add_line(subsystem, [kp_block '/1'], [pre_sat_name '/1'], 'autorouting', 'on');
add_line(subsystem, [state_name '/1'], [pre_sat_name '/2'], 'autorouting', 'on');
add_line(subsystem, [ki_block '/1'], [rate_name '/1'], 'autorouting', 'on');
add_line(subsystem, [back_calc_name '/1'], [kaw_name '/1'], 'autorouting', 'on');
add_line(subsystem, [kaw_name '/1'], [rate_name '/2'], 'autorouting', 'on');
add_line(subsystem, [rate_name '/1'], [delta_name '/1'], 'autorouting', 'on');
add_line(subsystem, [state_name '/1'], [next_name '/1'], 'autorouting', 'on');
add_line(subsystem, [delta_name '/1'], [next_name '/2'], 'autorouting', 'on');
add_line(subsystem, [next_name '/1'], [state_name '/1'], 'autorouting', 'on');
end

function add_circular_voltage_limit(subsystem)
add_block('simulink/Math Operations/Gain', [subsystem '/neg_voltage_limit'], ...
    'Position', [500 360 570 390], ...
    'Gain', '-1', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_minmax(subsystem, 'vd_min_upper', [545 55 605 90], 'min');
add_minmax(subsystem, 'vd_cmd', [650 55 710 90], 'max');

add_square_block(subsystem, 'voltage_limit_square', [545 430 595 465]);
add_square_block(subsystem, 'vd_cmd_square_for_vq_limit', [745 100 795 135]);
add_block('simulink/Math Operations/Sum', [subsystem '/vq_limit_square_raw'], ...
    'Position', [835 145 865 190], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Sources/Constant', [subsystem '/zero_voltage'], ...
    'Position', [835 220 895 250], ...
    'Value', 'single(0)', ...
    'OutDataTypeStr', 'T_GJVoltage', ...
    'SampleTime', '-1');
add_minmax(subsystem, 'vq_limit_square', [910 160 970 220], 'max');
add_block('simulink/Math Operations/Math Function', [subsystem '/vq_limit'], ...
    'Position', [1010 175 1065 210], ...
    'Operator', 'sqrt', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/neg_vq_limit'], ...
    'Position', [1010 240 1070 270], ...
    'Gain', '-1', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_minmax(subsystem, 'vq_min_upper', [1095 240 1155 275], 'min');
add_minmax(subsystem, 'vq_cmd', [1190 240 1250 275], 'max');

add_square_block(subsystem, 'vd_cmd_square_for_mag', [745 30 795 65]);
add_square_block(subsystem, 'vq_cmd_square_for_mag', [1285 240 1335 275]);
add_block('simulink/Math Operations/Sum', [subsystem '/voltage_mag_square'], ...
    'Position', [1370 130 1400 180], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Math Function', [subsystem '/voltage_mag'], ...
    'Position', [1435 137 1490 173], ...
    'Operator', 'sqrt', ...
    'OutDataTypeStr', 'T_GJVoltage');

add_line(subsystem, 'voltage_limit/1', 'neg_voltage_limit/1', 'autorouting', 'on');
add_line(subsystem, 'd_pre_sat_voltage/1', 'vd_min_upper/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_limit/1', 'vd_min_upper/2', 'autorouting', 'on');
add_line(subsystem, 'vd_min_upper/1', 'vd_cmd/1', 'autorouting', 'on');
add_line(subsystem, 'neg_voltage_limit/1', 'vd_cmd/2', 'autorouting', 'on');

add_line(subsystem, 'voltage_limit/1', 'voltage_limit_square/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_limit/1', 'voltage_limit_square/2', 'autorouting', 'on');
add_line(subsystem, 'vd_cmd/1', 'vd_cmd_square_for_vq_limit/1', 'autorouting', 'on');
add_line(subsystem, 'vd_cmd/1', 'vd_cmd_square_for_vq_limit/2', 'autorouting', 'on');
add_line(subsystem, 'voltage_limit_square/1', 'vq_limit_square_raw/1', 'autorouting', 'on');
add_line(subsystem, 'vd_cmd_square_for_vq_limit/1', 'vq_limit_square_raw/2', 'autorouting', 'on');
add_line(subsystem, 'vq_limit_square_raw/1', 'vq_limit_square/1', 'autorouting', 'on');
add_line(subsystem, 'zero_voltage/1', 'vq_limit_square/2', 'autorouting', 'on');
add_line(subsystem, 'vq_limit_square/1', 'vq_limit/1', 'autorouting', 'on');
add_line(subsystem, 'vq_limit/1', 'neg_vq_limit/1', 'autorouting', 'on');
add_line(subsystem, 'q_pre_sat_voltage/1', 'vq_min_upper/1', 'autorouting', 'on');
add_line(subsystem, 'vq_limit/1', 'vq_min_upper/2', 'autorouting', 'on');
add_line(subsystem, 'vq_min_upper/1', 'vq_cmd/1', 'autorouting', 'on');
add_line(subsystem, 'neg_vq_limit/1', 'vq_cmd/2', 'autorouting', 'on');

add_line(subsystem, 'vd_cmd/1', 'vd_cmd_square_for_mag/1', 'autorouting', 'on');
add_line(subsystem, 'vd_cmd/1', 'vd_cmd_square_for_mag/2', 'autorouting', 'on');
add_line(subsystem, 'vq_cmd/1', 'vq_cmd_square_for_mag/1', 'autorouting', 'on');
add_line(subsystem, 'vq_cmd/1', 'vq_cmd_square_for_mag/2', 'autorouting', 'on');
add_line(subsystem, 'vd_cmd_square_for_mag/1', 'voltage_mag_square/1', 'autorouting', 'on');
add_line(subsystem, 'vq_cmd_square_for_mag/1', 'voltage_mag_square/2', 'autorouting', 'on');
add_line(subsystem, 'voltage_mag_square/1', 'voltage_mag/1', 'autorouting', 'on');

add_line(subsystem, 'vd_cmd/1', 'd_back_calc_error/1', 'autorouting', 'on');
add_line(subsystem, 'd_pre_sat_voltage/1', 'd_back_calc_error/2', 'autorouting', 'on');
add_line(subsystem, 'vq_cmd/1', 'q_back_calc_error/1', 'autorouting', 'on');
add_line(subsystem, 'q_pre_sat_voltage/1', 'q_back_calc_error/2', 'autorouting', 'on');
end

function add_voltage_normalization(subsystem)
add_block('simulink/Sources/Constant', [subsystem '/one_for_inv_voltage_limit'], ...
    'Position', [830 495 895 525], ...
    'Value', 'single(1)', ...
    'OutDataTypeStr', 'T_GJFloat', ...
    'SampleTime', '-1');
add_block('simulink/Math Operations/Product', [subsystem '/inv_voltage_limit'], ...
    'Position', [930 500 980 535], ...
    'Inputs', '*/', ...
    'OutDataTypeStr', 'T_GJFloat');
add_block('simulink/Math Operations/Product', [subsystem '/vd_norm'], ...
    'Position', [930 315 980 350], ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Product', [subsystem '/vq_norm'], ...
    'Position', [930 375 980 410], ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Product', [subsystem '/voltage_mag_norm'], ...
    'Position', [930 435 980 470], ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Gain', [subsystem '/vd_mod'], ...
    'Position', [1015 315 1075 350], ...
    'Gain', 'VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Gain', [subsystem '/vq_mod'], ...
    'Position', [1015 375 1075 410], ...
    'Gain', 'VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Gain', [subsystem '/voltage_mag_mod'], ...
    'Position', [1015 435 1075 470], ...
    'Gain', 'VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');

add_line(subsystem, 'one_for_inv_voltage_limit/1', 'inv_voltage_limit/1', ...
    'autorouting', 'on');
add_line(subsystem, 'voltage_limit_guard/1', 'inv_voltage_limit/2', ...
    'autorouting', 'on');
add_line(subsystem, 'vd_cmd/1', 'vd_norm/1', 'autorouting', 'on');
add_line(subsystem, 'inv_voltage_limit/1', 'vd_norm/2', 'autorouting', 'on');
add_line(subsystem, 'vq_cmd/1', 'vq_norm/1', 'autorouting', 'on');
add_line(subsystem, 'inv_voltage_limit/1', 'vq_norm/2', 'autorouting', 'on');
add_line(subsystem, 'voltage_mag/1', 'voltage_mag_norm/1', 'autorouting', 'on');
add_line(subsystem, 'inv_voltage_limit/1', 'voltage_mag_norm/2', 'autorouting', 'on');
add_line(subsystem, 'vd_norm/1', 'vd_mod/1', 'autorouting', 'on');
add_line(subsystem, 'vq_norm/1', 'vq_mod/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_mag_norm/1', 'voltage_mag_mod/1', 'autorouting', 'on');
end

function add_square_block(subsystem, block_name, position)
add_block('simulink/Math Operations/Product', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltage');
end

function add_product(subsystem, block_name, position, output_type)
add_block('simulink/Math Operations/Product', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '**', ...
    'OutDataTypeStr', output_type);
end

function add_minmax(subsystem, block_name, position, operator)
add_block('simulink/Math Operations/MinMax', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '2', ...
    'Function', operator);
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
