%% Build green-joint current PI MBD model
%
% Scope is intentionally narrow:
%   dq current reference/feedback -> physical Vdq PI -> unit-circle Vdq
%
% Clarke/Park, current filtering, inverse Park, SVPWM, ADC sector handling,
% and PWM register writes remain outside this generated module.

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

assert_green_joint_safe_rebuild_environment();
run(fullfile(script_dir, 'generate_green_joint_current_loop_dictionary.m'));
contract = evalin('base', 'green_joint_current_loop_contract');

model = contract.model;
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

if exist(model_file, 'file')
    delete(model_file);
end

new_system(model);
set_param(model, ...
    'DataDictionary', contract.dictionary, ...
    'StopTime', '0.001', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(contract.sample_time_s, '%.12g'), ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'ParameterPrecisionLossMsg', 'none', ...
    'InlineParams', 'off', ...
    'CodeInterfacePackaging', 'Reusable function', ...
    'ModelReferenceNumInstancesAllowed', 'Multi');

add_algorithm_boundary(model, contract);

save_system(model, model_file);

fprintf('Built green-joint current PI MBD model:\n  %s\n', model_file);

function add_algorithm_boundary(model, contract)
subsystem = [model '/' contract.step_function];
add_block('simulink/Ports & Subsystems/Subsystem', subsystem, ...
    'Position', [210 85 430 175]);
delete_line(subsystem, 'In1/1', 'Out1/1');
delete_block([subsystem '/In1']);
delete_block([subsystem '/Out1']);

set_param(subsystem, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function', ...
    'RTWFcnNameOpts', 'User specified', ...
    'RTWFcnName', contract.step_function, ...
    'RTWFileNameOpts', 'User specified', ...
    'RTWFileName', contract.step_function);

input_bus = contract.buses{1}.name;
output_bus = contract.buses{2}.name;

add_block('simulink/Sources/In1', [subsystem '/loop_in'], ...
    'Position', [35 220 65 240], ...
    'OutDataTypeStr', ['Bus: ' input_bus], ...
    'BusOutputAsStruct', 'on');
add_block('simulink/Sinks/Out1', [subsystem '/loop_out'], ...
    'Position', [1375 220 1405 240], ...
    'OutDataTypeStr', ['Bus: ' output_bus]);

add_current_pi_algorithm(subsystem, contract, output_bus);

add_block('simulink/Sources/In1', [model '/loop_in'], ...
    'Position', [55 120 85 140], ...
    'OutDataTypeStr', ['Bus: ' input_bus], ...
    'BusOutputAsStruct', 'on');
add_block('simulink/Sinks/Out1', [model '/loop_out'], ...
    'Position', [520 120 550 140], ...
    'OutDataTypeStr', ['Bus: ' output_bus]);

add_line(model, 'loop_in/1', [contract.step_function '/1'], 'autorouting', 'on');
add_line(model, [contract.step_function '/1'], 'loop_out/1', 'autorouting', 'on');
end

function add_current_pi_algorithm(subsystem, contract, output_bus)
ts = num2str(contract.sample_time_s, '%.12g');

add_input_adapter(subsystem, contract);
add_voltage_limit_subsystem(subsystem);
add_current_error_subsystem(subsystem);
add_dq_current_pi_subsystem(subsystem, ts);
add_voltage_allocation_subsystem(subsystem);
add_voltage_normalization_subsystem(subsystem);
add_output_adapter_subsystem(subsystem, output_bus);

add_line(subsystem, 'loop_in/1', 'InputAdapter/1', 'autorouting', 'on');

add_line(subsystem, 'InputAdapter/1', 'CurrentError/1', 'autorouting', 'on');
add_line(subsystem, 'InputAdapter/2', 'CurrentError/2', 'autorouting', 'on');
add_line(subsystem, 'InputAdapter/3', 'CurrentError/3', 'autorouting', 'on');
add_line(subsystem, 'InputAdapter/4', 'CurrentError/4', 'autorouting', 'on');
add_line(subsystem, 'InputAdapter/5', 'VoltageLimit/1', 'autorouting', 'on');

add_line(subsystem, 'CurrentError/1', 'DqCurrentPI/1', 'autorouting', 'on');
add_line(subsystem, 'CurrentError/2', 'DqCurrentPI/2', 'autorouting', 'on');

add_line(subsystem, 'DqCurrentPI/1', ...
    'VdPriorityVoltageAllocation/1', 'autorouting', 'on');
add_line(subsystem, 'DqCurrentPI/2', ...
    'VdPriorityVoltageAllocation/2', 'autorouting', 'on');
add_line(subsystem, 'VoltageLimit/1', ...
    'VdPriorityVoltageAllocation/3', 'autorouting', 'on');

add_line(subsystem, 'VdPriorityVoltageAllocation/1', ...
    'DqCurrentPI/3', 'autorouting', 'on');
add_line(subsystem, 'VdPriorityVoltageAllocation/2', ...
    'DqCurrentPI/4', 'autorouting', 'on');

add_line(subsystem, 'VdPriorityVoltageAllocation/1', ...
    'VoltageNormalization/1', 'autorouting', 'on');
add_line(subsystem, 'VdPriorityVoltageAllocation/2', ...
    'VoltageNormalization/2', 'autorouting', 'on');
add_line(subsystem, 'VdPriorityVoltageAllocation/3', ...
    'VoltageNormalization/3', 'autorouting', 'on');
add_line(subsystem, 'VoltageLimit/2', ...
    'VoltageNormalization/4', 'autorouting', 'on');

add_line(subsystem, 'VdPriorityVoltageAllocation/1', ...
    'OutputAdapter/1', 'autorouting', 'on');
add_line(subsystem, 'VdPriorityVoltageAllocation/2', ...
    'OutputAdapter/2', 'autorouting', 'on');
add_line(subsystem, 'VdPriorityVoltageAllocation/3', ...
    'OutputAdapter/3', 'autorouting', 'on');
add_line(subsystem, 'VoltageNormalization/1', 'OutputAdapter/4', ...
    'autorouting', 'on');
add_line(subsystem, 'VoltageNormalization/2', 'OutputAdapter/5', ...
    'autorouting', 'on');
add_line(subsystem, 'VoltageNormalization/3', 'OutputAdapter/6', ...
    'autorouting', 'on');
add_line(subsystem, 'VoltageNormalization/4', 'OutputAdapter/7', ...
    'autorouting', 'on');
add_line(subsystem, 'VoltageNormalization/5', 'OutputAdapter/8', ...
    'autorouting', 'on');
add_line(subsystem, 'VoltageNormalization/6', 'OutputAdapter/9', ...
    'autorouting', 'on');

add_line(subsystem, 'OutputAdapter/1', 'loop_out/1', 'autorouting', 'on');
end

function add_input_adapter(parent, contract)
input_bus = contract.buses{1}.name;
subsystem = [parent '/InputAdapter'];
add_clean_subsystem(subsystem, [105 95 250 360]);

add_block('simulink/Sources/In1', [subsystem '/loop_in'], ...
    'Position', [35 135 65 155], ...
    'OutDataTypeStr', ['Bus: ' input_bus], ...
    'BusOutputAsStruct', 'on');
add_block('simulink/Signal Routing/Bus Selector', ...
    [subsystem '/input_selector'], ...
    'Position', [115 40 135 275], ...
    'OutputSignals', 'id_ref,iq_ref,id_fbk,iq_fbk,vbus');

output_specs = { ...
    'id_ref', 'T_GJCurrent'; ...
    'iq_ref', 'T_GJCurrent'; ...
    'id_fbk', 'T_GJCurrent'; ...
    'iq_fbk', 'T_GJCurrent'; ...
    'vbus', 'T_GJVoltage'};

for i = 1:size(output_specs, 1)
    y = 45 + (i - 1) * 45;
    add_typed_outport(subsystem, output_specs{i, 1}, ...
        [225 y 255 y + 20], output_specs{i, 2});
    name_line(add_line(subsystem, ['input_selector/' num2str(i)], ...
        [output_specs{i, 1} '/1'], 'autorouting', 'on'), ...
        output_specs{i, 1});
end

add_line(subsystem, 'loop_in/1', 'input_selector/1', 'autorouting', 'on');
end

function add_voltage_limit_subsystem(parent)
subsystem = [parent '/VoltageLimit'];
add_clean_subsystem(subsystem, [315 295 485 405]);
set_param(subsystem, 'TreatAsAtomicUnit', 'on');

add_typed_inport(subsystem, 'vbus', [35 65 65 85], 'T_GJVoltage');
add_typed_outport(subsystem, 'voltage_limit', ...
    [455 55 485 75], 'T_GJVoltage');
add_typed_outport(subsystem, 'voltage_limit_guard', ...
    [455 125 485 145], 'T_GJVoltage');

add_block('simulink/Math Operations/Gain', [subsystem '/voltage_limit_gain'], ...
    'Position', [120 60 210 90], ...
    'Gain', 'VoltageLimitRatio * VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Sources/Constant', [subsystem '/voltage_epsilon'], ...
    'Position', [120 135 210 165], ...
    'Value', 'VoltageEpsilon', ...
    'OutDataTypeStr', 'T_GJVoltage', ...
    'SampleTime', '-1');
add_minmax(subsystem, 'guard_with_epsilon', [285 100 345 155], 'max');

name_line(add_line(subsystem, 'vbus/1', 'voltage_limit_gain/1', ...
    'autorouting', 'on'), 'vbus');
name_line(add_line(subsystem, 'voltage_limit_gain/1', 'voltage_limit/1', ...
    'autorouting', 'on'), 'voltage_limit');
add_line(subsystem, 'voltage_limit_gain/1', 'guard_with_epsilon/1', ...
    'autorouting', 'on');
add_line(subsystem, 'voltage_epsilon/1', 'guard_with_epsilon/2', ...
    'autorouting', 'on');
name_line(add_line(subsystem, 'guard_with_epsilon/1', ...
    'voltage_limit_guard/1', 'autorouting', 'on'), ...
    'voltage_limit_guard');
end

function add_current_error_subsystem(parent)
subsystem = [parent '/CurrentError'];
add_clean_subsystem(subsystem, [315 95 485 250]);

add_typed_inport(subsystem, 'id_ref', [35 45 65 65], 'T_GJCurrent');
add_typed_inport(subsystem, 'iq_ref', [35 125 65 145], 'T_GJCurrent');
add_typed_inport(subsystem, 'id_fbk', [35 85 65 105], 'T_GJCurrent');
add_typed_inport(subsystem, 'iq_fbk', [35 165 65 185], 'T_GJCurrent');
add_typed_outport(subsystem, 'id_err', [425 65 455 85], 'T_GJCurrent');
add_typed_outport(subsystem, 'iq_err', [425 145 455 165], 'T_GJCurrent');

add_block('simulink/Math Operations/Sum', [subsystem '/d_current_error'], ...
    'Position', [150 55 180 100], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_GJCurrent', ...
    'OutDataTypeStr', 'T_GJCurrent');
add_block('simulink/Math Operations/Sum', [subsystem '/q_current_error'], ...
    'Position', [150 135 180 180], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_GJCurrent', ...
    'OutDataTypeStr', 'T_GJCurrent');

add_line(subsystem, 'id_ref/1', 'd_current_error/1', 'autorouting', 'on');
add_line(subsystem, 'id_fbk/1', 'd_current_error/2', 'autorouting', 'on');
add_line(subsystem, 'iq_ref/1', 'q_current_error/1', 'autorouting', 'on');
add_line(subsystem, 'iq_fbk/1', 'q_current_error/2', 'autorouting', 'on');
name_line(add_line(subsystem, 'd_current_error/1', 'id_err/1', ...
    'autorouting', 'on'), 'id_err');
name_line(add_line(subsystem, 'q_current_error/1', 'iq_err/1', ...
    'autorouting', 'on'), 'iq_err');
end

function add_dq_current_pi_subsystem(parent, ts)
subsystem = [parent '/DqCurrentPI'];
add_clean_subsystem(subsystem, [560 85 755 265]);

add_typed_inport(subsystem, 'id_err', [35 70 65 90], 'T_GJCurrent');
add_typed_inport(subsystem, 'iq_err', [35 250 65 270], 'T_GJCurrent');
add_typed_inport(subsystem, 'vd_cmd', [35 130 65 150], 'T_GJVoltage');
add_typed_inport(subsystem, 'vq_cmd', [35 310 65 330], 'T_GJVoltage');
add_typed_outport(subsystem, 'vd_pre', [760 75 790 95], 'T_GJVoltage');
add_typed_outport(subsystem, 'vq_pre', [760 255 790 275], 'T_GJVoltage');

add_pi_axis(subsystem, 'd', 'id_err/1', 'vd_cmd/1', ...
    'CurDKp', 'CurDKi', ts, 45);
add_pi_axis(subsystem, 'q', 'iq_err/1', 'vq_cmd/1', ...
    'CurQKp', 'CurQKi', ts, 225);
end

function add_pi_axis(subsystem, axis, error_port, allocated_voltage_port, ...
    kp_name, ki_name, ts, y)
kp_block = [axis '_kp'];
ki_block = [axis '_ki'];
state_name = [axis '_integrator_state'];
pre_sat_name = [axis '_pre_sat_voltage'];
back_calc_name = [axis '_back_calc_error'];
kaw_name = [axis '_kaw'];
rate_name = [axis '_integrator_rate'];
delta_name = [axis '_integrator_delta'];
next_name = [axis '_integrator_next'];
output_name = ['v' axis '_pre'];

add_block('simulink/Math Operations/Gain', [subsystem '/' kp_block], ...
    'Position', [125 y 195 y + 30], ...
    'Gain', kp_name, ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/' ki_block], ...
    'Position', [125 y + 55 195 y + 85], ...
    'Gain', ki_name, ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Discrete/Unit Delay', [subsystem '/' state_name], ...
    'Position', [250 y + 95 315 y + 125], ...
    'InitialCondition', 'single(0)', ...
    'SampleTime', ts);
add_block('simulink/Math Operations/Sum', [subsystem '/' pre_sat_name], ...
    'Position', [365 y + 5 395 y + 50], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Sum', [subsystem '/' back_calc_name], ...
    'Position', [450 y + 95 480 y + 140], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/' kaw_name], ...
    'Position', [515 y + 102 585 y + 132], ...
    'Gain', 'PiCorrectionGain', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Sum', [subsystem '/' rate_name], ...
    'Position', [620 y + 85 650 y + 130], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/' delta_name], ...
    'Position', [680 y + 92 750 y + 122], ...
    'Gain', ['single(' ts ')'], ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Sum', [subsystem '/' next_name], ...
    'Position', [790 y + 100 820 y + 145], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');

add_line(subsystem, error_port, [kp_block '/1'], 'autorouting', 'on');
add_line(subsystem, error_port, [ki_block '/1'], 'autorouting', 'on');
add_line(subsystem, [kp_block '/1'], [pre_sat_name '/1'], 'autorouting', 'on');
add_line(subsystem, [state_name '/1'], [pre_sat_name '/2'], 'autorouting', 'on');
add_line(subsystem, [ki_block '/1'], [rate_name '/1'], 'autorouting', 'on');
add_line(subsystem, allocated_voltage_port, [back_calc_name '/1'], ...
    'autorouting', 'on');
add_line(subsystem, [pre_sat_name '/1'], [back_calc_name '/2'], ...
    'autorouting', 'on');
add_line(subsystem, [back_calc_name '/1'], [kaw_name '/1'], 'autorouting', 'on');
add_line(subsystem, [kaw_name '/1'], [rate_name '/2'], 'autorouting', 'on');
add_line(subsystem, [rate_name '/1'], [delta_name '/1'], 'autorouting', 'on');
add_line(subsystem, [state_name '/1'], [next_name '/1'], 'autorouting', 'on');
add_line(subsystem, [delta_name '/1'], [next_name '/2'], 'autorouting', 'on');
add_line(subsystem, [next_name '/1'], [state_name '/1'], 'autorouting', 'on');
name_line(add_line(subsystem, [pre_sat_name '/1'], [output_name '/1'], ...
    'autorouting', 'on'), output_name);
end

function add_voltage_allocation_subsystem(parent)
subsystem = [parent '/VdPriorityVoltageAllocation'];
add_clean_subsystem(subsystem, [820 85 1045 300]);
set_param(subsystem, 'TreatAsAtomicUnit', 'on');

add_typed_inport(subsystem, 'vd_pre', [35 55 65 75], 'T_GJVoltage');
add_typed_inport(subsystem, 'vq_pre', [35 250 65 270], 'T_GJVoltage');
add_typed_inport(subsystem, 'voltage_limit', ...
    [35 360 65 380], 'T_GJVoltage');
add_typed_outport(subsystem, 'vd_cmd', [855 70 885 90], 'T_GJVoltage');
add_typed_outport(subsystem, 'vq_cmd', [855 260 885 280], 'T_GJVoltage');
add_typed_outport(subsystem, 'voltage_mag', ...
    [855 150 885 170], 'T_GJVoltage');

add_block('simulink/Math Operations/Gain', [subsystem '/neg_voltage_limit'], ...
    'Position', [115 360 185 390], ...
    'Gain', '-1', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_minmax(subsystem, 'vd_min_upper', [150 45 210 80], 'min');
add_minmax(subsystem, 'vd_cmd_limit', [250 45 310 80], 'max');

add_square_block(subsystem, 'voltage_limit_square', [250 395 300 430]);
add_square_block(subsystem, 'vd_cmd_square_for_vq_limit', [350 110 400 145]);
add_block('simulink/Math Operations/Sum', [subsystem '/vq_limit_square_raw'], ...
    'Position', [455 155 485 200], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Sources/Constant', [subsystem '/zero_voltage'], ...
    'Position', [455 225 515 255], ...
    'Value', 'single(0)', ...
    'OutDataTypeStr', 'T_GJVoltage', ...
    'SampleTime', '-1');
add_minmax(subsystem, 'vq_limit_square', [535 170 595 225], 'max');
add_block('simulink/Math Operations/Math Function', [subsystem '/vq_limit'], ...
    'Position', [625 180 680 215], ...
    'Operator', 'sqrt', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Gain', [subsystem '/neg_vq_limit'], ...
    'Position', [625 250 685 280], ...
    'Gain', '-1', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_minmax(subsystem, 'vq_min_upper', [710 240 770 275], 'min');
add_minmax(subsystem, 'vq_cmd_limit', [805 240 865 275], 'max');

add_square_block(subsystem, 'vd_cmd_square_for_mag', [350 35 400 70]);
add_square_block(subsystem, 'vq_cmd_square_for_mag', [900 240 950 275]);
add_block('simulink/Math Operations/Sum', [subsystem '/voltage_mag_square'], ...
    'Position', [575 95 605 145], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_GJVoltage', ...
    'OutDataTypeStr', 'T_GJVoltage');
add_block('simulink/Math Operations/Math Function', ...
    [subsystem '/voltage_mag_calc'], ...
    'Position', [640 102 695 138], ...
    'Operator', 'sqrt', ...
    'OutDataTypeStr', 'T_GJVoltage');

add_line(subsystem, 'voltage_limit/1', 'neg_voltage_limit/1', ...
    'autorouting', 'on');
add_line(subsystem, 'vd_pre/1', 'vd_min_upper/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_limit/1', 'vd_min_upper/2', 'autorouting', 'on');
add_line(subsystem, 'vd_min_upper/1', 'vd_cmd_limit/1', 'autorouting', 'on');
add_line(subsystem, 'neg_voltage_limit/1', 'vd_cmd_limit/2', 'autorouting', 'on');

add_line(subsystem, 'voltage_limit/1', 'voltage_limit_square/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_limit/1', 'voltage_limit_square/2', 'autorouting', 'on');
add_line(subsystem, 'vd_cmd_limit/1', 'vd_cmd_square_for_vq_limit/1', ...
    'autorouting', 'on');
add_line(subsystem, 'vd_cmd_limit/1', 'vd_cmd_square_for_vq_limit/2', ...
    'autorouting', 'on');
add_line(subsystem, 'voltage_limit_square/1', 'vq_limit_square_raw/1', 'autorouting', 'on');
add_line(subsystem, 'vd_cmd_square_for_vq_limit/1', 'vq_limit_square_raw/2', 'autorouting', 'on');
add_line(subsystem, 'vq_limit_square_raw/1', 'vq_limit_square/1', 'autorouting', 'on');
add_line(subsystem, 'zero_voltage/1', 'vq_limit_square/2', 'autorouting', 'on');
add_line(subsystem, 'vq_limit_square/1', 'vq_limit/1', 'autorouting', 'on');
add_line(subsystem, 'vq_limit/1', 'neg_vq_limit/1', 'autorouting', 'on');
add_line(subsystem, 'vq_pre/1', 'vq_min_upper/1', 'autorouting', 'on');
add_line(subsystem, 'vq_limit/1', 'vq_min_upper/2', 'autorouting', 'on');
add_line(subsystem, 'vq_min_upper/1', 'vq_cmd_limit/1', 'autorouting', 'on');
add_line(subsystem, 'neg_vq_limit/1', 'vq_cmd_limit/2', 'autorouting', 'on');

add_line(subsystem, 'vd_cmd_limit/1', 'vd_cmd_square_for_mag/1', ...
    'autorouting', 'on');
add_line(subsystem, 'vd_cmd_limit/1', 'vd_cmd_square_for_mag/2', ...
    'autorouting', 'on');
add_line(subsystem, 'vq_cmd_limit/1', 'vq_cmd_square_for_mag/1', ...
    'autorouting', 'on');
add_line(subsystem, 'vq_cmd_limit/1', 'vq_cmd_square_for_mag/2', ...
    'autorouting', 'on');
add_line(subsystem, 'vd_cmd_square_for_mag/1', 'voltage_mag_square/1', 'autorouting', 'on');
add_line(subsystem, 'vq_cmd_square_for_mag/1', 'voltage_mag_square/2', 'autorouting', 'on');
add_line(subsystem, 'voltage_mag_square/1', 'voltage_mag_calc/1', ...
    'autorouting', 'on');

name_line(add_line(subsystem, 'vd_cmd_limit/1', 'vd_cmd/1', ...
    'autorouting', 'on'), 'vd_cmd');
name_line(add_line(subsystem, 'vq_cmd_limit/1', 'vq_cmd/1', ...
    'autorouting', 'on'), 'vq_cmd');
name_line(add_line(subsystem, 'voltage_mag_calc/1', 'voltage_mag/1', ...
    'autorouting', 'on'), 'voltage_mag');
end

function add_voltage_normalization_subsystem(parent)
subsystem = [parent '/VoltageNormalization'];
add_clean_subsystem(subsystem, [1110 110 1295 350]);
set_param(subsystem, 'TreatAsAtomicUnit', 'on');

add_typed_inport(subsystem, 'vd_cmd', [35 45 65 65], 'T_GJVoltage');
add_typed_inport(subsystem, 'vq_cmd', [35 105 65 125], 'T_GJVoltage');
add_typed_inport(subsystem, 'voltage_mag', [35 165 65 185], 'T_GJVoltage');
add_typed_inport(subsystem, 'voltage_limit_guard', ...
    [35 255 65 275], 'T_GJVoltage');
add_typed_outport(subsystem, 'vd_norm', [640 45 670 65], ...
    'T_GJVoltageNorm');
add_typed_outport(subsystem, 'vq_norm', [640 105 670 125], ...
    'T_GJVoltageNorm');
add_typed_outport(subsystem, 'voltage_mag_norm', ...
    [640 165 670 185], 'T_GJVoltageNorm');
add_typed_outport(subsystem, 'vd_mod', [640 235 670 255], ...
    'T_GJVoltageNorm');
add_typed_outport(subsystem, 'vq_mod', [640 295 670 315], ...
    'T_GJVoltageNorm');
add_typed_outport(subsystem, 'voltage_mag_mod', ...
    [640 355 670 375], 'T_GJVoltageNorm');

add_block('simulink/Sources/Constant', [subsystem '/one_for_inv_voltage_limit'], ...
    'Position', [135 235 200 265], ...
    'Value', 'single(1)', ...
    'OutDataTypeStr', 'T_GJFloat', ...
    'SampleTime', '-1');
add_block('simulink/Math Operations/Product', [subsystem '/inv_voltage_limit'], ...
    'Position', [240 240 290 275], ...
    'Inputs', '*/', ...
    'OutDataTypeStr', 'T_GJFloat');
add_block('simulink/Math Operations/Product', [subsystem '/vd_norm_calc'], ...
    'Position', [235 40 285 75], ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Product', [subsystem '/vq_norm_calc'], ...
    'Position', [235 100 285 135], ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Product', ...
    [subsystem '/voltage_mag_norm_calc'], ...
    'Position', [235 160 285 195], ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Gain', [subsystem '/vd_mod_calc'], ...
    'Position', [400 230 460 265], ...
    'Gain', 'VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Gain', [subsystem '/vq_mod_calc'], ...
    'Position', [400 290 460 325], ...
    'Gain', 'VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');
add_block('simulink/Math Operations/Gain', ...
    [subsystem '/voltage_mag_mod_calc'], ...
    'Position', [400 350 460 385], ...
    'Gain', 'VoltageModulationRatio', ...
    'ParamDataTypeStr', 'T_GJFloat', ...
    'OutDataTypeStr', 'T_GJVoltageNorm');

add_line(subsystem, 'one_for_inv_voltage_limit/1', 'inv_voltage_limit/1', ...
    'autorouting', 'on');
add_line(subsystem, 'voltage_limit_guard/1', 'inv_voltage_limit/2', ...
    'autorouting', 'on');
add_line(subsystem, 'vd_cmd/1', 'vd_norm_calc/1', 'autorouting', 'on');
add_line(subsystem, 'inv_voltage_limit/1', 'vd_norm_calc/2', 'autorouting', 'on');
add_line(subsystem, 'vq_cmd/1', 'vq_norm_calc/1', 'autorouting', 'on');
add_line(subsystem, 'inv_voltage_limit/1', 'vq_norm_calc/2', 'autorouting', 'on');
add_line(subsystem, 'voltage_mag/1', 'voltage_mag_norm_calc/1', ...
    'autorouting', 'on');
add_line(subsystem, 'inv_voltage_limit/1', 'voltage_mag_norm_calc/2', ...
    'autorouting', 'on');
add_line(subsystem, 'vd_norm_calc/1', 'vd_mod_calc/1', 'autorouting', 'on');
add_line(subsystem, 'vq_norm_calc/1', 'vq_mod_calc/1', 'autorouting', 'on');
add_line(subsystem, 'voltage_mag_norm_calc/1', ...
    'voltage_mag_mod_calc/1', 'autorouting', 'on');

name_line(add_line(subsystem, 'vd_norm_calc/1', 'vd_norm/1', ...
    'autorouting', 'on'), 'vd_norm');
name_line(add_line(subsystem, 'vq_norm_calc/1', 'vq_norm/1', ...
    'autorouting', 'on'), 'vq_norm');
name_line(add_line(subsystem, 'voltage_mag_norm_calc/1', ...
    'voltage_mag_norm/1', 'autorouting', 'on'), 'voltage_mag_norm');
name_line(add_line(subsystem, 'vd_mod_calc/1', 'vd_mod/1', ...
    'autorouting', 'on'), 'vd_mod');
name_line(add_line(subsystem, 'vq_mod_calc/1', 'vq_mod/1', ...
    'autorouting', 'on'), 'vq_mod');
name_line(add_line(subsystem, 'voltage_mag_mod_calc/1', ...
    'voltage_mag_mod/1', 'autorouting', 'on'), 'voltage_mag_mod');
end

function add_output_adapter_subsystem(parent, output_bus)
subsystem = [parent '/OutputAdapter'];
add_clean_subsystem(subsystem, [1320 90 1460 370]);

output_specs = { ...
    'vd_cmd', 'T_GJVoltage'; ...
    'vq_cmd', 'T_GJVoltage'; ...
    'voltage_mag', 'T_GJVoltage'; ...
    'vd_norm', 'T_GJVoltageNorm'; ...
    'vq_norm', 'T_GJVoltageNorm'; ...
    'voltage_mag_norm', 'T_GJVoltageNorm'; ...
    'vd_mod', 'T_GJVoltageNorm'; ...
    'vq_mod', 'T_GJVoltageNorm'; ...
    'voltage_mag_mod', 'T_GJVoltageNorm'};

for i = 1:size(output_specs, 1)
    y = 35 + (i - 1) * 40;
    add_typed_inport(subsystem, output_specs{i, 1}, ...
        [35 y 65 y + 20], output_specs{i, 2});
end

add_block('simulink/Signal Routing/Bus Creator', ...
    [subsystem '/pi_output_bus_creator'], ...
    'Position', [165 35 180 360], ...
    'Inputs', '9', ...
    'UseBusObject', 'on', ...
    'BusObject', output_bus, ...
    'NonVirtualBus', 'on');
add_typed_outport(subsystem, 'loop_out', ...
    [260 185 290 205], ['Bus: ' output_bus]);

for i = 1:size(output_specs, 1)
    name_line(add_line(subsystem, [output_specs{i, 1} '/1'], ...
        ['pi_output_bus_creator/' num2str(i)], 'autorouting', 'on'), ...
        output_specs{i, 1});
end
add_line(subsystem, 'pi_output_bus_creator/1', 'loop_out/1', ...
    'autorouting', 'on');
end

function add_square_block(subsystem, block_name, position)
add_block('simulink/Math Operations/Product', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '**', ...
    'OutDataTypeStr', 'T_GJVoltage');
end

function add_minmax(subsystem, block_name, position, operator)
add_block('simulink/Math Operations/MinMax', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '2', ...
    'Function', operator);
end

function add_clean_subsystem(subsystem, position)
add_block('simulink/Ports & Subsystems/Subsystem', subsystem, ...
    'Position', position);
lines = find_system(subsystem, 'SearchDepth', 1, 'FindAll', 'on', ...
    'Type', 'line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(subsystem, 'SearchDepth', 1, 'Type', 'Block');
for i = 2:numel(blocks)
    delete_block(blocks{i});
end
end

function add_typed_inport(subsystem, block_name, position, data_type)
add_block('simulink/Sources/In1', [subsystem '/' block_name], ...
    'Position', position, ...
    'OutDataTypeStr', data_type);
end

function add_typed_outport(subsystem, block_name, position, data_type)
add_block('simulink/Sinks/Out1', [subsystem '/' block_name], ...
    'Position', position, ...
    'OutDataTypeStr', data_type);
end

function name_line(line_handle, signal_name)
try
    set_param(line_handle, 'Name', signal_name);
catch
end
end
