%% Build a float-based open-loop motor simulation architecture
%
% Architecture:
%   open_loop_cmd_t -> DqToAbcDutyStep -> phase_duty_t
%   phase_duty_t + dc_bus_t -> Average-Value Inverter -> PMSM plant
%
% This is the first MBD architecture milestone for a new motor simulation
% stack. It intentionally uses single-precision float types everywhere at the
% controller interface. Fixed-point design can be introduced later through the
% same data-dictionary pattern.

clc;

cfg = customer_interface_config();
script_dir = fileparts(mfilename('fullpath'));
cfg.dictionaryFile = fullfile(script_dir, cfg.dictionaryName);
assignin('base', 'motor_float_open_loop_config', cfg);
previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

open_loop_params = default_open_loop_params(cfg);
assignin('base', 'motor', open_loop_params.motor);
assignin('base', 'inverter', open_loop_params.inverter);
assignin('base', 'simcfg', open_loop_params.simcfg);
assignin('base', 'openloop', open_loop_params.openloop);

model = cfg.modelName;
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

close_open_data_dictionaries();
create_motor_data_dictionary(cfg);

if exist(model_file, 'file')
    delete(model_file);
end

load_system('mcbplantlib');
load_system('mcblib');

new_system(model);
set_param(model, 'DataDictionary', cfg.dictionaryName);
set_param(model, ...
    'StopTime', 'simcfg.stop_time', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'simcfg.Ts_plant', ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'InlineParams', 'on');

set_param(model, ...
    'CodeInterfacePackaging', 'Reusable function', ...
    'ModelReferenceNumInstancesAllowed', 'Multi');

add_open_loop_command_subsystem(model, cfg);
add_dq_to_abc_duty_subsystem(model, cfg);
add_average_inverter_and_plant(model, cfg);
add_log_outputs(model, 'feedback_bus_creator/1');
add_duty_log_outputs(model);

set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built float open-loop motor simulation model:\n  %s\n', model_file);

function cfg = customer_interface_config()
% Customer-editable interface and architecture contract.
cfg.modelName = 'motor_float_open_loop_model';
cfg.sampleTime = 'simcfg.Ts_ctrl';
cfg.plantSampleTime = 'simcfg.Ts_plant';
cfg.rebuildDictionary = true;

cfg.dictionaryName = 'motor_float_interface.sldd';
cfg.typeHeaderFile = 'motor_float_types.h';

cfg.realTypeName = 'T_MotorFloat';
cfg.voltageTypeName = 'T_MotorVoltage';
cfg.angleTypeName = 'T_MotorAngle';
cfg.currentTypeName = 'T_MotorCurrent';
cfg.speedTypeName = 'T_MotorSpeed';
cfg.torqueTypeName = 'T_MotorTorque';
cfg.dutyTypeName = 'T_DutyRatio';

cfg.openLoopCmdBusName = 'open_loop_cmd_t';
cfg.phaseDutyBusName = 'phase_duty_t';
cfg.dcBusName = 'dc_bus_t';
cfg.plantFeedbackBusName = 'plant_feedback_t';

cfg.floatBaseType = 'single';
end

function p = default_open_loop_params(~)
% Float-first baseline inspired by average-inverter/motor_control_params.m.
p.simcfg.stop_time = 0.20;
% Keep scheduler/sample-time values as double. Controller signal types are
% single, but Simulink block SampleTime parameters expect double scalars.
p.simcfg.Ts_plant = 25e-6;
p.simcfg.Ts_ctrl = 50e-6;

% Plant/library parameters stay double for robust Motor Control Blockset
% propagation. Controller-facing constants explicitly output T_MotorFloat.
p.inverter.Vdc = 68;
p.inverter.load_torque = 0;

p.motor.type = 'SPMSM';
p.motor.pole_pairs = 10;
p.motor.back_emf_vrms_per_krpm = 17.03;
p.motor.line_to_line_resistance = 0.4267;
p.motor.line_to_line_inductance = 0.53e-3;
p.motor.Rs = p.motor.line_to_line_resistance / 2;
p.motor.Ld = p.motor.line_to_line_inductance / 2;
p.motor.Lq = p.motor.Ld;
p.motor.psi_f = p.motor.back_emf_vrms_per_krpm / ...
    (sqrt(3/2) * p.motor.pole_pairs * (1000 * 2 * pi / 60));
p.motor.J = 2.5e-4;
p.motor.B = 1.0e-4;

p.openloop.vd = single(0);
p.openloop.vq = single(5);
p.openloop.freq_hz = single(20);
end

function close_open_data_dictionaries()
try
    Simulink.data.dictionary.closeAll('-discard');
catch err
    warning('Could not close open data dictionaries before rebuild: %s', ...
        err.message);
end
end

function create_motor_data_dictionary(cfg)
dd = open_or_create_data_dictionary(cfg);
design_data = getSection(dd, 'Design Data');

upsert_alias_type(design_data, cfg.realTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.voltageTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.angleTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.currentTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.speedTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.torqueTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.dutyTypeName, cfg.floatBaseType, cfg.typeHeaderFile);

upsert_bus_type(design_data, cfg.openLoopCmdBusName, cfg.typeHeaderFile, { ...
    {'vd', cfg.voltageTypeName}; ...
    {'vq', cfg.voltageTypeName}; ...
    {'theta_e', cfg.angleTypeName}; ...
    {'vdc', cfg.voltageTypeName}});

upsert_bus_type(design_data, cfg.phaseDutyBusName, cfg.typeHeaderFile, { ...
    {'da', cfg.dutyTypeName}; ...
    {'db', cfg.dutyTypeName}; ...
    {'dc', cfg.dutyTypeName}});

upsert_bus_type(design_data, cfg.dcBusName, cfg.typeHeaderFile, { ...
    {'vdc', cfg.voltageTypeName}});

upsert_bus_type(design_data, cfg.plantFeedbackBusName, cfg.typeHeaderFile, { ...
    {'ia', cfg.currentTypeName}; ...
    {'ib', cfg.currentTypeName}; ...
    {'ic', cfg.currentTypeName}; ...
    {'wm', cfg.speedTypeName}; ...
    {'theta_m', cfg.angleTypeName}; ...
    {'theta_e', cfg.angleTypeName}});

saveChanges(dd);
close(dd);
end

function dd = open_or_create_data_dictionary(cfg)
if isfield(cfg, 'rebuildDictionary') && cfg.rebuildDictionary && exist(cfg.dictionaryFile, 'file')
    delete(cfg.dictionaryFile);
end

if exist(cfg.dictionaryFile, 'file')
    try
        dd = Simulink.data.dictionary.open(cfg.dictionaryFile);
        getSection(dd, 'Design Data');
        return;
    catch err
        warning('Rebuilding data dictionary "%s" because it could not be opened: %s', ...
            cfg.dictionaryFile, err.message);
        close_open_data_dictionaries();
        backup_file = backup_bad_dictionary(cfg.dictionaryFile);
        fprintf('Backed up unusable data dictionary:\n  %s\n', backup_file);
    end
end

dd = Simulink.data.dictionary.create(cfg.dictionaryFile);
end

function backup_file = backup_bad_dictionary(dictionary_file)
[folder, name, ext] = fileparts(dictionary_file);
timestamp = datestr(now, 'yyyymmdd_HHMMSS');
backup_file = fullfile(folder, [name '_bad_' timestamp ext]);
index = 1;

while exist(backup_file, 'file')
    backup_file = fullfile(folder, sprintf('%s_bad_%s_%d%s', ...
        name, timestamp, index, ext));
    index = index + 1;
end

movefile(dictionary_file, backup_file);
end

function upsert_alias_type(section, type_name, base_type, header_file)
alias_type = Simulink.AliasType(base_type);
alias_type.DataScope = 'Exported';
alias_type.HeaderFile = header_file;

entry = find(section, 'Name', type_name);
if isempty(entry)
    addEntry(section, type_name, alias_type);
else
    setValue(entry(1), alias_type);
end
end

function upsert_bus_type(section, bus_name, header_file, element_specs)
bus_elements = repmat(Simulink.BusElement, numel(element_specs), 1);
for i = 1:numel(element_specs)
    bus_elements(i).Name = element_specs{i}{1};
    bus_elements(i).DataType = element_specs{i}{2};
    bus_elements(i).Dimensions = 1;
end

bus_type = Simulink.Bus;
bus_type.Elements = bus_elements;
bus_type.DataScope = 'Exported';
bus_type.HeaderFile = header_file;

entry = find(section, 'Name', bus_name);
if isempty(entry)
    addEntry(section, bus_name, bus_type);
else
    setValue(entry(1), bus_type);
end
end

function add_open_loop_command_subsystem(model, cfg)
subsystem = [model '/OpenLoopCommand'];
add_clean_subsystem(subsystem, [80 80 255 185]);

set_param(subsystem, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function', ...
    'RTWFcnNameOpts', 'User specified', ...
    'RTWFcnName', 'OpenLoopCommandStep', ...
    'RTWFileNameOpts', 'User specified', ...
    'RTWFileName', 'OpenLoopCommandStep');

add_typed_constant(subsystem, 'vd', [35 35 85 65], ...
    'openloop.vd', cfg.voltageTypeName, cfg.sampleTime);
add_typed_constant(subsystem, 'vq', [35 80 85 110], ...
    'openloop.vq', cfg.voltageTypeName, cfg.sampleTime);
add_typed_constant(subsystem, 'freq_hz', [35 190 105 220], ...
    'openloop.freq_hz', cfg.realTypeName, cfg.sampleTime);
add_typed_constant(subsystem, 'vdc', [35 245 85 275], ...
    'inverter.Vdc', cfg.voltageTypeName, cfg.sampleTime);

add_block('simulink/Math Operations/Gain', [subsystem '/omega_e'], ...
    'Position', [125 185 190 220], ...
    'Gain', '2*pi', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.realTypeName);
add_block('simulink/Math Operations/Gain', [subsystem '/theta_step'], ...
    'Position', [220 185 285 220], ...
    'Gain', 'simcfg.Ts_ctrl', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.angleTypeName);
add_block('simulink/Discrete/Unit Delay', [subsystem '/theta_state'], ...
    'Position', [220 120 285 150], ...
    'InitialCondition', '0', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Math Operations/Sum', [subsystem '/theta_sum'], ...
    'Position', [325 145 355 205], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', cfg.angleTypeName, ...
    'OutDataTypeStr', cfg.angleTypeName);
add_block('simulink/Sources/Constant', [subsystem '/two_pi'], ...
    'Position', [300 235 350 255], ...
    'Value', '2*pi', ...
    'OutDataTypeStr', cfg.angleTypeName, ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Math Operations/Math Function', [subsystem '/theta_mod'], ...
    'Position', [390 160 455 200], ...
    'Operator', 'mod', ...
    'OutDataTypeStr', cfg.angleTypeName);

add_block('simulink/Signal Routing/Bus Creator', [subsystem '/cmd_bus_creator'], ...
    'Position', [515 45 530 275], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.openLoopCmdBusName, ...
    'NonVirtualBus', 'on');

add_block('simulink/Sinks/Out1', [subsystem '/cmd_out'], ...
    'Position', [600 150 630 170], ...
    'OutDataTypeStr', ['Bus: ' cfg.openLoopCmdBusName]);

add_line(subsystem, 'freq_hz/1', 'omega_e/1', 'autorouting', 'on');
add_line(subsystem, 'omega_e/1', 'theta_step/1', 'autorouting', 'on');
add_line(subsystem, 'theta_state/1', 'theta_sum/1', 'autorouting', 'on');
add_line(subsystem, 'theta_step/1', 'theta_sum/2', 'autorouting', 'on');
add_line(subsystem, 'theta_sum/1', 'theta_mod/1', 'autorouting', 'on');
add_line(subsystem, 'two_pi/1', 'theta_mod/2', 'autorouting', 'on');
add_line(subsystem, 'theta_mod/1', 'theta_state/1', 'autorouting', 'on');

name_line(add_line(subsystem, 'vd/1', 'cmd_bus_creator/1', 'autorouting', 'on'), 'vd');
name_line(add_line(subsystem, 'vq/1', 'cmd_bus_creator/2', 'autorouting', 'on'), 'vq');
name_line(add_line(subsystem, 'theta_mod/1', 'cmd_bus_creator/3', 'autorouting', 'on'), 'theta_e');
name_line(add_line(subsystem, 'vdc/1', 'cmd_bus_creator/4', 'autorouting', 'on'), 'vdc');
add_line(subsystem, 'cmd_bus_creator/1', 'cmd_out/1', 'autorouting', 'on');
end

function add_dq_to_abc_duty_subsystem(model, cfg)
subsystem = [model '/DqToAbcDutyStep'];
add_clean_subsystem(subsystem, [340 70 540 195]);

set_param(subsystem, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function', ...
    'RTWFcnNameOpts', 'User specified', ...
    'RTWFcnName', 'DqToAbcDutyStep', ...
    'RTWFileNameOpts', 'User specified', ...
    'RTWFileName', 'DqToAbcDutyStep');

add_block('simulink/Sources/In1', [subsystem '/cmd_in'], ...
    'Position', [35 145 65 165], ...
    'OutDataTypeStr', ['Bus: ' cfg.openLoopCmdBusName], ...
    'BusOutputAsStruct', 'on');

add_block('simulink/Signal Routing/Bus Selector', [subsystem '/cmd_selector'], ...
    'Position', [100 70 115 235], ...
    'OutputSignals', 'vd,vq,theta_e,vdc');

add_block('simulink/Math Operations/Trigonometric Function', ...
    [subsystem '/cos_theta'], ...
    'Position', [165 135 220 165], ...
    'Operator', 'cos');
add_block('simulink/Math Operations/Trigonometric Function', ...
    [subsystem '/sin_theta'], ...
    'Position', [165 185 220 215], ...
    'Operator', 'sin');

add_product(subsystem, 'vd_cos', [275 55 325 85], cfg);
add_product(subsystem, 'vq_sin', [275 105 325 135], cfg);
add_product(subsystem, 'vd_sin', [275 165 325 195], cfg);
add_product(subsystem, 'vq_cos', [275 215 325 245], cfg);

add_sum(subsystem, 'v_alpha_sum', [370 75 400 125], '+-', cfg);
add_sum(subsystem, 'v_beta_sum', [370 185 400 235], '++', cfg);

add_block('simulink/Math Operations/Gain', [subsystem '/vb_alpha_gain'], ...
    'Position', [450 70 510 100], ...
    'Gain', '-0.5', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.voltageTypeName);
add_block('simulink/Math Operations/Gain', [subsystem '/vb_beta_gain'], ...
    'Position', [450 120 510 150], ...
    'Gain', 'sqrt(3)/2', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.voltageTypeName);
add_block('simulink/Math Operations/Gain', [subsystem '/vc_alpha_gain'], ...
    'Position', [450 200 510 230], ...
    'Gain', '-0.5', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.voltageTypeName);
add_block('simulink/Math Operations/Gain', [subsystem '/vc_beta_gain'], ...
    'Position', [450 250 510 280], ...
    'Gain', '-sqrt(3)/2', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.voltageTypeName);

add_sum(subsystem, 'vb_sum', [555 100 585 150], '++', cfg);
add_sum(subsystem, 'vc_sum', [555 230 585 280], '++', cfg);

add_minmax(subsystem, 'v_max', [640 95 700 135], 'max');
add_minmax(subsystem, 'v_min', [640 180 700 220], 'min');
add_sum(subsystem, 'zero_sum', [745 135 775 180], '++', cfg);
add_block('simulink/Math Operations/Gain', [subsystem '/zero_gain'], ...
    'Position', [810 145 870 175], ...
    'Gain', '-0.5', ...
    'ParamDataTypeStr', cfg.realTypeName, ...
    'OutDataTypeStr', cfg.voltageTypeName);

add_sum(subsystem, 'va_svpwm_sum', [920 55 950 100], '++', cfg);
add_sum(subsystem, 'vb_svpwm_sum', [920 145 950 190], '++', cfg);
add_sum(subsystem, 'vc_svpwm_sum', [920 235 950 280], '++', cfg);

add_block('simulink/Math Operations/Product', [subsystem '/da_ratio_calc'], ...
    'Position', [1015 60 1065 95], ...
    'Inputs', '*/', ...
    'OutDataTypeStr', cfg.dutyTypeName);
add_block('simulink/Math Operations/Product', [subsystem '/db_ratio_calc'], ...
    'Position', [1015 150 1065 185], ...
    'Inputs', '*/', ...
    'OutDataTypeStr', cfg.dutyTypeName);
add_block('simulink/Math Operations/Product', [subsystem '/dc_ratio_calc'], ...
    'Position', [1015 240 1065 275], ...
    'Inputs', '*/', ...
    'OutDataTypeStr', cfg.dutyTypeName);

add_block('simulink/Sources/Constant', [subsystem '/duty_half'], ...
    'Position', [1045 315 1095 340], ...
    'Value', '0.5', ...
    'OutDataTypeStr', cfg.dutyTypeName, ...
    'SampleTime', cfg.sampleTime);
add_duty_sum(subsystem, 'da_duty_sum', [1110 55 1140 100], cfg);
add_duty_sum(subsystem, 'db_duty_sum', [1110 145 1140 190], cfg);
add_duty_sum(subsystem, 'dc_duty_sum', [1110 235 1140 280], cfg);

add_block('simulink/Signal Routing/Bus Creator', [subsystem '/phase_duty_bus_creator'], ...
    'Position', [1190 65 1205 275], ...
    'Inputs', '3', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.phaseDutyBusName, ...
    'NonVirtualBus', 'on');

add_block('simulink/Sinks/Out1', [subsystem '/phase_duty_out'], ...
    'Position', [1270 155 1300 175], ...
    'OutDataTypeStr', ['Bus: ' cfg.phaseDutyBusName]);

add_line(subsystem, 'cmd_in/1', 'cmd_selector/1', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/3', 'cos_theta/1', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/3', 'sin_theta/1', 'autorouting', 'on');

add_line(subsystem, 'cmd_selector/1', 'vd_cos/1', 'autorouting', 'on');
add_line(subsystem, 'cos_theta/1', 'vd_cos/2', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/2', 'vq_sin/1', 'autorouting', 'on');
add_line(subsystem, 'sin_theta/1', 'vq_sin/2', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/1', 'vd_sin/1', 'autorouting', 'on');
add_line(subsystem, 'sin_theta/1', 'vd_sin/2', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/2', 'vq_cos/1', 'autorouting', 'on');
add_line(subsystem, 'cos_theta/1', 'vq_cos/2', 'autorouting', 'on');

add_line(subsystem, 'vd_cos/1', 'v_alpha_sum/1', 'autorouting', 'on');
add_line(subsystem, 'vq_sin/1', 'v_alpha_sum/2', 'autorouting', 'on');
add_line(subsystem, 'vd_sin/1', 'v_beta_sum/1', 'autorouting', 'on');
add_line(subsystem, 'vq_cos/1', 'v_beta_sum/2', 'autorouting', 'on');

add_line(subsystem, 'v_alpha_sum/1', 'vb_alpha_gain/1', 'autorouting', 'on');
add_line(subsystem, 'v_beta_sum/1', 'vb_beta_gain/1', 'autorouting', 'on');
add_line(subsystem, 'v_alpha_sum/1', 'vc_alpha_gain/1', 'autorouting', 'on');
add_line(subsystem, 'v_beta_sum/1', 'vc_beta_gain/1', 'autorouting', 'on');
add_line(subsystem, 'vb_alpha_gain/1', 'vb_sum/1', 'autorouting', 'on');
add_line(subsystem, 'vb_beta_gain/1', 'vb_sum/2', 'autorouting', 'on');
add_line(subsystem, 'vc_alpha_gain/1', 'vc_sum/1', 'autorouting', 'on');
add_line(subsystem, 'vc_beta_gain/1', 'vc_sum/2', 'autorouting', 'on');

add_line(subsystem, 'v_alpha_sum/1', 'v_max/1', 'autorouting', 'on');
add_line(subsystem, 'vb_sum/1', 'v_max/2', 'autorouting', 'on');
add_line(subsystem, 'vc_sum/1', 'v_max/3', 'autorouting', 'on');
add_line(subsystem, 'v_alpha_sum/1', 'v_min/1', 'autorouting', 'on');
add_line(subsystem, 'vb_sum/1', 'v_min/2', 'autorouting', 'on');
add_line(subsystem, 'vc_sum/1', 'v_min/3', 'autorouting', 'on');
add_line(subsystem, 'v_max/1', 'zero_sum/1', 'autorouting', 'on');
add_line(subsystem, 'v_min/1', 'zero_sum/2', 'autorouting', 'on');
add_line(subsystem, 'zero_sum/1', 'zero_gain/1', 'autorouting', 'on');

add_line(subsystem, 'v_alpha_sum/1', 'va_svpwm_sum/1', 'autorouting', 'on');
add_line(subsystem, 'zero_gain/1', 'va_svpwm_sum/2', 'autorouting', 'on');
add_line(subsystem, 'vb_sum/1', 'vb_svpwm_sum/1', 'autorouting', 'on');
add_line(subsystem, 'zero_gain/1', 'vb_svpwm_sum/2', 'autorouting', 'on');
add_line(subsystem, 'vc_sum/1', 'vc_svpwm_sum/1', 'autorouting', 'on');
add_line(subsystem, 'zero_gain/1', 'vc_svpwm_sum/2', 'autorouting', 'on');

add_line(subsystem, 'va_svpwm_sum/1', 'da_ratio_calc/1', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/4', 'da_ratio_calc/2', 'autorouting', 'on');
add_line(subsystem, 'vb_svpwm_sum/1', 'db_ratio_calc/1', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/4', 'db_ratio_calc/2', 'autorouting', 'on');
add_line(subsystem, 'vc_svpwm_sum/1', 'dc_ratio_calc/1', 'autorouting', 'on');
add_line(subsystem, 'cmd_selector/4', 'dc_ratio_calc/2', 'autorouting', 'on');

add_line(subsystem, 'da_ratio_calc/1', 'da_duty_sum/1', 'autorouting', 'on');
add_line(subsystem, 'db_ratio_calc/1', 'db_duty_sum/1', 'autorouting', 'on');
add_line(subsystem, 'dc_ratio_calc/1', 'dc_duty_sum/1', 'autorouting', 'on');
add_line(subsystem, 'duty_half/1', 'da_duty_sum/2', 'autorouting', 'on');
add_line(subsystem, 'duty_half/1', 'db_duty_sum/2', 'autorouting', 'on');
add_line(subsystem, 'duty_half/1', 'dc_duty_sum/2', 'autorouting', 'on');

name_line(add_line(subsystem, 'da_duty_sum/1', 'phase_duty_bus_creator/1', 'autorouting', 'on'), 'da');
name_line(add_line(subsystem, 'db_duty_sum/1', 'phase_duty_bus_creator/2', 'autorouting', 'on'), 'db');
name_line(add_line(subsystem, 'dc_duty_sum/1', 'phase_duty_bus_creator/3', 'autorouting', 'on'), 'dc');
add_line(subsystem, 'phase_duty_bus_creator/1', 'phase_duty_out/1', 'autorouting', 'on');
end

function add_average_inverter_and_plant(model, cfg)
add_block('simulink/Sources/Constant', [model '/LoadTorque'], ...
    'Position', [50 515 120 540], ...
    'Value', 'inverter.load_torque', ...
    'SampleTime', cfg.plantSampleTime, ...
    'OutDataTypeStr', cfg.torqueTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/LoadTorque_to_double'], ...
    'Position', [160 512 245 542], ...
    'OutDataTypeStr', 'double');

add_block('mcbplantlib/Average-Value Inverter', [model '/Average Inverter'], ...
    'Position', [720 80 900 185]);
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/Vabc_to_double'], ...
    'Position', [930 125 970 165], ...
    'OutDataTypeStr', 'double');
add_block('mcblib/Electrical Systems/Motors/Surface Mount PMSM', ...
    [model '/Surface Mount PMSM'], ...
    'Position', [990 110 1200 270]);
set_param([model '/Surface Mount PMSM'], ...
    'port_config', 'Torque', ...
    'sim_type', 'Discrete', ...
    'Ts', 'simcfg.Ts_plant', ...
    'P', 'motor.pole_pairs', ...
    'Rs', 'motor.Rs', ...
    'Ldq_', 'motor.Ld', ...
    'lambda_pm', 'motor.psi_f', ...
    'mechanical', '[motor.J, motor.B, 0]', ...
    'idq0', '[0 0]', ...
    'theta_init', '0', ...
    'omega_init', '0');

add_block('simulink/Signal Routing/Bus Selector', [model '/phase_duty_selector'], ...
    'Position', [575 75 590 185], ...
    'OutputSignals', 'da,db,dc');
add_block('simulink/Signal Routing/Mux', [model '/phase_duty_mux'], ...
    'Position', [615 95 620 175], ...
    'Inputs', '3');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/PhaseDuty_RateTransition_25us'], ...
    'Position', [650 115 685 155], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', cfg.plantSampleTime);
add_block('simulink/Sources/Constant', [model '/Vdc'], ...
    'Position', [575 215 625 245], ...
    'Value', 'inverter.Vdc', ...
    'SampleTime', cfg.plantSampleTime, ...
    'OutDataTypeStr', cfg.voltageTypeName);
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/Vdc_RateTransition_25us'], ...
    'Position', [650 215 685 245], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', cfg.plantSampleTime);

add_block('simulink/Signal Routing/Bus Selector', [model '/plant_info_selector'], ...
    'Position', [1250 85 1265 125], ...
    'OutputSignals', 'MtrPos');
add_block('simulink/Signal Routing/Demux', [model '/iabc_demux'], ...
    'Position', [1250 160 1255 240], ...
    'Outputs', '3');
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/ia_to_float'], ...
    'Position', [1305 170 1365 195], ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/ib_to_float'], ...
    'Position', [1305 205 1365 230], ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/ic_to_float'], ...
    'Position', [1305 240 1365 265], ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/wm_to_float'], ...
    'Position', [1305 285 1365 310], ...
    'OutDataTypeStr', cfg.speedTypeName);
add_block('simulink/Math Operations/Gain', [model '/theta_m_to_theta_e'], ...
    'Position', [1305 90 1370 120], ...
    'Gain', 'motor.pole_pairs', ...
    'OutDataTypeStr', cfg.angleTypeName);
add_block('simulink/Math Operations/Gain', [model '/theta_m_identity'], ...
    'Position', [1305 130 1370 160], ...
    'Gain', '1', ...
    'OutDataTypeStr', cfg.angleTypeName);

add_block('simulink/Signal Routing/Bus Creator', [model '/feedback_bus_creator'], ...
    'Position', [1440 90 1455 305], ...
    'Inputs', '6', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.plantFeedbackBusName, ...
    'NonVirtualBus', 'on');
add_block('simulink/Sinks/Out1', [model '/feedback_out'], ...
    'Position', [1515 190 1545 210], ...
    'OutDataTypeStr', ['Bus: ' cfg.plantFeedbackBusName]);

add_line(model, 'OpenLoopCommand/1', 'DqToAbcDutyStep/1', 'autorouting', 'on');
add_line(model, 'DqToAbcDutyStep/1', 'phase_duty_selector/1', 'autorouting', 'on');
add_line(model, 'phase_duty_selector/1', 'phase_duty_mux/1', 'autorouting', 'on');
add_line(model, 'phase_duty_selector/2', 'phase_duty_mux/2', 'autorouting', 'on');
add_line(model, 'phase_duty_selector/3', 'phase_duty_mux/3', 'autorouting', 'on');
add_line(model, 'phase_duty_mux/1', 'PhaseDuty_RateTransition_25us/1', 'autorouting', 'on');
add_line(model, 'PhaseDuty_RateTransition_25us/1', 'Average Inverter/1', 'autorouting', 'on');
add_line(model, 'Vdc/1', 'Vdc_RateTransition_25us/1', 'autorouting', 'on');
add_line(model, 'Vdc_RateTransition_25us/1', 'Average Inverter/2', 'autorouting', 'on');
add_line(model, 'LoadTorque/1', 'LoadTorque_to_double/1', 'autorouting', 'on');
add_line(model, 'LoadTorque_to_double/1', 'Surface Mount PMSM/1', 'autorouting', 'on');
add_line(model, 'Average Inverter/1', 'Vabc_to_double/1', 'autorouting', 'on');
add_line(model, 'Vabc_to_double/1', 'Surface Mount PMSM/2', 'autorouting', 'on');

add_line(model, 'Surface Mount PMSM/1', 'plant_info_selector/1', 'autorouting', 'on');
add_line(model, 'plant_info_selector/1', 'theta_m_to_theta_e/1', 'autorouting', 'on');
add_line(model, 'plant_info_selector/1', 'theta_m_identity/1', 'autorouting', 'on');
add_line(model, 'Surface Mount PMSM/2', 'iabc_demux/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/1', 'ia_to_float/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/2', 'ib_to_float/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/3', 'ic_to_float/1', 'autorouting', 'on');
add_line(model, 'Surface Mount PMSM/3', 'wm_to_float/1', 'autorouting', 'on');

name_line(add_line(model, 'ia_to_float/1', 'feedback_bus_creator/1', 'autorouting', 'on'), 'ia');
name_line(add_line(model, 'ib_to_float/1', 'feedback_bus_creator/2', 'autorouting', 'on'), 'ib');
name_line(add_line(model, 'ic_to_float/1', 'feedback_bus_creator/3', 'autorouting', 'on'), 'ic');
name_line(add_line(model, 'wm_to_float/1', 'feedback_bus_creator/4', 'autorouting', 'on'), 'wm');
name_line(add_line(model, 'theta_m_identity/1', 'feedback_bus_creator/5', 'autorouting', 'on'), 'theta_m');
name_line(add_line(model, 'theta_m_to_theta_e/1', 'feedback_bus_creator/6', 'autorouting', 'on'), 'theta_e');
add_line(model, 'feedback_bus_creator/1', 'feedback_out/1', 'autorouting', 'on');
end

function add_log_outputs(model, feedback_src_port)
add_block('simulink/Sinks/To Workspace', [model '/log_feedback_bus'], ...
    'Position', [1515 185 1625 215], ...
    'VariableName', 'log_feedback_bus', ...
    'SaveFormat', 'Timeseries');
add_block('simulink/Sinks/Scope', [model '/Feedback Scope'], ...
    'Position', [1515 235 1570 285], ...
    'NumInputPorts', '1');
add_line(model, feedback_src_port, 'log_feedback_bus/1', 'autorouting', 'on');
add_line(model, feedback_src_port, 'Feedback Scope/1', 'autorouting', 'on');

add_block('simulink/Signal Routing/Bus Selector', [model '/feedback_log_selector'], ...
    'Position', [1515 315 1530 475], ...
    'OutputSignals', 'wm,theta_e,ia,ib,ic');
add_scalar_logger(model, 'log_wm', [1585 310 1665 340], 'feedback_log_selector/1');
add_scalar_logger(model, 'log_theta_e', [1585 350 1665 380], 'feedback_log_selector/2');
add_scalar_logger(model, 'log_ia', [1585 390 1665 420], 'feedback_log_selector/3');
add_scalar_logger(model, 'log_ib', [1585 430 1665 460], 'feedback_log_selector/4');
add_scalar_logger(model, 'log_ic', [1585 470 1665 500], 'feedback_log_selector/5');
add_line(model, feedback_src_port, 'feedback_log_selector/1', 'autorouting', 'on');
end

function add_duty_log_outputs(model)
add_scalar_logger(model, 'log_da', [700 315 780 345], 'phase_duty_selector/1');
add_scalar_logger(model, 'log_db', [700 355 780 385], 'phase_duty_selector/2');
add_scalar_logger(model, 'log_dc', [700 395 780 425], 'phase_duty_selector/3');
end

function add_scalar_logger(model, variable_name, position, src_port)
add_block('simulink/Sinks/To Workspace', [model '/' variable_name], ...
    'Position', position, ...
    'VariableName', variable_name, ...
    'SaveFormat', 'Timeseries');
add_line(model, src_port, [variable_name '/1'], 'autorouting', 'on');
end

function add_clean_subsystem(subsystem, position)
add_block('simulink/Ports & Subsystems/Subsystem', subsystem, ...
    'Position', position);
lines = find_system(subsystem, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(subsystem, 'SearchDepth', 1, 'Type', 'Block');
for i = 2:numel(blocks)
    delete_block(blocks{i});
end
end

function add_typed_constant(model, block_name, position, value, data_type, sample_time)
add_block('simulink/Sources/Constant', [model '/' block_name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', sample_time);
end

function add_product(subsystem, block_name, position, cfg)
add_block('simulink/Math Operations/Product', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '**', ...
    'OutDataTypeStr', cfg.voltageTypeName);
end

function add_sum(subsystem, block_name, position, inputs, cfg)
add_block('simulink/Math Operations/Sum', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', inputs, ...
    'AccumDataTypeStr', cfg.voltageTypeName, ...
    'OutDataTypeStr', cfg.voltageTypeName);
end

function add_duty_sum(subsystem, block_name, position, cfg)
add_block('simulink/Math Operations/Sum', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '++', ...
    'AccumDataTypeStr', cfg.dutyTypeName, ...
    'OutDataTypeStr', cfg.dutyTypeName);
end

function add_minmax(subsystem, block_name, position, operator)
add_block('simulink/Math Operations/MinMax', [subsystem '/' block_name], ...
    'Position', position, ...
    'Inputs', '3', ...
    'Function', operator);
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
