%% Build a reusable Simulink fixed-point PI module with local Q parameters
% The root interface is already quantized. Only the PI gains and integrator
% use local fixed-point types inside the reusable subsystem.

clear; clc;

script_dir = fileparts(mfilename('fullpath'));
model = 'fixed_point_pi_local_q';
model_file = fullfile(script_dir, [model '.slx']);

Ts = 0.00005;
Kp_local = 10;
Ki_local = 100;
Ki_dt_local = Ki_local * Ts;
Umax_local = 1.8;
Umin_local = -1.8;

io_word_length = 16;
io_fraction_length = 14;
gain_word_length = 32;
gain_fraction_length = 20;
integrator_word_length = 32;
integrator_fraction_length = 24;

io_type_str = sprintf('fixdt(1,%d,%d)', io_word_length, io_fraction_length);
integrator_type_str = sprintf('fixdt(1,%d,%d)', ...
    integrator_word_length, integrator_fraction_length);

assignin('base', 'Ts', Ts);
assignin('base', 'Kp_local', Kp_local);
assignin('base', 'Ki_local', Ki_local);
assignin('base', 'Ki_dt_local', Ki_dt_local);
assignin('base', 'Umax_local', Umax_local);
assignin('base', 'Umin_local', Umin_local);
assignin('base', 'T_pi_io', fixdt(1, io_word_length, io_fraction_length));
assignin('base', 'T_pi_gain', fixdt(1, gain_word_length, gain_fraction_length));
assignin('base', 'T_pi_integrator', ...
    fixdt(1, integrator_word_length, integrator_fraction_length));
create_local_q_pi_bus_objects(io_type_str, integrator_type_str);

if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);

set_param(model, ...
    'StopTime', '0.02', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(Ts, '%.17g'), ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'InlineParams', 'on', ...
    'SupportContinuousTime', 'off');

add_block('simulink/Sources/In1', [model '/pi_in'], ...
    'Position', [45 105 75 125], ...
    'OutDataTypeStr', 'Bus: FixedPointPI_LocalQ_Input', ...
    'BusOutputAsStruct', 'on');

add_local_q_pi_subsystem(model, 'FixedPointPI_LocalQ');

add_block('simulink/Sinks/Out1', [model '/pi_out'], ...
    'Position', [390 105 420 125], ...
    'OutDataTypeStr', 'Bus: FixedPointPI_LocalQ_Output');

add_line(model, 'pi_in/1', 'FixedPointPI_LocalQ/1', 'autorouting', 'on');
add_line(model, 'FixedPointPI_LocalQ/1', 'pi_out/1', 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(model);
set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built local-Q PI module model:\n  %s\n', model_file);

function create_local_q_pi_bus_objects(io_type_str, integrator_type_str)
in_elements(1) = Simulink.BusElement;
in_elements(1).Name = 'setpoint';
in_elements(1).DataType = io_type_str;
in_elements(2) = Simulink.BusElement;
in_elements(2).Name = 'measurement';
in_elements(2).DataType = io_type_str;

pi_input_bus = Simulink.Bus;
pi_input_bus.Elements = in_elements;
assignin('base', 'FixedPointPI_LocalQ_Input', pi_input_bus);

out_elements(1) = Simulink.BusElement;
out_elements(1).Name = 'output';
out_elements(1).DataType = io_type_str;
out_elements(2) = Simulink.BusElement;
out_elements(2).Name = 'error';
out_elements(2).DataType = io_type_str;
out_elements(3) = Simulink.BusElement;
out_elements(3).Name = 'integrator';
out_elements(3).DataType = integrator_type_str;
out_elements(4) = Simulink.BusElement;
out_elements(4).Name = 'saturated';
out_elements(4).DataType = 'boolean';

pi_output_bus = Simulink.Bus;
pi_output_bus.Elements = out_elements;
assignin('base', 'FixedPointPI_LocalQ_Output', pi_output_bus);
end

function add_local_q_pi_subsystem(model, block_name)
pi_path = [model '/' block_name];

add_block('simulink/Ports & Subsystems/Subsystem', pi_path, ...
    'Position', [155 75 305 155]);
delete_line(pi_path, 'In1/1', 'Out1/1');
delete_block([pi_path '/In1']);
delete_block([pi_path '/Out1']);
set_param(pi_path, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function');

add_block('simulink/Sources/In1', [pi_path '/pi_in'], ...
    'Position', [35 92 65 112], ...
    'OutDataTypeStr', 'Bus: FixedPointPI_LocalQ_Input', ...
    'BusOutputAsStruct', 'on');
add_block('simulink/Signal Routing/Bus Selector', [pi_path '/input_bus_selector'], ...
    'Position', [95 60 110 175], ...
    'OutputSignals', 'setpoint,measurement');

add_block('simulink/Math Operations/Sum', [pi_path '/error_sum'], ...
    'Position', [140 93 170 127], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_pi_integrator', ...
    'OutDataTypeStr', 'T_pi_io', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Math Operations/Gain', [pi_path '/kp_gain'], ...
    'Position', [235 60 310 94], ...
    'Gain', 'Kp_local', ...
    'ParamDataTypeStr', 'T_pi_gain', ...
    'OutDataTypeStr', 'T_pi_integrator', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Math Operations/Gain', [pi_path '/kidt_gain'], ...
    'Position', [235 138 310 172], ...
    'Gain', 'Ki_dt_local', ...
    'ParamDataTypeStr', 'T_pi_gain', ...
    'OutDataTypeStr', 'T_pi_integrator', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Discrete/Unit Delay', [pi_path '/integrator_z1'], ...
    'Position', [365 215 415 255], ...
    'InitialCondition', '0', ...
    'SampleTime', 'Ts');
add_block('simulink/Math Operations/Sum', [pi_path '/integrator_sum'], ...
    'Position', [365 138 395 172], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_pi_integrator', ...
    'OutDataTypeStr', 'T_pi_integrator', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [pi_path '/integrator_next_to_local_q'], ...
    'Position', [430 138 535 172], ...
    'OutDataTypeStr', 'T_pi_integrator', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Math Operations/Sum', [pi_path '/u_unsat_sum'], ...
    'Position', [585 93 615 127], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_pi_integrator', ...
    'OutDataTypeStr', 'T_pi_integrator', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [pi_path '/u_unsat_to_local_q'], ...
    'Position', [650 93 755 127], ...
    'OutDataTypeStr', 'T_pi_integrator', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Discontinuities/Saturation', [pi_path '/u_saturation'], ...
    'Position', [795 93 865 127], ...
    'UpperLimit', 'Umax_local', ...
    'LowerLimit', 'Umin_local', ...
    'OutDataTypeStr', 'T_pi_io', ...
    'RndMeth', 'Floor');

add_block('simulink/Sources/Constant', [pi_path '/u_max_local_q'], ...
    'Position', [795 170 865 200], ...
    'Value', 'Umax_local', ...
    'OutDataTypeStr', 'T_pi_integrator');
add_block('simulink/Sources/Constant', [pi_path '/u_min_local_q'], ...
    'Position', [795 265 865 295], ...
    'Value', 'Umin_local', ...
    'OutDataTypeStr', 'T_pi_integrator');
add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [pi_path '/over_max'], ...
    'Position', [915 165 960 205], ...
    'Operator', '>');
add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [pi_path '/under_min'], ...
    'Position', [915 260 960 300], ...
    'Operator', '<');
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [pi_path '/sat_or'], ...
    'Position', [1005 211 1045 249], ...
    'Operator', 'OR', ...
    'Inputs', '2');

add_block('simulink/Signal Routing/Switch', [pi_path '/anti_windup_switch'], ...
    'Position', [585 190 635 260], ...
    'Criteria', 'u2 >= Threshold', ...
    'Threshold', '0.5');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [pi_path '/integrator_to_local_q'], ...
    'Position', [690 210 795 240], ...
    'OutDataTypeStr', 'T_pi_integrator', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Signal Routing/Bus Creator', [pi_path '/output_bus_creator'], ...
    'Position', [1090 75 1105 250], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', 'FixedPointPI_LocalQ_Output', ...
    'NonVirtualBus', 'on');
add_block('simulink/Sinks/Out1', [pi_path '/pi_out'], ...
    'Position', [1140 155 1170 175], ...
    'OutDataTypeStr', 'Bus: FixedPointPI_LocalQ_Output');

add_line(pi_path, 'pi_in/1', 'input_bus_selector/1', 'autorouting', 'on');
add_line(pi_path, 'input_bus_selector/1', 'error_sum/1', 'autorouting', 'on');
add_line(pi_path, 'input_bus_selector/2', 'error_sum/2', 'autorouting', 'on');
add_line(pi_path, 'error_sum/1', 'kp_gain/1', 'autorouting', 'on');
add_line(pi_path, 'error_sum/1', 'kidt_gain/1', 'autorouting', 'on');

add_line(pi_path, 'kidt_gain/1', 'integrator_sum/1', 'autorouting', 'on');
add_line(pi_path, 'integrator_z1/1', 'integrator_sum/2', 'autorouting', 'on');
add_line(pi_path, 'integrator_sum/1', 'integrator_next_to_local_q/1', ...
    'autorouting', 'on');
add_line(pi_path, 'kp_gain/1', 'u_unsat_sum/1', 'autorouting', 'on');
add_line(pi_path, 'integrator_next_to_local_q/1', 'u_unsat_sum/2', ...
    'autorouting', 'on');
add_line(pi_path, 'u_unsat_sum/1', 'u_unsat_to_local_q/1', ...
    'autorouting', 'on');
add_line(pi_path, 'u_unsat_to_local_q/1', 'u_saturation/1', ...
    'autorouting', 'on');

add_line(pi_path, 'u_unsat_to_local_q/1', 'over_max/1', 'autorouting', 'on');
add_line(pi_path, 'u_max_local_q/1', 'over_max/2', 'autorouting', 'on');
add_line(pi_path, 'u_unsat_to_local_q/1', 'under_min/1', 'autorouting', 'on');
add_line(pi_path, 'u_min_local_q/1', 'under_min/2', 'autorouting', 'on');
add_line(pi_path, 'over_max/1', 'sat_or/1', 'autorouting', 'on');
add_line(pi_path, 'under_min/1', 'sat_or/2', 'autorouting', 'on');

add_line(pi_path, 'integrator_z1/1', 'anti_windup_switch/1', ...
    'autorouting', 'on');
add_line(pi_path, 'sat_or/1', 'anti_windup_switch/2', 'autorouting', 'on');
add_line(pi_path, 'integrator_next_to_local_q/1', 'anti_windup_switch/3', ...
    'autorouting', 'on');
add_line(pi_path, 'anti_windup_switch/1', 'integrator_to_local_q/1', ...
    'autorouting', 'on');
add_line(pi_path, 'integrator_to_local_q/1', 'integrator_z1/1', ...
    'autorouting', 'on');

h = add_line(pi_path, 'u_saturation/1', 'output_bus_creator/1', ...
    'autorouting', 'on');
set_param(h, 'Name', 'output');
h = add_line(pi_path, 'error_sum/1', 'output_bus_creator/2', ...
    'autorouting', 'on');
set_param(h, 'Name', 'error');
h = add_line(pi_path, 'integrator_to_local_q/1', 'output_bus_creator/3', ...
    'autorouting', 'on');
set_param(h, 'Name', 'integrator');
h = add_line(pi_path, 'sat_or/1', 'output_bus_creator/4', ...
    'autorouting', 'on');
set_param(h, 'Name', 'saturated');
add_line(pi_path, 'output_bus_creator/1', 'pi_out/1', 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(pi_path);
end
