%% Build a fixed-point Q14 PI Simulink model
% Interface signals are Q14. The PI gains and internal accumulator use wider
% fixed-point types so Kp = 10 and Ki = 100 are representable.

clear; clc;

script_dir = fileparts(mfilename('fullpath'));
model = 'fixed_point_pi_q14';
model_file = fullfile(script_dir, [model '.slx']);

Ts = 0.00005;
Kp = 10;
Ki = 100;
kidt = Ki * Ts;
Umax = 1.8;
Umin = -1.8;
ref_step = 1.0;
feedback_step = 0.2;

assignin('base', 'Ts', Ts);
assignin('base', 'Kp', Kp);
assignin('base', 'Ki', Ki);
assignin('base', 'kidt', kidt);
assignin('base', 'Umax', Umax);
assignin('base', 'Umin', Umin);
assignin('base', 'ref_step', ref_step);
assignin('base', 'feedback_step', feedback_step);
assignin('base', 'T_q14', fixdt(1, 16, 14));
assignin('base', 'T_iq24', fixdt(1, 32, 24));
assignin('base', 'T_gain', fixdt(1, 32, 20));
create_pi_bus_objects();

if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);

set_param(model, ...
    'StopTime', '0.02', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(Ts, '%.17g'), ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'InlineParams', 'on', ...
    'SupportContinuousTime', 'off');

add_block('simulink/Sources/Step', [model '/ref_step'], ...
    'Position', [45 70 75 100], ...
    'Time', '0.001', ...
    'Before', '0', ...
    'After', 'ref_step', ...
    'SampleTime', 'Ts');
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/ref_to_q14'], ...
    'Position', [110 68 180 102], ...
    'OutDataTypeStr', 'T_q14', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Sources/Step', [model '/feedback_step'], ...
    'Position', [45 155 75 185], ...
    'Time', '0.006', ...
    'Before', '0', ...
    'After', 'feedback_step', ...
    'SampleTime', 'Ts');
add_block('simulink/Signal Attributes/Data Type Conversion', [model '/feedback_to_q14'], ...
    'Position', [110 153 180 187], ...
    'OutDataTypeStr', 'T_q14', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_fixed_point_pi_subsystem(model, 'FixedPointPI_Q14');

add_block('simulink/Signal Routing/Bus Creator', [model '/pi_input_bus'], ...
    'Position', [210 89 225 151], ...
    'Inputs', '2', ...
    'UseBusObject', 'on', ...
    'BusObject', 'FixedPointPI_Q14_Input', ...
    'NonVirtualBus', 'on');
add_block('simulink/Signal Routing/Bus Selector', [model '/pi_output_bus'], ...
    'Position', [485 80 500 245], ...
    'OutputSignals', 'u_q14,error_q14,integral_iq24,sat_flag');

out_names = {'u_q14', 'error_q14', 'integral_iq24', 'sat_flag'};
for i = 1:numel(out_names)
    y = 70 + (i - 1)*55;
    add_block('simulink/Sinks/Out1', [model '/' out_names{i}], ...
        'Position', [565 y 595 y+20]);
end

ws_names = {'u_log', 'error_log', 'integral_log', 'sat_log'};
for i = 1:numel(ws_names)
    y = 70 + (i - 1)*55;
    add_block('simulink/Sinks/To Workspace', [model '/' ws_names{i}], ...
        'Position', [650 y-5 735 y+25], ...
        'VariableName', ws_names{i}, ...
        'SaveFormat', 'Timeseries');
end

add_line(model, 'ref_step/1', 'ref_to_q14/1', 'autorouting', 'on');
add_line(model, 'feedback_step/1', 'feedback_to_q14/1', 'autorouting', 'on');
h = add_line(model, 'ref_to_q14/1', 'pi_input_bus/1', 'autorouting', 'on');
set_param(h, 'Name', 'ref_q14');
h = add_line(model, 'feedback_to_q14/1', 'pi_input_bus/2', 'autorouting', 'on');
set_param(h, 'Name', 'feedback_q14');
add_line(model, 'pi_input_bus/1', 'FixedPointPI_Q14/1', 'autorouting', 'on');
add_line(model, 'FixedPointPI_Q14/1', 'pi_output_bus/1', 'autorouting', 'on');

for i = 1:numel(out_names)
    add_line(model, sprintf('pi_output_bus/%d', i), sprintf('%s/1', out_names{i}), 'autorouting', 'on');
    add_line(model, sprintf('pi_output_bus/%d', i), sprintf('%s/1', ws_names{i}), 'autorouting', 'on');
end

Simulink.BlockDiagram.arrangeSystem(model);
set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built model:\n  %s\n', model_file);

function create_pi_bus_objects()
in_elements(1) = Simulink.BusElement;
in_elements(1).Name = 'ref_q14';
in_elements(1).DataType = 'fixdt(1,16,14)';
in_elements(2) = Simulink.BusElement;
in_elements(2).Name = 'feedback_q14';
in_elements(2).DataType = 'fixdt(1,16,14)';

pi_input_bus = Simulink.Bus;
pi_input_bus.Elements = in_elements;
assignin('base', 'FixedPointPI_Q14_Input', pi_input_bus);

out_elements(1) = Simulink.BusElement;
out_elements(1).Name = 'u_q14';
out_elements(1).DataType = 'fixdt(1,16,14)';
out_elements(2) = Simulink.BusElement;
out_elements(2).Name = 'error_q14';
out_elements(2).DataType = 'fixdt(1,16,14)';
out_elements(3) = Simulink.BusElement;
out_elements(3).Name = 'integral_iq24';
out_elements(3).DataType = 'fixdt(1,32,24)';
out_elements(4) = Simulink.BusElement;
out_elements(4).Name = 'sat_flag';
out_elements(4).DataType = 'boolean';

pi_output_bus = Simulink.Bus;
pi_output_bus.Elements = out_elements;
assignin('base', 'FixedPointPI_Q14_Output', pi_output_bus);
end

function add_fixed_point_pi_subsystem(model, block_name)
pi_path = [model '/' block_name];

add_block('simulink/Ports & Subsystems/Subsystem', pi_path, ...
    'Position', [245 85 445 195]);
delete_line(pi_path, 'In1/1', 'Out1/1');
delete_block([pi_path '/In1']);
delete_block([pi_path '/Out1']);
set_param(pi_path, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function');

add_block('simulink/Sources/In1', [pi_path '/pi_in'], ...
    'Position', [35 92 65 112], ...
    'OutDataTypeStr', 'Bus: FixedPointPI_Q14_Input');
add_block('simulink/Signal Routing/Bus Selector', [pi_path '/input_bus_selector'], ...
    'Position', [95 60 110 175], ...
    'OutputSignals', 'ref_q14,feedback_q14');

add_block('simulink/Math Operations/Sum', [pi_path '/error_sum'], ...
    'Position', [125 93 155 127], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', 'T_iq24', ...
    'OutDataTypeStr', 'T_q14', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Signal Attributes/Data Type Conversion', [pi_path '/error_to_q14'], ...
    'Position', [190 93 260 127], ...
    'OutDataTypeStr', 'T_q14', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Math Operations/Gain', [pi_path '/kp_gain'], ...
    'Position', [305 60 380 94], ...
    'Gain', 'Kp', ...
    'ParamDataTypeStr', 'T_gain', ...
    'OutDataTypeStr', 'T_iq24', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Math Operations/Gain', [pi_path '/kidt_gain'], ...
    'Position', [305 138 380 172], ...
    'Gain', 'kidt', ...
    'ParamDataTypeStr', 'T_gain', ...
    'OutDataTypeStr', 'T_iq24', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Discrete/Unit Delay', [pi_path '/integral_z1'], ...
    'Position', [430 215 480 255], ...
    'InitialCondition', '0', ...
    'SampleTime', 'Ts');
add_block('simulink/Math Operations/Sum', [pi_path '/integral_sum'], ...
    'Position', [430 138 460 172], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_iq24', ...
    'OutDataTypeStr', 'T_iq24', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Signal Attributes/Data Type Conversion', [pi_path '/i_next_to_iq24'], ...
    'Position', [495 138 575 172], ...
    'OutDataTypeStr', 'T_iq24', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Math Operations/Sum', [pi_path '/u_unsat_sum'], ...
    'Position', [620 93 650 127], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', 'T_iq24', ...
    'OutDataTypeStr', 'T_iq24', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Signal Attributes/Data Type Conversion', [pi_path '/u_unsat_to_iq24'], ...
    'Position', [685 93 775 127], ...
    'OutDataTypeStr', 'T_iq24', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');
add_block('simulink/Discontinuities/Saturation', [pi_path '/u_saturation'], ...
    'Position', [815 93 885 127], ...
    'UpperLimit', 'Umax', ...
    'LowerLimit', 'Umin', ...
    'OutDataTypeStr', 'T_q14', ...
    'RndMeth', 'Floor');

add_block('simulink/Sources/Constant', [pi_path '/u_max_iq24'], ...
    'Position', [815 170 865 200], ...
    'Value', 'Umax', ...
    'OutDataTypeStr', 'T_iq24');
add_block('simulink/Sources/Constant', [pi_path '/u_min_iq24'], ...
    'Position', [815 265 865 295], ...
    'Value', 'Umin', ...
    'OutDataTypeStr', 'T_iq24');
add_block('simulink/Logic and Bit Operations/Relational Operator', [pi_path '/over_max'], ...
    'Position', [920 165 965 205], ...
    'Operator', '>');
add_block('simulink/Logic and Bit Operations/Relational Operator', [pi_path '/under_min'], ...
    'Position', [920 260 965 300], ...
    'Operator', '<');
add_block('simulink/Logic and Bit Operations/Logical Operator', [pi_path '/sat_or'], ...
    'Position', [1005 211 1045 249], ...
    'Operator', 'OR', ...
    'Inputs', '2');

add_block('simulink/Signal Routing/Switch', [pi_path '/anti_windup_switch'], ...
    'Position', [620 190 670 260], ...
    'Criteria', 'u2 >= Threshold', ...
    'Threshold', '0.5');
add_block('simulink/Signal Attributes/Data Type Conversion', [pi_path '/integral_to_iq24'], ...
    'Position', [710 210 790 240], ...
    'OutDataTypeStr', 'T_iq24', ...
    'RndMeth', 'Floor', ...
    'SaturateOnIntegerOverflow', 'on');

add_block('simulink/Signal Routing/Bus Creator', [pi_path '/output_bus_creator'], ...
    'Position', [1075 75 1090 250], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', 'FixedPointPI_Q14_Output', ...
    'NonVirtualBus', 'on');
add_block('simulink/Sinks/Out1', [pi_path '/pi_out'], ...
    'Position', [1130 155 1160 175], ...
    'OutDataTypeStr', 'Bus: FixedPointPI_Q14_Output');

add_line(pi_path, 'pi_in/1', 'input_bus_selector/1', 'autorouting', 'on');
add_line(pi_path, 'input_bus_selector/1', 'error_sum/1', 'autorouting', 'on');
add_line(pi_path, 'input_bus_selector/2', 'error_sum/2', 'autorouting', 'on');
add_line(pi_path, 'error_sum/1', 'error_to_q14/1', 'autorouting', 'on');
add_line(pi_path, 'error_to_q14/1', 'kp_gain/1', 'autorouting', 'on');
add_line(pi_path, 'error_to_q14/1', 'kidt_gain/1', 'autorouting', 'on');

add_line(pi_path, 'kidt_gain/1', 'integral_sum/1', 'autorouting', 'on');
add_line(pi_path, 'integral_z1/1', 'integral_sum/2', 'autorouting', 'on');
add_line(pi_path, 'integral_sum/1', 'i_next_to_iq24/1', 'autorouting', 'on');
add_line(pi_path, 'kp_gain/1', 'u_unsat_sum/1', 'autorouting', 'on');
add_line(pi_path, 'i_next_to_iq24/1', 'u_unsat_sum/2', 'autorouting', 'on');
add_line(pi_path, 'u_unsat_sum/1', 'u_unsat_to_iq24/1', 'autorouting', 'on');
add_line(pi_path, 'u_unsat_to_iq24/1', 'u_saturation/1', 'autorouting', 'on');

add_line(pi_path, 'u_unsat_to_iq24/1', 'over_max/1', 'autorouting', 'on');
add_line(pi_path, 'u_max_iq24/1', 'over_max/2', 'autorouting', 'on');
add_line(pi_path, 'u_unsat_to_iq24/1', 'under_min/1', 'autorouting', 'on');
add_line(pi_path, 'u_min_iq24/1', 'under_min/2', 'autorouting', 'on');
add_line(pi_path, 'over_max/1', 'sat_or/1', 'autorouting', 'on');
add_line(pi_path, 'under_min/1', 'sat_or/2', 'autorouting', 'on');

add_line(pi_path, 'integral_z1/1', 'anti_windup_switch/1', 'autorouting', 'on');
add_line(pi_path, 'sat_or/1', 'anti_windup_switch/2', 'autorouting', 'on');
add_line(pi_path, 'i_next_to_iq24/1', 'anti_windup_switch/3', 'autorouting', 'on');
add_line(pi_path, 'anti_windup_switch/1', 'integral_to_iq24/1', 'autorouting', 'on');
add_line(pi_path, 'integral_to_iq24/1', 'integral_z1/1', 'autorouting', 'on');

h = add_line(pi_path, 'u_saturation/1', 'output_bus_creator/1', 'autorouting', 'on');
set_param(h, 'Name', 'u_q14');
h = add_line(pi_path, 'error_to_q14/1', 'output_bus_creator/2', 'autorouting', 'on');
set_param(h, 'Name', 'error_q14');
h = add_line(pi_path, 'integral_to_iq24/1', 'output_bus_creator/3', 'autorouting', 'on');
set_param(h, 'Name', 'integral_iq24');
h = add_line(pi_path, 'sat_or/1', 'output_bus_creator/4', 'autorouting', 'on');
set_param(h, 'Name', 'sat_flag');
add_line(pi_path, 'output_bus_creator/1', 'pi_out/1', 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(pi_path);
end
