function mdl = build_switching_sampling_study_model()
%BUILD_SWITCHING_SAMPLING_STUDY_MODEL Create a first-stage PWM timing model.

switching_sampling_study_config;
mdl = ss_cfg.model_name;

if bdIsLoaded(mdl)
    close_system(mdl, 0);
end
if exist([mdl '.slx'], 'file')
    delete([mdl '.slx']);
end

new_system(mdl);
open_system(mdl);
set_param(mdl, ...
    'StopTime', 'max(ss_cfg.sim_stop_time, 1/ss_cfg.electrical_freq_hz)', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'ss_cfg.model_fixed_step_s');

% Base parameters
add_block('simulink/Sources/Repeating Sequence', [mdl '/Theta_e_deg'], ...
    'Position', [30 35 140 75], ...
    'rep_seq_t', '[0 1/ss_cfg.electrical_freq_hz]', ...
    'rep_seq_y', '[0 360]');
add_block('simulink/Sources/Constant', [mdl '/ModulationRatio'], ...
    'Position', [30 80 90 100], 'Value', 'ss_cfg.modulation_ratio');
add_block('simulink/Sources/Constant', [mdl '/Vdc'], ...
    'Position', [30 125 90 145], 'Value', 'ss_cfg.Vdc');
add_block('simulink/Sources/Constant', [mdl '/DutySampleLimit'], ...
    'Position', [30 160 110 180], 'Value', 'ss_cfg.duty_sample_limit');

% Symmetric V0/V7 duty generation
fcn_blk = [mdl '/SymmetricDutyGenerator'];
add_block('simulink/User-Defined Functions/MATLAB Function', fcn_blk, ...
    'Position', [140 35 320 145]);
local_set_duty_generator_script(fcn_blk);
add_line(mdl, 'Theta_e_deg/1', 'SymmetricDutyGenerator/1');
add_line(mdl, 'ModulationRatio/1', 'SymmetricDutyGenerator/2');
add_line(mdl, 'Vdc/1', 'SymmetricDutyGenerator/3');
add_line(mdl, 'DutySampleLimit/1', 'SymmetricDutyGenerator/4');

% Center-aligned triangular carrier
add_block('simulink/Sources/Repeating Sequence', [mdl '/TriangleCarrier'], ...
    'Position', [360 50 470 90], ...
    'rep_seq_t', '[0 ss_cfg.T_pwm/2 ss_cfg.T_pwm]', ...
    'rep_seq_y', '[0 1 0]');

add_block('simulink/Sources/Constant', [mdl '/Ts_model_const'], ...
    'Position', [360 95 430 115], ...
    'Value', 'ss_cfg.model_fixed_step_s');

add_block('simulink/Sources/Constant', [mdl '/DeadTime_const'], ...
    'Position', [360 430 430 450], 'Value', 'ss_cfg.dead_time_s');

% Compare carrier to each duty and add dead time to complementary gates
local_add_pwm_leg(mdl, 'A', [530 20], 'SymmetricDutyGenerator/1', 'TriangleCarrier/1', 'DeadTime_const/1', 'Ts_model_const/1');
local_add_pwm_leg(mdl, 'B', [530 125], 'SymmetricDutyGenerator/2', 'TriangleCarrier/1', 'DeadTime_const/1', 'Ts_model_const/1');
local_add_pwm_leg(mdl, 'C', [530 230], 'SymmetricDutyGenerator/3', 'TriangleCarrier/1', 'DeadTime_const/1', 'Ts_model_const/1');

% Scope: carrier and duty levels
add_block('simulink/Signal Routing/Mux', [mdl '/MuxCarrierDuty'], ...
    'Position', [360 165 365 255], 'Inputs', '4');
add_line(mdl, 'TriangleCarrier/1', 'MuxCarrierDuty/1');
add_line(mdl, 'SymmetricDutyGenerator/1', 'MuxCarrierDuty/2');
add_line(mdl, 'SymmetricDutyGenerator/2', 'MuxCarrierDuty/3');
add_line(mdl, 'SymmetricDutyGenerator/3', 'MuxCarrierDuty/4');
add_block('simulink/Sinks/Scope', [mdl '/CarrierAndDutyScope'], ...
    'Position', [410 165 500 255], 'NumInputPorts', '1');
add_line(mdl, 'MuxCarrierDuty/1', 'CarrierAndDutyScope/1');

% Scope: slow evolution of angle and duty to reveal saddle-wave shape
add_block('simulink/Signal Routing/Mux', [mdl '/MuxThetaDuty'], ...
    'Position', [360 285 365 375], 'Inputs', '4');
add_line(mdl, 'Theta_e_deg/1', 'MuxThetaDuty/1');
add_line(mdl, 'SymmetricDutyGenerator/1', 'MuxThetaDuty/2');
add_line(mdl, 'SymmetricDutyGenerator/2', 'MuxThetaDuty/3');
add_line(mdl, 'SymmetricDutyGenerator/3', 'MuxThetaDuty/4');
add_block('simulink/Sinks/Scope', [mdl '/ThetaAndDutyScope'], ...
    'Position', [410 285 500 375], 'NumInputPorts', '1');
add_line(mdl, 'MuxThetaDuty/1', 'ThetaAndDutyScope/1');

% Scope: low-side gate windows
local_add_from_block(mdl, 'S_A_low', [770 85 835 105], 'From_S_A_low_scope');
local_add_from_block(mdl, 'S_B_low', [770 125 835 145], 'From_S_B_low_scope');
local_add_from_block(mdl, 'S_C_low', [770 165 835 185], 'From_S_C_low_scope');
add_block('simulink/Signal Routing/Mux', [mdl '/MuxLowerGates'], ...
    'Position', [835 80 840 200], 'Inputs', '3');
add_line(mdl, 'From_S_A_low_scope/1', 'MuxLowerGates/1');
add_line(mdl, 'From_S_B_low_scope/1', 'MuxLowerGates/2');
add_line(mdl, 'From_S_C_low_scope/1', 'MuxLowerGates/3');
add_block('simulink/Sinks/Scope', [mdl '/LowerGateScope'], ...
    'Position', [885 95 975 185], 'NumInputPorts', '1');
add_line(mdl, 'MuxLowerGates/1', 'LowerGateScope/1');

% SPS power stage: six gate commands, bridge, PMSM, and phase currents
local_add_from_block(mdl, 'S_A_high', [820 -220 885 -200], 'From_S_A_high_sps');
local_add_from_block(mdl, 'S_A_low', [820 -190 885 -170], 'From_S_A_low_sps');
local_add_from_block(mdl, 'S_B_high', [820 -160 885 -140], 'From_S_B_high_sps');
local_add_from_block(mdl, 'S_B_low', [820 -130 885 -110], 'From_S_B_low_sps');
local_add_from_block(mdl, 'S_C_high', [820 -100 885 -80], 'From_S_C_high_sps');
local_add_from_block(mdl, 'S_C_low', [820 -70 885 -50], 'From_S_C_low_sps');
add_block('simulink/Signal Routing/Mux', [mdl '/GateCommandMux'], ...
    'Position', [940 -215 945 -95], 'Inputs', '6');
add_line(mdl, 'From_S_A_high_sps/1', 'GateCommandMux/1');
add_line(mdl, 'From_S_A_low_sps/1', 'GateCommandMux/2');
add_line(mdl, 'From_S_B_high_sps/1', 'GateCommandMux/3');
add_line(mdl, 'From_S_B_low_sps/1', 'GateCommandMux/4');
add_line(mdl, 'From_S_C_high_sps/1', 'GateCommandMux/5');
add_line(mdl, 'From_S_C_low_sps/1', 'GateCommandMux/6');

add_block('simulink/Sources/Constant', [mdl '/PMSMSpeedRef'], ...
    'Position', [1260 -115 1290 -85], ...
    'Value', 'ss_cfg.pmsm_speed_ref_rad_s');
add_block('spsUniversalBridgeLib/Universal Bridge', [mdl '/UniversalBridge'], ...
    'Position', [1125 -16 1215 121], ...
    'BlockMirror', 'on', ...
    'NameLocation', 'top', ...
    'Device', 'MOSFET / Diodes', ...
    'SnubberResistance', '1e5', ...
    'SnubberCapacitance', 'inf', ...
    'Ron', '1e-3', ...
    'Lon', '0', ...
    'Measurements', 'None');
add_block('spsPermanentMagnetSynchronousMachineLib/Permanent Magnet Synchronous Machine', [mdl '/PMSM'], ...
    'Position', [1320 0 1410 80], ...
    'MechanicalLoad', 'Speed w', ...
    'MeasurementBus', 'off');
add_block('simulink/Signal Routing/Bus Selector', [mdl '/MachineCurrentSelector'], ...
    'Position', [1495 21 1500 59], ...
    'OutputSignals', 'Stator current is_a (A),Stator current is_b (A),Stator current is_c (A)');
add_block('simulink/Sinks/Scope', [mdl '/PhaseCurrentScope'], ...
    'Position', [1625 40 1715 130], ...
    'NumInputPorts', '3');
add_block('spsDCVoltageSourceLib/DC Voltage Source', [mdl '/DCSource'], ...
    'Position', [1085 20 1105 55], ...
    'BlockRotation', '270', ...
    'Amplitude', 'ss_cfg.Vdc', ...
    'Measurements', 'None');
add_block('sps_lib/powergui', [mdl '/powergui'], ...
    'Position', [1325 220 1406 259], ...
    'SimulationMode', 'Discrete', ...
    'SampleTime', 'ss_cfg.powergui_sample_time_s');

gate_mux_ph = get_param([mdl '/GateCommandMux'], 'PortHandles');
bridge_ph = get_param([mdl '/UniversalBridge'], 'PortHandles');
machine_ph = get_param([mdl '/PMSM'], 'PortHandles');
dc_ph = get_param([mdl '/DCSource'], 'PortHandles');
speed_ph = get_param([mdl '/PMSMSpeedRef'], 'PortHandles');
selector_ph = get_param([mdl '/MachineCurrentSelector'], 'PortHandles');
current_scope_ph = get_param([mdl '/PhaseCurrentScope'], 'PortHandles');

add_line(mdl, gate_mux_ph.Outport(1), bridge_ph.Inport(1), 'autorouting', 'on');
add_line(mdl, speed_ph.Outport(1), machine_ph.Inport(1), 'autorouting', 'on');
add_line(mdl, machine_ph.Outport(1), selector_ph.Inport(1), 'autorouting', 'on');
add_line(mdl, selector_ph.Outport(1), current_scope_ph.Inport(1), 'autorouting', 'on');
add_line(mdl, selector_ph.Outport(2), current_scope_ph.Inport(2), 'autorouting', 'on');
add_line(mdl, selector_ph.Outport(3), current_scope_ph.Inport(3), 'autorouting', 'on');
add_line(mdl, bridge_ph.LConn(1), machine_ph.LConn(1), 'autorouting', 'on');
add_line(mdl, bridge_ph.LConn(2), machine_ph.LConn(2), 'autorouting', 'on');
add_line(mdl, bridge_ph.LConn(3), machine_ph.LConn(3), 'autorouting', 'on');
add_line(mdl, dc_ph.RConn(1), bridge_ph.RConn(1), 'autorouting', 'on');
add_line(mdl, dc_ph.LConn(1), bridge_ph.RConn(2), 'autorouting', 'on');

% Window metrics: ideal low-side, after dead time, after settling time
add_block('simulink/Sources/Constant', [mdl '/T_pwm_const'], ...
    'Position', [360 395 430 415], 'Value', 'ss_cfg.T_pwm');
add_block('simulink/Sources/Constant', [mdl '/Settling_const'], ...
    'Position', [360 465 430 485], 'Value', 'ss_cfg.adc_settle_time_s');

window_blk = [mdl '/WindowMetrics'];
add_block('simulink/User-Defined Functions/MATLAB Function', window_blk, ...
    'Position', [470 390 700 500]);
local_set_window_metrics_script(window_blk);
add_line(mdl, 'SymmetricDutyGenerator/1', 'WindowMetrics/1');
add_line(mdl, 'SymmetricDutyGenerator/2', 'WindowMetrics/2');
add_line(mdl, 'SymmetricDutyGenerator/3', 'WindowMetrics/3');
add_line(mdl, 'T_pwm_const/1', 'WindowMetrics/4');
add_line(mdl, 'DeadTime_const/1', 'WindowMetrics/5');
add_line(mdl, 'Settling_const/1', 'WindowMetrics/6');

add_block('simulink/Sinks/Scope', [mdl '/WindowMetricsScope'], ...
    'Position', [760 400 855 490], 'NumInputPorts', '3');
add_line(mdl, 'WindowMetrics/1', 'WindowMetricsScope/1');
add_line(mdl, 'WindowMetrics/2', 'WindowMetricsScope/2');
add_line(mdl, 'WindowMetrics/3', 'WindowMetricsScope/3');

% To workspace logging for follow-up sampling-window logic
local_add_to_workspace(mdl, 'duty_a', [345 285 435 305], 'SymmetricDutyGenerator/1');
local_add_to_workspace(mdl, 'duty_b', [345 315 435 335], 'SymmetricDutyGenerator/2');
local_add_to_workspace(mdl, 'duty_c', [345 345 435 365], 'SymmetricDutyGenerator/3');
local_add_to_workspace(mdl, 'theta_e_deg', [180 285 270 305], 'Theta_e_deg/1');
local_add_to_workspace(mdl, 'carrier', [485 285 575 305], 'TriangleCarrier/1');
local_add_from_block(mdl, 'S_A_low', [770 240 835 260], 'From_S_A_low_log');
local_add_from_block(mdl, 'S_B_low', [770 270 835 290], 'From_S_B_low_log');
local_add_from_block(mdl, 'S_C_low', [770 300 835 320], 'From_S_C_low_log');
local_add_to_workspace(mdl, 's_a_low', [835 240 925 260], 'From_S_A_low_log/1');
local_add_to_workspace(mdl, 's_b_low', [835 270 925 290], 'From_S_B_low_log/1');
local_add_to_workspace(mdl, 's_c_low', [835 300 925 320], 'From_S_C_low_log/1');
local_add_to_workspace(mdl, 'i_a', [1545 10 1635 30], 'MachineCurrentSelector/1');
local_add_to_workspace(mdl, 'i_b', [1545 45 1635 65], 'MachineCurrentSelector/2');
local_add_to_workspace(mdl, 'i_c', [1545 80 1635 100], 'MachineCurrentSelector/3');
local_add_to_workspace(mdl, 'low_window_ideal', [880 525 990 545], 'WindowMetrics/1');
local_add_to_workspace(mdl, 'low_window_deadtime', [880 555 990 575], 'WindowMetrics/2');
local_add_to_workspace(mdl, 'low_window_valid', [880 585 990 605], 'WindowMetrics/3');

annotation_text = sprintf([ ...
    'First-stage switching study model\n' ...
    'Assumptions:\n' ...
    '1. Base duty from symmetric V0/V7 allocation\n' ...
    '2. MCU-style common duty shift on sampled phases\n' ...
    '3. Center-aligned triangular carrier\n' ...
    '4. Electrical angle is periodic sawtooth\n' ...
    '5. Window metrics computed analytically\n\n' ...
    'Current config:\n' ...
    'f_elec = %.1f Hz\n' ...
    'T_elec = %.2f ms\n' ...
    'modulation = %.2f\n' ...
    'f_pwm = %.1f kHz\n' ...
    'duty sample limit = %.2f\n' ...
    'model step = %.3f ns\n' ...
    'SPS stage = bridge + PMSM + powergui\n' ...
    'StopTime = max(sim_stop_time, T_elec)\n' ...
    'dead time inserted in gate logic\n' ...
    'dead time = %.2f us\n' ...
    'settle = %.2f us'], ...
    ss_cfg.electrical_freq_hz, 1e3 / ss_cfg.electrical_freq_hz, ss_cfg.modulation_ratio, ss_cfg.f_pwm / 1e3, ...
    ss_cfg.duty_sample_limit, ...
    ss_cfg.model_fixed_step_s * 1e9, ...
    ss_cfg.dead_time_s * 1e6, ss_cfg.adc_settle_time_s * 1e6);
top_note = Simulink.Annotation(mdl, annotation_text);
top_note.Position = [25 185 285 300];

save_system(mdl);

end

function local_set_duty_generator_script(blockPath)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = sprintf([ ...
    'function [da, db, dc] = fcn(theta_e_deg, modulation_ratio, Vdc, duty_sample_limit)\n' ...
    '%% Symmetric V0/V7 base duty plus MCU-style common duty shift\n' ...
    'theta_e = theta_e_deg * pi / 180;\n' ...
    'v_mag = modulation_ratio * (Vdc / sqrt(3));\n' ...
    'v_alpha = -v_mag * sin(theta_e);\n' ...
    'v_beta =  v_mag * cos(theta_e);\n' ...
    'va = v_alpha;\n' ...
    'vb = -0.5 * v_alpha + sqrt(3) / 2 * v_beta;\n' ...
    'vc = -0.5 * v_alpha - sqrt(3) / 2 * v_beta;\n' ...
    'duty_raw = [va; vb; vc] / Vdc + 0.5;\n' ...
    'shift_min = -min(duty_raw);\n' ...
    'shift_max = 1.0 - max(duty_raw);\n' ...
    'shift = 0.5 * (shift_min + shift_max);\n' ...
    'duty = min(max(duty_raw + shift, 0.0), 1.0);\n' ...
    'if (va >= vb) && (vb >= vc)\n' ...
    '    sector = 1;\n' ...
    'elseif (vb >= va) && (va >= vc)\n' ...
    '    sector = 2;\n' ...
    'elseif (vb >= vc) && (vc >= va)\n' ...
    '    sector = 3;\n' ...
    'elseif (vc >= vb) && (vb >= va)\n' ...
    '    sector = 4;\n' ...
    'elseif (vc >= va) && (va >= vb)\n' ...
    '    sector = 5;\n' ...
    'else\n' ...
    '    sector = 6;\n' ...
    'end\n' ...
    'duty_a = duty(1);\n' ...
    'duty_b = duty(2);\n' ...
    'duty_c = duty(3);\n' ...
    'switch sector\n' ...
    '    case {1, 6}\n' ...
    '        max_sampled = max(duty_b, duty_c);\n' ...
    '    case {2, 3}\n' ...
    '        max_sampled = max(duty_a, duty_c);\n' ...
    '    case {4, 5}\n' ...
    '        max_sampled = max(duty_a, duty_b);\n' ...
    '    otherwise\n' ...
    '        max_sampled = 0.0;\n' ...
    'end\n' ...
    'if max_sampled > duty_sample_limit\n' ...
    '    common_shift = -(max_sampled - duty_sample_limit);\n' ...
    '    min_duty = min([duty_a; duty_b; duty_c]);\n' ...
    '    if (min_duty + common_shift) < 0.0\n' ...
    '        common_shift = -min_duty;\n' ...
    '    end\n' ...
    '    duty_a = duty_a + common_shift;\n' ...
    '    duty_b = duty_b + common_shift;\n' ...
    '    duty_c = duty_c + common_shift;\n' ...
    'end\n' ...
    'duty = min(max([duty_a; duty_b; duty_c], 0.0), 1.0);\n' ...
    'da = duty(1);\n' ...
    'db = duty(2);\n' ...
    'dc = duty(3);\n' ...
    'end\n']);
end

function local_set_window_metrics_script(blockPath)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = sprintf([ ...
    'function [w_ideal, w_dead, w_valid] = fcn(da, db, dc, T_pwm, dead_time, settle_time)\n' ...
    '%% Low-side window metrics for center-aligned PWM\n' ...
    'd = [da; db; dc];\n' ...
    'w_ideal = zeros(3,1);\n' ...
    'w_dead = zeros(3,1);\n' ...
    'w_valid = zeros(3,1);\n' ...
    'for i = 1:3\n' ...
    '    w_ideal(i) = max((1.0 - d(i)) * T_pwm, 0.0);\n' ...
    '    w_dead(i) = max(w_ideal(i) - 2.0 * dead_time, 0.0);\n' ...
    '    w_valid(i) = max(w_dead(i) - settle_time, 0.0);\n' ...
    'end\n' ...
    'end\n']);
end

function local_set_deadtime_script(blockPath)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = sprintf([ ...
    'function [s_high, s_low] = fcn(pwm_cmd, dead_time, Ts_model)\n' ...
    '%% Complementary gate generation with dead time\n' ...
    'persistent active_state pending_state dead_count initialized\n' ...
    'if isempty(initialized)\n' ...
    '    active_state = double(pwm_cmd >= 0.5);\n' ...
    '    pending_state = active_state;\n' ...
    '    dead_count = 0;\n' ...
    '    initialized = true;\n' ...
    'end\n' ...
    'requested_state = double(pwm_cmd >= 0.5);\n' ...
    'samples_dt = max(1, ceil(dead_time / Ts_model));\n' ...
    'if dead_time <= 0.0\n' ...
    '    active_state = requested_state;\n' ...
    '    dead_count = 0;\n' ...
    'elseif dead_count > 0\n' ...
    '    pending_state = requested_state;\n' ...
    '    dead_count = dead_count - 1;\n' ...
    '    if dead_count == 0\n' ...
    '        active_state = pending_state;\n' ...
    '    else\n' ...
    '        active_state = -1;\n' ...
    '    end\n' ...
    'elseif requested_state ~= active_state\n' ...
    '    pending_state = requested_state;\n' ...
    '    active_state = -1;\n' ...
    '    dead_count = samples_dt;\n' ...
    'end\n' ...
    'if active_state == 1\n' ...
    '    s_high = true;\n' ...
    '    s_low = false;\n' ...
    'elseif active_state == 0\n' ...
    '    s_high = false;\n' ...
    '    s_low = true;\n' ...
    'else\n' ...
    '    s_high = false;\n' ...
    '    s_low = false;\n' ...
    'end\n' ...
    'end\n']);
end

function local_set_pwm_compare_script(blockPath)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = sprintf([ ...
    'function pwm_cmd = fcn(carrier, duty)\n' ...
    '%% Boundary-safe PWM compare for duty in [0, 1]\n' ...
    'if duty <= 0.0\n' ...
    '    pwm_cmd = false;\n' ...
    'elseif duty >= 1.0\n' ...
    '    pwm_cmd = true;\n' ...
    'else\n' ...
    '    pwm_cmd = carrier < duty;\n' ...
    'end\n' ...
    'end\n']);
end

function local_add_pwm_leg(mdl, phaseName, origin, dutySrc, carrierSrc, deadTimeSrc, tsSrc)
compareBlk = [mdl '/Compare_' phaseName];
add_block('simulink/User-Defined Functions/MATLAB Function', compareBlk, ...
    'Position', [origin(1) origin(2)-5 origin(1)+105 origin(2)+35]);
local_set_pwm_compare_script(compareBlk);
add_line(mdl, carrierSrc, ['Compare_' phaseName '/1']);
add_line(mdl, dutySrc, ['Compare_' phaseName '/2']);

deadBlk = [mdl '/DeadTime_' phaseName];
add_block('simulink/User-Defined Functions/MATLAB Function', deadBlk, ...
    'Position', [origin(1)+80 origin(2)-5 origin(1)+205 origin(2)+55]);
local_set_deadtime_script(deadBlk);
add_line(mdl, ['Compare_' phaseName '/1'], ['DeadTime_' phaseName '/1']);
add_line(mdl, deadTimeSrc, ['DeadTime_' phaseName '/2']);
add_line(mdl, tsSrc, ['DeadTime_' phaseName '/3']);

add_block('simulink/Signal Routing/Goto', [mdl '/S_' phaseName '_high'], ...
    'Position', [origin(1)+240 origin(2) origin(1)+315 origin(2)+20], ...
    'GotoTag', ['S_' phaseName '_high']);
add_line(mdl, ['DeadTime_' phaseName '/1'], ['S_' phaseName '_high/1']);

add_block('simulink/Signal Routing/Goto', [mdl '/S_' phaseName '_low'], ...
    'Position', [origin(1)+240 origin(2)+35 origin(1)+315 origin(2)+55], ...
    'GotoTag', ['S_' phaseName '_low']);
add_line(mdl, ['DeadTime_' phaseName '/2'], ['S_' phaseName '_low/1']);

end

function local_add_from_block(mdl, gotoTag, position, blockName)
add_block('simulink/Signal Routing/From', [mdl '/' blockName], ...
    'Position', position, ...
    'GotoTag', gotoTag);
end

function local_add_to_workspace(mdl, varName, position, src)
blk = [mdl '/ToWs_' varName];
add_block('simulink/Sinks/To Workspace', blk, ...
    'Position', position, ...
    'VariableName', varName, ...
    'SaveFormat', 'Structure With Time');
add_line(mdl, src, ['ToWs_' varName '/1']);
end