%% Build a controller-only Simulink model with struct/bus I/O
% This model is intended for maintainable embedded code interfaces:
%   ctrl_in  -> struct/bus input
%   ctrl_out -> struct/bus output

clear; clc;

script_dir = fileparts(mfilename('fullpath'));
root_dir = fileparts(script_dir);
matlab_dir = fullfile(root_dir, 'matlab');
addpath(matlab_dir);

cfg = config_default();
init_controller_fixed_point_types(cfg);
init_controller_bus_types();

model = 'single_joint_controller_struct';
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);

set_param(model, ...
    'StopTime', '1.0', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(cfg.sim.Ts), ...
    'SystemTargetFile', 'grt.tlc', ...
    'ProdHWDeviceType', 'Intel->x86-64 (Linux 64)', ...
    'TargetHWDeviceType', 'Intel->x86-64 (Linux 64)', ...
    'StrictBusMsg', 'ErrorLevel1', ...
    'BusObjectLabelMismatch', 'error', ...
    'GenerateReport', 'on');

add_block('simulink/Sources/In1', [model '/ctrl_in'], ...
    'Position', [55 120 85 140], ...
    'OutDataTypeStr', 'Bus: ControllerInputBus');

add_controller_subsystem(model, cfg);

add_block('simulink/Sinks/Out1', [model '/ctrl_out'], ...
    'Position', [485 120 515 140], ...
    'OutDataTypeStr', 'Bus: ControllerOutputBus');

add_line(model, 'ctrl_in/1', 'ControllerStruct/1', 'autorouting', 'on');
add_line(model, 'ControllerStruct/1', 'ctrl_out/1', 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(model);
set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built struct I/O controller model:\n  %s\n', model_file);

function add_controller_subsystem(model, cfg)
    subsystem = [model '/ControllerStruct'];
    add_block('built-in/Subsystem', subsystem, 'Position', [185 75 365 185]);
    configure_reusable_function(subsystem, 'usr_pid');

    add_block('simulink/Sources/In1', [subsystem '/ctrl_in'], ...
        'Position', [30 140 60 160], ...
        'OutDataTypeStr', 'Bus: ControllerInputBus');
    add_block('simulink/Signal Routing/Bus Selector', [subsystem '/select_inputs'], ...
        'Position', [105 45 115 255], ...
        'OutputSignals', 'q_ref,q,qdot,qddot,tau_prev,mode');

    add_block('simulink/User-Defined Functions/MATLAB Function', [subsystem '/Core'], ...
        'Position', [185 65 335 235]);
    set_matlab_function_code([subsystem '/Core'], controller_core_code(cfg));

    add_block('simulink/Signal Routing/Bus Creator', [subsystem '/create_output'], ...
        'Position', [390 105 400 185], ...
        'Inputs', '2', ...
        'OutDataTypeStr', 'Bus: ControllerOutputBus');
    add_block('simulink/Sinks/Out1', [subsystem '/ctrl_out'], ...
        'Position', [455 140 485 160], ...
        'OutDataTypeStr', 'Bus: ControllerOutputBus');

    add_line(subsystem, 'ctrl_in/1', 'select_inputs/1', 'autorouting', 'on');
    for i = 1:6
        add_line(subsystem, sprintf('select_inputs/%d', i), sprintf('Core/%d', i), ...
            'autorouting', 'on');
    end
    add_line(subsystem, 'Core/1', 'create_output/1', 'autorouting', 'on');
    add_line(subsystem, 'Core/2', 'create_output/2', 'autorouting', 'on');
    add_line(subsystem, 'create_output/1', 'ctrl_out/1', 'autorouting', 'on');

    Simulink.BlockDiagram.arrangeSystem(subsystem);
end

function code = controller_core_code(cfg)
    code = sprintf([ ...
        'function [tau_cmd, tau_load_hat] = fcn(q_ref, q, qdot, qddot, tau_prev, mode)\n' ...
        '%%#codegen\n' ...
        'persistent integral_e dob_hat\n' ...
        'if isempty(integral_e)\n' ...
        '    integral_e = fi(0, 1, 16, 13);\n' ...
        '    dob_hat = fi(0, 1, 16, 13);\n' ...
        'end\n' ...
        'q_ref_f = fi(q_ref, 1, 16, 12);\n' ...
        'q_f = fi(q, 1, 16, 12);\n' ...
        'qdot_f = fi(qdot, 1, 16, 8);\n' ...
        'qddot_f = fi(qddot, 1, 16, 4);\n' ...
        'tau_prev_f = fi(tau_prev, 1, 16, 12);\n' ...
        'mode_f = mode;\n' ...
        'Ts = fi(%.17g, 1, 16, 15);\n' ...
        'tau_limit = fi(%.17g, 1, 16, 13);\n' ...
        'integral_limit = fi(%.17g, 1, 16, 13);\n' ...
        'tau_hat_limit = fi(%.17g, 1, 16, 13);\n' ...
        'Kp_pid = fi(%.17g, 1, 16, 10);\n' ...
        'Ki_pid = fi(%.17g, 1, 16, 10);\n' ...
        'Kd_pid = fi(%.17g, 1, 16, 14);\n' ...
        'Kp_dob = fi(%.17g, 1, 16, 10);\n' ...
        'Kd_dob = fi(%.17g, 1, 16, 14);\n' ...
        'Jn_dob = fi(%.17g, 1, 16, 15);\n' ...
        'bn_dob = fi(%.17g, 1, 16, 15);\n' ...
        'alpha_dob = fi(%.17g, 1, 16, 14);\n' ...
        'K_imp = fi(%.17g, 1, 16, 10);\n' ...
        'D_imp = fi(%.17g, 1, 16, 14);\n' ...
        'e = fi(q_ref_f - q_f, 1, 16, 12);\n' ...
        'tau_cmd = fi(0, 1, 16, 13);\n' ...
        'tau_load_hat = fi(0, 1, 16, 13);\n' ...
        'if mode_f < uint8(2)\n' ...
        '    integral_e = fi(integral_e + Ts*e, 1, 16, 13);\n' ...
        '    if integral_e > integral_limit\n' ...
        '        integral_e = integral_limit;\n' ...
        '    elseif integral_e < -integral_limit\n' ...
        '        integral_e = -integral_limit;\n' ...
        '    end\n' ...
        '    tau_cmd = fi(Kp_pid*e + Ki_pid*integral_e - Kd_pid*qdot_f, 1, 16, 13);\n' ...
        'elseif mode_f < uint8(3)\n' ...
        '    raw_load = fi(tau_prev_f - Jn_dob*qddot_f - bn_dob*qdot_f, 1, 16, 13);\n' ...
        '    dob_hat = fi(dob_hat + alpha_dob*(raw_load - dob_hat), 1, 16, 13);\n' ...
        '    if dob_hat > tau_hat_limit\n' ...
        '        dob_hat = tau_hat_limit;\n' ...
        '    elseif dob_hat < -tau_hat_limit\n' ...
        '        dob_hat = -tau_hat_limit;\n' ...
        '    end\n' ...
        '    tau_load_hat = dob_hat;\n' ...
        '    tau_cmd = fi(Kp_dob*e - Kd_dob*qdot_f + tau_load_hat, 1, 16, 13);\n' ...
        'else\n' ...
        '    tau_cmd = fi(K_imp*e - D_imp*qdot_f, 1, 16, 13);\n' ...
        'end\n' ...
        'if tau_cmd > tau_limit\n' ...
        '    tau_cmd = tau_limit;\n' ...
        'elseif tau_cmd < -tau_limit\n' ...
        '    tau_cmd = -tau_limit;\n' ...
        'end\n' ...
        'end\n'], ...
        cfg.sim.Ts, cfg.sim.tau_limit, cfg.pid.integral_limit, cfg.dob_pd.tau_hat_limit, ...
        cfg.pid.Kp, cfg.pid.Ki, cfg.pid.Kd, cfg.dob_pd.Kp, cfg.dob_pd.Kd, ...
        cfg.dob_pd.Jn, cfg.dob_pd.bn, 1 - exp(-2*pi*cfg.dob_pd.observer_bw_hz*cfg.sim.Ts), ...
        cfg.impedance.K, cfg.impedance.D);
end

function set_matlab_function_code(block_path, code)
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block_path);
    if isempty(chart)
        error('Could not find MATLAB Function chart: %s', block_path);
    end
    chart.Script = code;
end

function configure_reusable_function(block_path, function_name)
    set_param(block_path, ...
        'RTWSystemCode', 'Reusable function', ...
        'RTWFcnNameOpts', 'User specified', ...
        'RTWFcnName', function_name, ...
        'RTWFileNameOpts', 'User specified', ...
        'RTWFileName', function_name);
end
