%% Build a Simulink model for single-joint dynamics control
% The generated model is intended for visual simulation and C code generation.

clear; clc;

script_dir = fileparts(mfilename('fullpath'));
root_dir = fileparts(script_dir);
matlab_dir = fullfile(root_dir, 'matlab');
addpath(matlab_dir);

cfg = config_default();
fxp = init_controller_fixed_point_types(cfg);
init_controller_bus_types();

model = 'single_joint_dynamics_control';
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);

set_param(model, ...
    'StopTime', num2str(cfg.sim.T_end), ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(cfg.sim.Ts), ...
    'SystemTargetFile', 'grt.tlc', ...
    'ProdHWDeviceType', 'Intel->x86-64 (Linux 64)', ...
    'TargetHWDeviceType', 'Intel->x86-64 (Linux 64)', ...
    'StrictBusMsg', 'ErrorLevel1', ...
    'BusObjectLabelMismatch', 'error', ...
    'GenerateReport', 'on', ...
    'SaveOutput', 'on', ...
    'SignalLogging', 'on');

%% Top-level blocks
add_block('simulink/Sources/Step', [model '/q_ref_step'], ...
    'Position', [40 60 90 90], ...
    'Time', num2str(cfg.ref.step_time), ...
    'Before', num2str(cfg.ref.q_initial), ...
    'After', num2str(cfg.ref.q_final), ...
    'SampleTime', num2str(cfg.sim.Ts));

add_block('simulink/Sources/Step', [model '/tau_load_step'], ...
    'Position', [40 250 90 280], ...
    'Time', num2str(cfg.load.step_time), ...
    'Before', '0', ...
    'After', num2str(cfg.load.tau_value), ...
    'SampleTime', num2str(cfg.sim.Ts));

add_block('simulink/Sources/Constant', [model '/controller_mode'], ...
    'Position', [40 135 90 165], ...
    'Value', 'uint8(2)', ...
    'OutDataTypeStr', 'uint8');

add_controller_subsystem(model, cfg);

add_fixed_conversion(model, 'q_ref_to_fixed', [180 62 205 88], 'T_angle');
add_fixed_conversion(model, 'q_to_fixed', [180 92 205 118], 'T_angle');
add_fixed_conversion(model, 'qdot_to_fixed', [180 122 205 148], 'T_speed');
add_fixed_conversion(model, 'qddot_to_fixed', [180 152 205 178], 'T_accel');
add_fixed_conversion(model, 'tau_prev_to_fixed', [180 182 205 208], 'T_torque_wide');

add_block('simulink/Signal Attributes/Signal Conversion', [model '/mode_signal_conversion'], ...
    'Position', [180 212 205 238], ...
    'OverrideOpt', 'on');

add_block('simulink/Signal Routing/Bus Creator', [model '/ctrl_in_bus'], ...
    'Position', [235 65 245 235], ...
    'Inputs', '6', ...
    'OutDataTypeStr', 'Bus: ControllerInputBus');

add_block('simulink/Signal Routing/Bus Selector', [model '/ctrl_out_selector'], ...
    'Position', [405 90 415 165], ...
    'OutputSignals', 'tau_cmd,tau_load_hat');

add_block('simulink/Signal Attributes/Data Type Conversion', [model '/tau_cmd_to_double'], ...
    'Position', [455 112 475 138], ...
    'OutDataTypeStr', 'double');

add_block('simulink/Discontinuities/Saturation', [model '/torque_saturation'], ...
    'Position', [510 105 555 145], ...
    'UpperLimit', num2str(cfg.sim.tau_limit), ...
    'LowerLimit', num2str(-cfg.sim.tau_limit));

add_block('simulink/Discrete/Delay', [model '/command_delay'], ...
    'Position', [600 105 650 145], ...
    'DelayLength', '1', ...
    'InitialCondition', '0', ...
    'SampleTime', num2str(cfg.sim.Ts));

add_block('simulink/Discrete/Unit Delay', [model '/tau_prev'], ...
    'Position', [690 165 740 205], ...
    'InitialCondition', '0', ...
    'SampleTime', num2str(cfg.sim.Ts));

add_plant_block(model, cfg);

add_block('simulink/Math Operations/Gain', [model '/current_from_torque'], ...
    'Position', [870 115 920 145], ...
    'Gain', num2str(1/cfg.plant.Kt));

add_block('simulink/Math Operations/Product', [model '/I_squared'], ...
    'Position', [975 105 1005 145]);

add_block('simulink/Math Operations/Gain', [model '/heat_power_gain'], ...
    'Position', [1045 112 1095 138], ...
    'Gain', num2str(cfg.plant.R));

%% Scopes and outports
add_block('simulink/Signal Routing/Mux', [model '/position_mux'], ...
    'Position', [970 250 975 310], ...
    'Inputs', '2');
add_block('simulink/Sinks/Scope', [model '/position_scope'], ...
    'Position', [1030 245 1080 315]);

out_names = {'q', 'qdot', 'qddot', 'tau_cmd', 'tau_applied', ...
    'tau_load', 'tau_load_hat', 'current', 'heat_power'};
for i = 1:numel(out_names)
    y = 380 + (i - 1)*45;
    add_block('simulink/Sinks/Out1', [model '/' out_names{i}], ...
        'Position', [1050 y 1080 y+20]);
end

%% Wiring
add_line(model, 'q_ref_step/1', 'q_ref_to_fixed/1', 'autorouting', 'on');
name_line(add_line(model, 'q_ref_to_fixed/1', 'ctrl_in_bus/1', 'autorouting', 'on'), 'q_ref');
add_line(model, 'controller_mode/1', 'mode_signal_conversion/1', 'autorouting', 'on');
name_line(add_line(model, 'mode_signal_conversion/1', 'ctrl_in_bus/6', 'autorouting', 'on'), 'mode');
add_line(model, 'ctrl_in_bus/1', 'Controller/1', 'autorouting', 'on');
add_line(model, 'Controller/1', 'ctrl_out_selector/1', 'autorouting', 'on');
add_line(model, 'ctrl_out_selector/1', 'tau_cmd_to_double/1', 'autorouting', 'on');
add_line(model, 'tau_cmd_to_double/1', 'torque_saturation/1', 'autorouting', 'on');
add_line(model, 'ctrl_out_selector/2', 'tau_load_hat/1', 'autorouting', 'on');
add_line(model, 'torque_saturation/1', 'command_delay/1', 'autorouting', 'on');
add_line(model, 'command_delay/1', 'Plant/1', 'autorouting', 'on');
add_line(model, 'command_delay/1', 'tau_applied/1', 'autorouting', 'on');
add_line(model, 'command_delay/1', 'tau_prev/1', 'autorouting', 'on');
add_line(model, 'tau_prev/1', 'tau_prev_to_fixed/1', 'autorouting', 'on');
name_line(add_line(model, 'tau_prev_to_fixed/1', 'ctrl_in_bus/5', 'autorouting', 'on'), 'tau_prev');
add_line(model, 'tau_load_step/1', 'Plant/2', 'autorouting', 'on');
add_line(model, 'tau_load_step/1', 'tau_load/1', 'autorouting', 'on');

add_line(model, 'Plant/1', 'q_to_fixed/1', 'autorouting', 'on');
name_line(add_line(model, 'q_to_fixed/1', 'ctrl_in_bus/2', 'autorouting', 'on'), 'q');
add_line(model, 'Plant/2', 'qdot_to_fixed/1', 'autorouting', 'on');
name_line(add_line(model, 'qdot_to_fixed/1', 'ctrl_in_bus/3', 'autorouting', 'on'), 'qdot');
add_line(model, 'Plant/3', 'qddot_to_fixed/1', 'autorouting', 'on');
name_line(add_line(model, 'qddot_to_fixed/1', 'ctrl_in_bus/4', 'autorouting', 'on'), 'qddot');
add_line(model, 'Plant/1', 'q/1', 'autorouting', 'on');
add_line(model, 'Plant/2', 'qdot/1', 'autorouting', 'on');
add_line(model, 'Plant/3', 'qddot/1', 'autorouting', 'on');

add_line(model, 'ctrl_out_selector/1', 'tau_cmd/1', 'autorouting', 'on');
add_line(model, 'command_delay/1', 'current_from_torque/1', 'autorouting', 'on');
add_line(model, 'current_from_torque/1', 'current/1', 'autorouting', 'on');
add_line(model, 'current_from_torque/1', 'I_squared/1', 'autorouting', 'on');
add_line(model, 'current_from_torque/1', 'I_squared/2', 'autorouting', 'on');
add_line(model, 'I_squared/1', 'heat_power_gain/1', 'autorouting', 'on');
add_line(model, 'heat_power_gain/1', 'heat_power/1', 'autorouting', 'on');

add_line(model, 'q_ref_step/1', 'position_mux/1', 'autorouting', 'on');
add_line(model, 'Plant/1', 'position_mux/2', 'autorouting', 'on');
add_line(model, 'position_mux/1', 'position_scope/1', 'autorouting', 'on');

%% Save and run a quick update
Simulink.BlockDiagram.arrangeSystem(model);
set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built Simulink model:\n  %s\n', model_file);
fprintf('Controller mode constant: 1=PID, 2=DOB+PD, 3=Impedance\n');

%% Local helpers
function add_controller_subsystem(model, cfg)
    subsystem = [model '/Controller'];
    add_block('built-in/Subsystem', subsystem, 'Position', [285 80 365 180]);
    configure_reusable_function(subsystem, 'usr_pid');

    add_block('simulink/Sources/In1', [subsystem '/ctrl_in'], ...
        'Position', [30 140 60 160], ...
        'OutDataTypeStr', 'Bus: ControllerInputBus');
    add_block('simulink/Signal Routing/Bus Selector', [subsystem '/select_inputs'], ...
        'Position', [105 45 115 255], ...
        'OutputSignals', 'q_ref,q,qdot,qddot,tau_prev,mode');

    add_block('simulink/User-Defined Functions/MATLAB Function', [subsystem '/Core'], ...
        'Position', [185 65 335 235]);

    code = sprintf([ ...
        'function [tau_cmd, tau_load_hat] = fcn(q_ref, q, qdot, qddot, tau_prev, mode)\n' ...
        '%%#codegen\n' ...
        'persistent integral_e dob_hat\n' ...
        'if isempty(integral_e)\n' ...
        '    integral_e = fi(0, 1, 16, 13);\n' ...
        '    dob_hat = fi(0, 1, 16, 13);\n' ...
        'end\n' ...
        'q_ref_f = fi(q_ref, 1, 16, 12);\n' ...
        'q_f = fi(q, 1, 16, 12);\n' ...
        'qdot_f = fi(qdot, 1, 16, 8);\n' ...
        'qddot_f = fi(qddot, 1, 16, 4);\n' ...
        'tau_prev_f = fi(tau_prev, 1, 16, 12);\n' ...
        'Ts = fi(%.17g, 1, 16, 15);\n' ...
        'tau_limit = fi(%.17g, 1, 16, 13);\n' ...
        'integral_limit = fi(%.17g, 1, 16, 13);\n' ...
        'tau_hat_limit = fi(%.17g, 1, 16, 13);\n' ...
        'Kp_pid = fi(%.17g, 1, 16, 10);\n' ...
        'Ki_pid = fi(%.17g, 1, 16, 10);\n' ...
        'Kd_pid = fi(%.17g, 1, 16, 14);\n' ...
        'Kp_dob = fi(%.17g, 1, 16, 10);\n' ...
        'Kd_dob = fi(%.17g, 1, 16, 14);\n' ...
        'Jn_dob = fi(%.17g, 1, 16, 15);\n' ...
        'bn_dob = fi(%.17g, 1, 16, 15);\n' ...
        'alpha_dob = fi(%.17g, 1, 16, 14);\n' ...
        'K_imp = fi(%.17g, 1, 16, 10);\n' ...
        'D_imp = fi(%.17g, 1, 16, 14);\n' ...
        'e = fi(q_ref_f - q_f, 1, 16, 12);\n' ...
        'tau_cmd = fi(0, 1, 16, 13);\n' ...
        'tau_load_hat = fi(0, 1, 16, 13);\n' ...
        'if mode < uint8(2)\n' ...
        '    integral_e = fi(integral_e + Ts*e, 1, 16, 13);\n' ...
        '    if integral_e > integral_limit\n' ...
        '        integral_e = integral_limit;\n' ...
        '    elseif integral_e < -integral_limit\n' ...
        '        integral_e = -integral_limit;\n' ...
        '    end\n' ...
        '    tau_cmd = fi(Kp_pid*e + Ki_pid*integral_e - Kd_pid*qdot_f, 1, 16, 13);\n' ...
        'elseif mode < uint8(3)\n' ...
        '    raw_load = fi(tau_prev_f - Jn_dob*qddot_f - bn_dob*qdot_f, 1, 16, 13);\n' ...
        '    dob_hat = fi(dob_hat + alpha_dob*(raw_load - dob_hat), 1, 16, 13);\n' ...
        '    if dob_hat > tau_hat_limit\n' ...
        '        dob_hat = tau_hat_limit;\n' ...
        '    elseif dob_hat < -tau_hat_limit\n' ...
        '        dob_hat = -tau_hat_limit;\n' ...
        '    end\n' ...
        '    tau_load_hat = dob_hat;\n' ...
        '    tau_cmd = fi(Kp_dob*e - Kd_dob*qdot_f + tau_load_hat, 1, 16, 13);\n' ...
        'else\n' ...
        '    tau_cmd = fi(K_imp*e - D_imp*qdot_f, 1, 16, 13);\n' ...
        'end\n' ...
        'if tau_cmd > tau_limit\n' ...
        '    tau_cmd = tau_limit;\n' ...
        'elseif tau_cmd < -tau_limit\n' ...
        '    tau_cmd = -tau_limit;\n' ...
        'end\n' ...
        'end\n'], ...
        cfg.sim.Ts, cfg.sim.tau_limit, cfg.pid.integral_limit, cfg.dob_pd.tau_hat_limit, ...
        cfg.pid.Kp, cfg.pid.Ki, cfg.pid.Kd, cfg.dob_pd.Kp, cfg.dob_pd.Kd, ...
        cfg.dob_pd.Jn, cfg.dob_pd.bn, 1 - exp(-2*pi*cfg.dob_pd.observer_bw_hz*cfg.sim.Ts), ...
        cfg.impedance.K, cfg.impedance.D);

    set_matlab_function_code([subsystem '/Core'], code);

    add_block('simulink/Signal Routing/Bus Creator', [subsystem '/create_output'], ...
        'Position', [390 105 400 185], ...
        'Inputs', '2', ...
        'OutDataTypeStr', 'Bus: ControllerOutputBus');
    add_block('simulink/Sinks/Out1', [subsystem '/ctrl_out'], ...
        'Position', [455 140 485 160], ...
        'OutDataTypeStr', 'Bus: ControllerOutputBus');

    add_line(subsystem, 'ctrl_in/1', 'select_inputs/1', 'autorouting', 'on');
    for i = 1:6
        add_line(subsystem, sprintf('select_inputs/%d', i), sprintf('Core/%d', i), ...
            'autorouting', 'on');
    end
    add_line(subsystem, 'Core/1', 'create_output/1', 'autorouting', 'on');
    add_line(subsystem, 'Core/2', 'create_output/2', 'autorouting', 'on');
    add_line(subsystem, 'create_output/1', 'ctrl_out/1', 'autorouting', 'on');

    Simulink.BlockDiagram.arrangeSystem(subsystem);
end

function configure_reusable_function(block_path, function_name)
    set_param(block_path, ...
        'RTWSystemCode', 'Reusable function', ...
        'RTWFcnNameOpts', 'User specified', ...
        'RTWFcnName', function_name, ...
        'RTWFileNameOpts', 'User specified', ...
        'RTWFileName', function_name);
end

function name_line(line_handle, signal_name)
    set_param(line_handle, 'Name', signal_name);
end

function add_fixed_conversion(model, name, position, data_type)
    add_block('simulink/Signal Attributes/Data Type Conversion', [model '/' name], ...
        'Position', position, ...
        'OutDataTypeStr', data_type, ...
        'RndMeth', 'Zero', ...
        'SaturateOnIntegerOverflow', 'on');
end

function add_plant_block(model, cfg)
    plant = [model '/Plant'];
    add_block('built-in/Subsystem', plant, 'Position', [670 75 810 235]);

    add_block('simulink/Sources/In1', [plant '/tau'], 'Position', [30 45 60 65]);
    add_block('simulink/Sources/In1', [plant '/tau_load'], 'Position', [30 120 60 140]);
    add_block('simulink/Math Operations/Gain', [plant '/b'], ...
        'Position', [165 190 215 220], 'Gain', num2str(cfg.plant.b));
    add_block('simulink/Math Operations/Sum', [plant '/sum_tau'], ...
        'Position', [255 75 285 125], 'Inputs', '+--');
    add_block('simulink/Math Operations/Gain', [plant '/inv_J'], ...
        'Position', [325 85 375 115], 'Gain', num2str(1/cfg.plant.J));
    add_block('simulink/Discrete/Discrete-Time Integrator', [plant '/qdot_integrator'], ...
        'Position', [425 85 475 115], ...
        'gainval', '1', ...
        'InitialCondition', num2str(cfg.sim.qdot0), ...
        'SampleTime', num2str(cfg.sim.Ts));
    add_block('simulink/Discrete/Discrete-Time Integrator', [plant '/q_integrator'], ...
        'Position', [545 85 595 115], ...
        'gainval', '1', ...
        'InitialCondition', num2str(cfg.sim.q0), ...
        'SampleTime', num2str(cfg.sim.Ts));
    add_block('simulink/Sinks/Out1', [plant '/q'], 'Position', [665 90 695 110]);
    add_block('simulink/Sinks/Out1', [plant '/qdot'], 'Position', [665 145 695 165]);
    add_block('simulink/Sinks/Out1', [plant '/qddot'], 'Position', [665 200 695 220]);

    add_line(plant, 'tau/1', 'sum_tau/1', 'autorouting', 'on');
    add_line(plant, 'tau_load/1', 'sum_tau/2', 'autorouting', 'on');
    add_line(plant, 'qdot_integrator/1', 'b/1', 'autorouting', 'on');
    add_line(plant, 'b/1', 'sum_tau/3', 'autorouting', 'on');
    add_line(plant, 'sum_tau/1', 'inv_J/1', 'autorouting', 'on');
    add_line(plant, 'inv_J/1', 'qdot_integrator/1', 'autorouting', 'on');
    add_line(plant, 'qdot_integrator/1', 'q_integrator/1', 'autorouting', 'on');
    add_line(plant, 'q_integrator/1', 'q/1', 'autorouting', 'on');
    add_line(plant, 'qdot_integrator/1', 'qdot/1', 'autorouting', 'on');
    add_line(plant, 'inv_J/1', 'qddot/1', 'autorouting', 'on');

    Simulink.BlockDiagram.arrangeSystem(plant);
end

function set_matlab_function_code(block_path, code)
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block_path);
    if isempty(chart)
        error('Could not find MATLAB Function chart: %s', block_path);
    end
    chart.Script = code;
end
