%% Build a controller-only Simulink model for focused C code generation
% This model contains only the Controller MATLAB Function block plus inports
% and outports. It is easier to inspect than the full plant simulation model.

clear; clc;

script_dir = fileparts(mfilename('fullpath'));
root_dir = fileparts(script_dir);
matlab_dir = fullfile(root_dir, 'matlab');
addpath(matlab_dir);

cfg = config_default();
fxp = init_controller_fixed_point_types(cfg);
model = 'single_joint_controller_only';
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);

set_param(model, ...
    'StopTime', '1.0', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(cfg.sim.Ts), ...
    'SystemTargetFile', 'grt.tlc', ...
    'ProdHWDeviceType', 'Intel->x86-64 (Linux 64)', ...
    'TargetHWDeviceType', 'Intel->x86-64 (Linux 64)', ...
    'GenerateReport', 'on');

in_names = {'q_ref', 'q', 'qdot', 'qddot', 'tau_prev', 'mode'};
in_types = {'T_angle', 'T_angle', 'T_speed', 'T_accel', 'T_torque_wide', 'uint8'};
for i = 1:numel(in_names)
    y = 55 + (i - 1)*45;
    add_block('simulink/Sources/In1', [model '/' in_names{i}], ...
    'Position', [45 y 75 y+20], ...
    'OutDataTypeStr', in_types{i});
end

add_block('simulink/User-Defined Functions/MATLAB Function', [model '/Controller'], ...
    'Position', [185 70 335 250]);
set_matlab_function_code([model '/Controller'], controller_code(cfg));

out_names = {'tau_cmd', 'tau_load_hat'};
for i = 1:numel(out_names)
    y = 110 + (i - 1)*80;
    add_block('simulink/Sinks/Out1', [model '/' out_names{i}], ...
    'Position', [445 y 475 y+20], ...
    'OutDataTypeStr', 'T_torque');
end

for i = 1:numel(in_names)
    add_line(model, [in_names{i} '/1'], sprintf('Controller/%d', i), 'autorouting', 'on');
end
add_line(model, 'Controller/1', 'tau_cmd/1', 'autorouting', 'on');
add_line(model, 'Controller/2', 'tau_load_hat/1', 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(model);
set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built controller-only Simulink model:\n  %s\n', model_file);

function code = controller_code(cfg)
    code = sprintf([ ...
        'function [tau_cmd, tau_load_hat] = fcn(q_ref, q, qdot, qddot, tau_prev, mode)\n' ...
        '%%#codegen\n' ...
        'persistent integral_e dob_hat\n' ...
        'if isempty(integral_e)\n' ...
        '    integral_e = fi(0, 1, 16, 13);\n' ...
        '    dob_hat = fi(0, 1, 16, 13);\n' ...
        'end\n' ...
        'q_ref_f = fi(q_ref, 1, 16, 12);\n' ...
        'q_f = fi(q, 1, 16, 12);\n' ...
        'qdot_f = fi(qdot, 1, 16, 8);\n' ...
        'qddot_f = fi(qddot, 1, 16, 4);\n' ...
        'tau_prev_f = fi(tau_prev, 1, 16, 12);\n' ...
        'Ts = fi(%.17g, 1, 16, 15);\n' ...
        'tau_limit = fi(%.17g, 1, 16, 13);\n' ...
        'integral_limit = fi(%.17g, 1, 16, 13);\n' ...
        'tau_hat_limit = fi(%.17g, 1, 16, 13);\n' ...
        'Kp_pid = fi(%.17g, 1, 16, 10);\n' ...
        'Ki_pid = fi(%.17g, 1, 16, 10);\n' ...
        'Kd_pid = fi(%.17g, 1, 16, 14);\n' ...
        'Kp_dob = fi(%.17g, 1, 16, 10);\n' ...
        'Kd_dob = fi(%.17g, 1, 16, 14);\n' ...
        'Jn_dob = fi(%.17g, 1, 16, 15);\n' ...
        'bn_dob = fi(%.17g, 1, 16, 15);\n' ...
        'alpha_dob = fi(%.17g, 1, 16, 14);\n' ...
        'K_imp = fi(%.17g, 1, 16, 10);\n' ...
        'D_imp = fi(%.17g, 1, 16, 14);\n' ...
        'e = fi(q_ref_f - q_f, 1, 16, 12);\n' ...
        'tau_cmd = fi(0, 1, 16, 13);\n' ...
        'tau_load_hat = fi(0, 1, 16, 13);\n' ...
        'if mode < uint8(2)\n' ...
        '    integral_e = fi(integral_e + Ts*e, 1, 16, 13);\n' ...
        '    if integral_e > integral_limit\n' ...
        '        integral_e = integral_limit;\n' ...
        '    elseif integral_e < -integral_limit\n' ...
        '        integral_e = -integral_limit;\n' ...
        '    end\n' ...
        '    tau_cmd = fi(Kp_pid*e + Ki_pid*integral_e - Kd_pid*qdot_f, 1, 16, 13);\n' ...
        'elseif mode < uint8(3)\n' ...
        '    raw_load = fi(tau_prev_f - Jn_dob*qddot_f - bn_dob*qdot_f, 1, 16, 13);\n' ...
        '    dob_hat = fi(dob_hat + alpha_dob*(raw_load - dob_hat), 1, 16, 13);\n' ...
        '    if dob_hat > tau_hat_limit\n' ...
        '        dob_hat = tau_hat_limit;\n' ...
        '    elseif dob_hat < -tau_hat_limit\n' ...
        '        dob_hat = -tau_hat_limit;\n' ...
        '    end\n' ...
        '    tau_load_hat = dob_hat;\n' ...
        '    tau_cmd = fi(Kp_dob*e - Kd_dob*qdot_f + tau_load_hat, 1, 16, 13);\n' ...
        'else\n' ...
        '    tau_cmd = fi(K_imp*e - D_imp*qdot_f, 1, 16, 13);\n' ...
        'end\n' ...
        'if tau_cmd > tau_limit\n' ...
        '    tau_cmd = tau_limit;\n' ...
        'elseif tau_cmd < -tau_limit\n' ...
        '    tau_cmd = -tau_limit;\n' ...
        'end\n' ...
        'end\n'], ...
        cfg.sim.Ts, cfg.sim.tau_limit, cfg.pid.integral_limit, cfg.dob_pd.tau_hat_limit, ...
        cfg.pid.Kp, cfg.pid.Ki, cfg.pid.Kd, cfg.dob_pd.Kp, cfg.dob_pd.Kd, ...
        cfg.dob_pd.Jn, cfg.dob_pd.bn, 1 - exp(-2*pi*cfg.dob_pd.observer_bw_hz*cfg.sim.Ts), ...
        cfg.impedance.K, cfg.impedance.D);
end

function set_matlab_function_code(block_path, code)
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block_path);
    if isempty(chart)
        error('Could not find MATLAB Function chart: %s', block_path);
    end
    chart.Script = code;
end
