%% Build a current PI saturation test harness
%
% The harness connects CurrentPiStep to a simple first-order q-axis current
% plant. It is designed to compare normal back-calculation anti-windup against
% Kaw_iq = 0 without changing the reusable PI algorithm itself.

clc;

script_dir = fileparts(mfilename('fullpath'));
run(fullfile(script_dir, 'build_current_pi_model.m'));

cfg = customer_interface_config();
cfg.dictionaryFile = fullfile(script_dir, cfg.dictionaryName);
assignin('base', 'current_pi_saturation_test_config', cfg);

sat_test = default_saturation_test_params();
assignin('base', 'current_pi_sat_test', sat_test);
assignin('base', 'current_pi_simcfg', sat_test.simcfg);

model = cfg.modelName;
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

if exist(model_file, 'file')
    delete(model_file);
end

previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);
load_system('current_pi_model.slx');

new_system(model);
set_param(model, 'DataDictionary', cfg.dictionaryName);
set_param(model, ...
    'StopTime', 'current_pi_sat_test.simcfg.stop_time', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'current_pi_simcfg.Ts_ctrl', ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'off', ...
    'RTWVerbose', 'off', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'InlineParams', 'off');

add_block('current_pi_model/CurrentPiStep', [model '/CurrentPiStep'], ...
    'Position', [350 110 550 210]);
close_system('current_pi_model', 0);

add_simple_q_axis_plant(model, cfg);
add_test_sources(model, cfg);
add_output_logs(model);

set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built current PI saturation test model:\n  %s\n', model_file);

function cfg = customer_interface_config()
cfg.modelName = 'current_pi_saturation_test_model';
cfg.dictionaryName = 'current_pi_interface.sldd';

cfg.currentTypeName = 'T_CurrentPiCurrent';
cfg.voltageTypeName = 'T_CurrentPiVoltage';
cfg.speedTypeName = 'T_CurrentPiSpeed';
cfg.gainTypeName = 'T_CurrentPiGain';
cfg.inputBusName = 'current_pi_input_t';
cfg.outputBusName = 'current_pi_output_t';
cfg.sampleTime = 'current_pi_simcfg.Ts_ctrl';
end

function sat_test = default_saturation_test_params()
sat_test.simcfg.stop_time = 0.040;
sat_test.simcfg.Ts_ctrl = 50e-6;

sat_test.ref.iq_high = single(30);
sat_test.ref.on_time = 0.002;
sat_test.ref.release_time = 0.012;

sat_test.vdc = single(12);
sat_test.v_limit_ratio = single(0.577);

sat_test.plant.tau = 1.0e-3;
sat_test.plant.current_per_volt = single(1);
sat_test.plant.alpha = single(sat_test.simcfg.Ts_ctrl / sat_test.plant.tau);
end

function add_test_sources(model, cfg)
add_typed_constant(model, 'id_ref_zero', [50 45 115 70], '0', ...
    cfg.currentTypeName, cfg.sampleTime);
add_typed_constant(model, 'id_meas_zero', [50 165 115 190], '0', ...
    cfg.currentTypeName, cfg.sampleTime);
add_typed_constant(model, 'omega_e_zero', [50 225 115 250], '0', ...
    cfg.speedTypeName, cfg.sampleTime);
add_typed_constant(model, 'vdc_low', [50 285 115 310], ...
    'current_pi_sat_test.vdc', cfg.voltageTypeName, cfg.sampleTime);

add_block('simulink/Sources/Step', [model '/iq_ref_on_step'], ...
    'Position', [50 85 115 115], ...
    'Time', 'current_pi_sat_test.ref.on_time', ...
    'Before', '0', ...
    'After', 'current_pi_sat_test.ref.iq_high', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Sources/Step', [model '/iq_ref_release_step'], ...
    'Position', [50 125 115 155], ...
    'Time', 'current_pi_sat_test.ref.release_time', ...
    'Before', '0', ...
    'After', '-current_pi_sat_test.ref.iq_high', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Math Operations/Sum', [model '/iq_ref_sum'], ...
    'Position', [155 100 185 145], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', cfg.currentTypeName, ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/iq_ref_to_pi_type'], ...
    'Position', [215 107 290 137], ...
    'OutDataTypeStr', cfg.currentTypeName);

add_block('simulink/Signal Routing/Bus Creator', [model '/pi_input_bus_creator'], ...
    'Position', [315 45 330 310], ...
    'Inputs', '6', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.inputBusName, ...
    'NonVirtualBus', 'on');

add_line(model, 'iq_ref_on_step/1', 'iq_ref_sum/1', 'autorouting', 'on');
add_line(model, 'iq_ref_release_step/1', 'iq_ref_sum/2', 'autorouting', 'on');
add_line(model, 'iq_ref_sum/1', 'iq_ref_to_pi_type/1', 'autorouting', 'on');

name_line(add_line(model, 'id_ref_zero/1', 'pi_input_bus_creator/1', ...
    'autorouting', 'on'), 'id_ref');
name_line(add_line(model, 'iq_ref_to_pi_type/1', 'pi_input_bus_creator/2', ...
    'autorouting', 'on'), 'iq_ref');
name_line(add_line(model, 'id_meas_zero/1', 'pi_input_bus_creator/3', ...
    'autorouting', 'on'), 'id_meas');
name_line(add_line(model, 'iq_meas_state/1', 'pi_input_bus_creator/4', ...
    'autorouting', 'on'), 'iq_meas');
name_line(add_line(model, 'omega_e_zero/1', 'pi_input_bus_creator/5', ...
    'autorouting', 'on'), 'omega_e');
name_line(add_line(model, 'vdc_low/1', 'pi_input_bus_creator/6', ...
    'autorouting', 'on'), 'vdc');

add_line(model, 'pi_input_bus_creator/1', 'CurrentPiStep/1', ...
    'autorouting', 'on');
end

function add_simple_q_axis_plant(model, cfg)
add_block('simulink/Signal Routing/Bus Selector', [model '/pi_output_selector'], ...
    'Position', [600 110 615 210], ...
    'OutputSignals', 'vd_ref,vq_ref');
add_line(model, 'CurrentPiStep/1', 'pi_output_selector/1', 'autorouting', 'on');

add_block('simulink/Discrete/Unit Delay', [model '/iq_meas_state'], ...
    'Position', [805 245 875 275], ...
    'InitialCondition', '0', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Math Operations/Gain', [model '/vq_to_current_target'], ...
    'Position', [660 150 740 180], ...
    'Gain', 'current_pi_sat_test.plant.current_per_volt', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Math Operations/Sum', [model '/plant_error'], ...
    'Position', [780 160 810 205], ...
    'Inputs', '+-', ...
    'AccumDataTypeStr', cfg.currentTypeName, ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Math Operations/Gain', [model '/plant_delta'], ...
    'Position', [850 165 930 195], ...
    'Gain', 'current_pi_sat_test.plant.alpha', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Math Operations/Sum', [model '/plant_next_current'], ...
    'Position', [965 185 995 235], ...
    'Inputs', '++', ...
    'AccumDataTypeStr', cfg.currentTypeName, ...
    'OutDataTypeStr', cfg.currentTypeName);

add_line(model, 'pi_output_selector/2', 'vq_to_current_target/1', ...
    'autorouting', 'on');
add_line(model, 'vq_to_current_target/1', 'plant_error/1', ...
    'autorouting', 'on');
add_line(model, 'iq_meas_state/1', 'plant_error/2', ...
    'autorouting', 'on');
add_line(model, 'plant_error/1', 'plant_delta/1', ...
    'autorouting', 'on');
add_line(model, 'plant_delta/1', 'plant_next_current/1', ...
    'autorouting', 'on');
add_line(model, 'iq_meas_state/1', 'plant_next_current/2', ...
    'autorouting', 'on');
add_line(model, 'plant_next_current/1', 'iq_meas_state/1', ...
    'autorouting', 'on');
end

function add_output_logs(model)
add_scalar_logger(model, 'log_iq_ref_sat', [215 55 315 85], 'iq_ref_to_pi_type/1');
add_scalar_logger(model, 'log_iq_meas_sat', [895 245 1005 275], 'iq_meas_state/1');
add_scalar_logger(model, 'log_vd_ref_sat', [660 85 760 115], 'pi_output_selector/1');
add_scalar_logger(model, 'log_vq_ref_sat', [660 205 760 235], 'pi_output_selector/2');
end

function add_typed_constant(model, block_name, position, value, data_type, sample_time)
add_block('simulink/Sources/Constant', [model '/' block_name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', sample_time);
end

function add_scalar_logger(model, variable_name, position, src_port)
add_block('simulink/Sinks/To Workspace', [model '/' variable_name], ...
    'Position', position, ...
    'VariableName', variable_name, ...
    'SaveFormat', 'Timeseries');
add_line(model, src_port, [variable_name '/1'], 'autorouting', 'on');
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
