%% Build a float-based current-loop motor integration model
%
% Milestone:
%   id_ref step, iq_ref = 0
%
% This top-level model integrates reusable algorithm subsystems with the
% Average-Value Inverter and PMSM plant. The plant remains a simulation
% harness; controller subsystems remain the embedded-code candidates.

clc;

cfg = customer_interface_config();
script_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(script_dir);
cfg.dictionaryFile = fullfile(script_dir, cfg.dictionaryName);
assignin('base', 'motor_current_loop_config', cfg);

previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

ensure_source_models(repo_dir);

params = default_current_loop_params();
assignin('base', 'motor', params.motor);
assignin('base', 'inverter', params.inverter);
assignin('base', 'simcfg', params.simcfg);
assignin('base', 'current_loop', params.current_loop);
assignin('base', 'current_pi_simcfg', params.simcfg);

model = cfg.modelName;
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

close_open_data_dictionaries();
create_current_loop_data_dictionary(cfg, params);

if exist(model_file, 'file')
    delete(model_file);
end

load_system('mcbplantlib');
load_system('mcblib');

source_models = load_source_models(repo_dir);

new_system(model);
set_param(model, 'DataDictionary', cfg.dictionaryName);
set_param(model, ...
    'StopTime', 'simcfg.stop_time', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'simcfg.Ts_plant', ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'InlineParams', 'off');

set_param(model, ...
    'CodeInterfacePackaging', 'Reusable function', ...
    'ModelReferenceNumInstancesAllowed', 'Multi');

copy_reusable_subsystems(model, source_models);
close_source_models(source_models);

add_current_reference_sources(model, cfg);
add_average_inverter_and_plant(model, cfg);
add_feedback_to_dq_adapter(model, cfg);
add_pi_input_adapter(model, cfg);
add_dq_voltage_to_duty_cmd_adapter(model, cfg);
connect_current_loop(model);
add_log_outputs(model);

set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built current-loop motor integration model:\n  %s\n', model_file);

function cfg = customer_interface_config()
% Customer-editable interface and architecture contract.
cfg.modelName = 'motor_current_loop_model';
cfg.sampleTime = 'simcfg.Ts_ctrl';
cfg.plantSampleTime = 'simcfg.Ts_plant';
cfg.rebuildDictionary = true;

cfg.dictionaryName = 'motor_current_loop_interface.sldd';
cfg.typeHeaderFile = 'motor_current_loop_types.h';

cfg.realTypeName = 'T_MotorFloat';
cfg.voltageTypeName = 'T_MotorVoltage';
cfg.angleTypeName = 'T_MotorAngle';
cfg.currentTypeName = 'T_MotorCurrent';
cfg.speedTypeName = 'T_MotorSpeed';
cfg.torqueTypeName = 'T_MotorTorque';
cfg.dutyTypeName = 'T_DutyRatio';

cfg.currentPiRealTypeName = 'T_CurrentPiFloat';
cfg.currentPiCurrentTypeName = 'T_CurrentPiCurrent';
cfg.currentPiVoltageTypeName = 'T_CurrentPiVoltage';
cfg.currentPiSpeedTypeName = 'T_CurrentPiSpeed';
cfg.currentPiGainTypeName = 'T_CurrentPiGain';

cfg.motorInputBusName = 'motor_t';
cfg.motorDqBusName = 'motor_dq_t';
cfg.openLoopCmdBusName = 'open_loop_cmd_t';
cfg.phaseDutyBusName = 'phase_duty_t';
cfg.plantFeedbackBusName = 'plant_feedback_t';
cfg.currentPiInputBusName = 'current_pi_input_t';
cfg.currentPiOutputBusName = 'current_pi_output_t';

cfg.floatBaseType = 'single';
end

function p = default_current_loop_params()
p.simcfg.stop_time = 0.050;
p.simcfg.Ts_plant = 25e-6;
p.simcfg.Ts_ctrl = 50e-6;

p.inverter.Vdc = 68;
p.inverter.load_torque = 0;

p.motor.type = 'SPMSM';
p.motor.pole_pairs = 10;
p.motor.back_emf_vrms_per_krpm = 17.03;
p.motor.line_to_line_resistance = 0.4267;
p.motor.line_to_line_inductance = 0.53e-3;
p.motor.Rs = p.motor.line_to_line_resistance / 2;
p.motor.Ld = p.motor.line_to_line_inductance / 2;
p.motor.Lq = p.motor.Ld;
p.motor.psi_f = p.motor.back_emf_vrms_per_krpm / ...
    (sqrt(3/2) * p.motor.pole_pairs * (1000 * 2 * pi / 60));
p.motor.J = 2.5e-4;
p.motor.B = 1.0e-4;

current_bandwidth_rad_s = 2 * pi * 800;
p.current_loop.Kp_id = single(p.motor.Ld * current_bandwidth_rad_s);
p.current_loop.Ki_id = single(p.motor.Rs * current_bandwidth_rad_s);
p.current_loop.Kaw_id = single(400);
p.current_loop.Kp_iq = p.current_loop.Kp_id;
p.current_loop.Ki_iq = p.current_loop.Ki_id;
p.current_loop.Kaw_iq = p.current_loop.Kaw_id;
p.current_loop.VLimitRatio = single(0.577);

p.current_loop.ref.id_step_time = 0.005;
p.current_loop.ref.id_before = single(0);
p.current_loop.ref.id_after = single(3);
p.current_loop.ref.iq_ref = single(0);
end

function ensure_source_models(repo_dir)
source_specs = { ...
    fullfile(repo_dir, 'motor_current_pi_mbd', 'current_pi_model.slx'), ...
    fullfile(repo_dir, 'motor_current_pi_mbd', 'build_current_pi_model.m'); ...
    fullfile(repo_dir, 'motor_float_open_loop_mbd', 'motor_float_open_loop_model.slx'), ...
    fullfile(repo_dir, 'motor_float_open_loop_mbd', 'build_motor_float_open_loop_model.m'); ...
    fullfile(repo_dir, 'motor_clarke_park_struct', 'motor_clarke_park_model.slx'), ...
    fullfile(repo_dir, 'motor_clarke_park_struct', 'build_motor_clarke_park_model.m')};

for i = 1:size(source_specs, 1)
    if ~exist(source_specs{i, 1}, 'file')
        run(source_specs{i, 2});
    end
end
end

function source_models = load_source_models(repo_dir)
source_models.currentPi = 'current_pi_model';
source_models.openLoop = 'motor_float_open_loop_model';
source_models.clarkePark = 'motor_clarke_park_model';

load_model_from_folder(fullfile(repo_dir, 'motor_current_pi_mbd'), ...
    source_models.currentPi);
load_model_from_folder(fullfile(repo_dir, 'motor_float_open_loop_mbd'), ...
    source_models.openLoop);
load_model_from_folder(fullfile(repo_dir, 'motor_clarke_park_struct'), ...
    source_models.clarkePark);
end

function load_model_from_folder(model_dir, model_name)
previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(model_dir);
load_system([model_name '.slx']);
end

function close_source_models(source_models)
names = {source_models.currentPi, source_models.openLoop, ...
    source_models.clarkePark};
for i = 1:numel(names)
    if bdIsLoaded(names{i})
        close_system(names{i}, 0);
    end
end
end

function close_open_data_dictionaries()
try
    Simulink.data.dictionary.closeAll('-discard');
catch err
    warning('Could not close open data dictionaries before rebuild: %s', ...
        err.message);
end
end

function create_current_loop_data_dictionary(cfg, params)
dd = open_or_create_data_dictionary(cfg);
design_data = getSection(dd, 'Design Data');

upsert_alias_type(design_data, cfg.realTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.voltageTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.angleTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.currentTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.speedTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.torqueTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.dutyTypeName, cfg.floatBaseType, cfg.typeHeaderFile);

upsert_alias_type(design_data, cfg.currentPiRealTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.currentPiCurrentTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.currentPiVoltageTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.currentPiSpeedTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.currentPiGainTypeName, cfg.floatBaseType, cfg.typeHeaderFile);

upsert_bus_type(design_data, cfg.motorInputBusName, cfg.typeHeaderFile, { ...
    {'ia', cfg.currentTypeName}; ...
    {'ib', cfg.currentTypeName}; ...
    {'ic', cfg.currentTypeName}; ...
    {'theta_e', cfg.angleTypeName}});

upsert_bus_type(design_data, cfg.motorDqBusName, cfg.typeHeaderFile, { ...
    {'i_alpha', cfg.currentTypeName}; ...
    {'i_beta', cfg.currentTypeName}; ...
    {'id', cfg.currentTypeName}; ...
    {'iq', cfg.currentTypeName}});

upsert_bus_type(design_data, cfg.openLoopCmdBusName, cfg.typeHeaderFile, { ...
    {'vd', cfg.voltageTypeName}; ...
    {'vq', cfg.voltageTypeName}; ...
    {'theta_e', cfg.angleTypeName}; ...
    {'vdc', cfg.voltageTypeName}});

upsert_bus_type(design_data, cfg.phaseDutyBusName, cfg.typeHeaderFile, { ...
    {'da', cfg.dutyTypeName}; ...
    {'db', cfg.dutyTypeName}; ...
    {'dc', cfg.dutyTypeName}});

upsert_bus_type(design_data, cfg.plantFeedbackBusName, cfg.typeHeaderFile, { ...
    {'ia', cfg.currentTypeName}; ...
    {'ib', cfg.currentTypeName}; ...
    {'ic', cfg.currentTypeName}; ...
    {'wm', cfg.speedTypeName}; ...
    {'theta_m', cfg.angleTypeName}; ...
    {'theta_e', cfg.angleTypeName}});

upsert_bus_type(design_data, cfg.currentPiInputBusName, cfg.typeHeaderFile, { ...
    {'id_ref', cfg.currentPiCurrentTypeName}; ...
    {'iq_ref', cfg.currentPiCurrentTypeName}; ...
    {'id_meas', cfg.currentPiCurrentTypeName}; ...
    {'iq_meas', cfg.currentPiCurrentTypeName}; ...
    {'omega_e', cfg.currentPiSpeedTypeName}; ...
    {'vdc', cfg.currentPiVoltageTypeName}});

upsert_bus_type(design_data, cfg.currentPiOutputBusName, cfg.typeHeaderFile, { ...
    {'vd_ref', cfg.currentPiVoltageTypeName}; ...
    {'vq_ref', cfg.currentPiVoltageTypeName}});

upsert_parameter(design_data, 'Kp_id', params.current_loop.Kp_id, cfg.currentPiGainTypeName);
upsert_parameter(design_data, 'Ki_id', params.current_loop.Ki_id, cfg.currentPiGainTypeName);
upsert_parameter(design_data, 'Kaw_id', params.current_loop.Kaw_id, cfg.currentPiGainTypeName);
upsert_parameter(design_data, 'Kp_iq', params.current_loop.Kp_iq, cfg.currentPiGainTypeName);
upsert_parameter(design_data, 'Ki_iq', params.current_loop.Ki_iq, cfg.currentPiGainTypeName);
upsert_parameter(design_data, 'Kaw_iq', params.current_loop.Kaw_iq, cfg.currentPiGainTypeName);
upsert_parameter(design_data, 'VLimitRatio', params.current_loop.VLimitRatio, cfg.currentPiGainTypeName);

saveChanges(dd);
close(dd);
end

function dd = open_or_create_data_dictionary(cfg)
if isfield(cfg, 'rebuildDictionary') && cfg.rebuildDictionary && exist(cfg.dictionaryFile, 'file')
    delete(cfg.dictionaryFile);
end

if exist(cfg.dictionaryFile, 'file')
    dd = Simulink.data.dictionary.open(cfg.dictionaryFile);
else
    dd = Simulink.data.dictionary.create(cfg.dictionaryFile);
end
end

function upsert_alias_type(section, type_name, base_type, header_file)
alias_type = Simulink.AliasType(base_type);
alias_type.DataScope = 'Exported';
alias_type.HeaderFile = header_file;

entry = find(section, 'Name', type_name);
if isempty(entry)
    addEntry(section, type_name, alias_type);
else
    setValue(entry(1), alias_type);
end
end

function upsert_bus_type(section, bus_name, header_file, element_specs)
bus_elements = repmat(Simulink.BusElement, numel(element_specs), 1);
for i = 1:numel(element_specs)
    bus_elements(i).Name = element_specs{i}{1};
    bus_elements(i).DataType = element_specs{i}{2};
    bus_elements(i).Dimensions = 1;
end

bus_type = Simulink.Bus;
bus_type.Elements = bus_elements;
bus_type.DataScope = 'Exported';
bus_type.HeaderFile = header_file;

entry = find(section, 'Name', bus_name);
if isempty(entry)
    addEntry(section, bus_name, bus_type);
else
    setValue(entry(1), bus_type);
end
end

function upsert_parameter(section, name, value, data_type)
parameter = Simulink.Parameter(double(value));
parameter.DataType = data_type;
parameter.CoderInfo.StorageClass = 'Auto';

entry = find(section, 'Name', name);
if isempty(entry)
    addEntry(section, name, parameter);
else
    setValue(entry(1), parameter);
end
end

function copy_reusable_subsystems(model, source_models)
add_block([source_models.currentPi '/CurrentPiStep'], ...
    [model '/CurrentPiStep'], ...
    'Position', [430 130 630 230]);
add_block([source_models.openLoop '/DqToAbcDutyStep'], ...
    [model '/DqToAbcDutyStep'], ...
    'Position', [850 125 1065 235]);
add_block([source_models.clarkePark '/MotorClarkeParkStep'], ...
    [model '/MotorClarkeParkStep'], ...
    'Position', [430 360 630 465]);
end

function add_current_reference_sources(model, cfg)
add_block('simulink/Sources/Step', [model '/id_ref_step'], ...
    'Position', [45 75 95 105], ...
    'Time', 'current_loop.ref.id_step_time', ...
    'Before', 'current_loop.ref.id_before', ...
    'After', 'current_loop.ref.id_after', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/id_ref_to_pi_type'], ...
    'Position', [130 75 205 105], ...
    'OutDataTypeStr', cfg.currentPiCurrentTypeName);

add_block('simulink/Sources/Constant', [model '/iq_ref_zero'], ...
    'Position', [45 125 95 155], ...
    'Value', 'current_loop.ref.iq_ref', ...
    'OutDataTypeStr', cfg.currentPiCurrentTypeName, ...
    'SampleTime', cfg.sampleTime);

add_block('simulink/Sources/Constant', [model '/vdc_ctrl'], ...
    'Position', [45 275 95 305], ...
    'Value', 'inverter.Vdc', ...
    'OutDataTypeStr', cfg.currentPiVoltageTypeName, ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/vdc_to_motor_voltage'], ...
    'Position', [130 275 205 305], ...
    'OutDataTypeStr', cfg.voltageTypeName);

add_line(model, 'id_ref_step/1', 'id_ref_to_pi_type/1', 'autorouting', 'on');
add_line(model, 'vdc_ctrl/1', 'vdc_to_motor_voltage/1', 'autorouting', 'on');
end

function add_average_inverter_and_plant(model, cfg)
add_block('simulink/Sources/Constant', [model '/LoadTorque'], ...
    'Position', [865 575 935 600], ...
    'Value', 'inverter.load_torque', ...
    'SampleTime', cfg.plantSampleTime, ...
    'OutDataTypeStr', cfg.torqueTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/LoadTorque_to_double'], ...
    'Position', [970 572 1055 602], ...
    'OutDataTypeStr', 'double');

add_block('mcbplantlib/Average-Value Inverter', [model '/Average Inverter'], ...
    'Position', [1230 125 1410 230]);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/Vabc_to_double'], ...
    'Position', [1440 170 1480 210], ...
    'OutDataTypeStr', 'double');
add_block('mcblib/Electrical Systems/Motors/Surface Mount PMSM', ...
    [model '/Surface Mount PMSM'], ...
    'Position', [1510 160 1720 320]);
set_param([model '/Surface Mount PMSM'], ...
    'port_config', 'Torque', ...
    'sim_type', 'Discrete', ...
    'Ts', 'simcfg.Ts_plant', ...
    'P', 'motor.pole_pairs', ...
    'Rs', 'motor.Rs', ...
    'Ldq_', 'motor.Ld', ...
    'lambda_pm', 'motor.psi_f', ...
    'mechanical', '[motor.J, motor.B, 0]', ...
    'idq0', '[0 0]', ...
    'theta_init', '0', ...
    'omega_init', '0');

add_block('simulink/Signal Routing/Bus Selector', [model '/phase_duty_selector'], ...
    'Position', [1095 125 1110 235], ...
    'OutputSignals', 'da,db,dc');
add_block('simulink/Signal Routing/Mux', [model '/phase_duty_mux'], ...
    'Position', [1140 145 1145 225], ...
    'Inputs', '3');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/PhaseDuty_RateTransition_25us'], ...
    'Position', [1175 165 1210 205], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', cfg.plantSampleTime);
add_block('simulink/Sources/Constant', [model '/Vdc_plant'], ...
    'Position', [1095 265 1145 295], ...
    'Value', 'inverter.Vdc', ...
    'SampleTime', cfg.plantSampleTime, ...
    'OutDataTypeStr', cfg.voltageTypeName);
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/Vdc_RateTransition_25us'], ...
    'Position', [1175 265 1210 295], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', cfg.plantSampleTime);

add_block('simulink/Signal Routing/Bus Selector', [model '/plant_info_selector'], ...
    'Position', [1770 135 1785 175], ...
    'OutputSignals', 'MtrPos');
add_block('simulink/Signal Routing/Demux', [model '/iabc_demux'], ...
    'Position', [1770 210 1775 290], ...
    'Outputs', '3');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ia_to_float'], ...
    'Position', [1825 220 1885 245], ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ib_to_float'], ...
    'Position', [1825 255 1885 280], ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ic_to_float'], ...
    'Position', [1825 290 1885 315], ...
    'OutDataTypeStr', cfg.currentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/wm_to_float'], ...
    'Position', [1825 335 1885 360], ...
    'OutDataTypeStr', cfg.speedTypeName);
add_block('simulink/Math Operations/Gain', [model '/theta_m_to_theta_e'], ...
    'Position', [1825 140 1890 170], ...
    'Gain', 'motor.pole_pairs', ...
    'OutDataTypeStr', cfg.angleTypeName);
add_block('simulink/Math Operations/Gain', [model '/theta_m_identity'], ...
    'Position', [1825 180 1890 210], ...
    'Gain', '1', ...
    'OutDataTypeStr', cfg.angleTypeName);

add_block('simulink/Signal Routing/Bus Creator', [model '/feedback_bus_creator'], ...
    'Position', [1960 140 1975 355], ...
    'Inputs', '6', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.plantFeedbackBusName, ...
    'NonVirtualBus', 'on');

add_line(model, 'DqToAbcDutyStep/1', 'phase_duty_selector/1', 'autorouting', 'on');
add_line(model, 'phase_duty_selector/1', 'phase_duty_mux/1', 'autorouting', 'on');
add_line(model, 'phase_duty_selector/2', 'phase_duty_mux/2', 'autorouting', 'on');
add_line(model, 'phase_duty_selector/3', 'phase_duty_mux/3', 'autorouting', 'on');
add_line(model, 'phase_duty_mux/1', 'PhaseDuty_RateTransition_25us/1', 'autorouting', 'on');
add_line(model, 'PhaseDuty_RateTransition_25us/1', 'Average Inverter/1', 'autorouting', 'on');
add_line(model, 'Vdc_plant/1', 'Vdc_RateTransition_25us/1', 'autorouting', 'on');
add_line(model, 'Vdc_RateTransition_25us/1', 'Average Inverter/2', 'autorouting', 'on');
add_line(model, 'LoadTorque/1', 'LoadTorque_to_double/1', 'autorouting', 'on');
add_line(model, 'LoadTorque_to_double/1', 'Surface Mount PMSM/1', 'autorouting', 'on');
add_line(model, 'Average Inverter/1', 'Vabc_to_double/1', 'autorouting', 'on');
add_line(model, 'Vabc_to_double/1', 'Surface Mount PMSM/2', 'autorouting', 'on');

add_line(model, 'Surface Mount PMSM/1', 'plant_info_selector/1', 'autorouting', 'on');
add_line(model, 'plant_info_selector/1', 'theta_m_to_theta_e/1', 'autorouting', 'on');
add_line(model, 'plant_info_selector/1', 'theta_m_identity/1', 'autorouting', 'on');
add_line(model, 'Surface Mount PMSM/2', 'iabc_demux/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/1', 'ia_to_float/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/2', 'ib_to_float/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/3', 'ic_to_float/1', 'autorouting', 'on');
add_line(model, 'Surface Mount PMSM/3', 'wm_to_float/1', 'autorouting', 'on');

name_line(add_line(model, 'ia_to_float/1', 'feedback_bus_creator/1', ...
    'autorouting', 'on'), 'ia');
name_line(add_line(model, 'ib_to_float/1', 'feedback_bus_creator/2', ...
    'autorouting', 'on'), 'ib');
name_line(add_line(model, 'ic_to_float/1', 'feedback_bus_creator/3', ...
    'autorouting', 'on'), 'ic');
name_line(add_line(model, 'wm_to_float/1', 'feedback_bus_creator/4', ...
    'autorouting', 'on'), 'wm');
name_line(add_line(model, 'theta_m_identity/1', 'feedback_bus_creator/5', ...
    'autorouting', 'on'), 'theta_m');
name_line(add_line(model, 'theta_m_to_theta_e/1', 'feedback_bus_creator/6', ...
    'autorouting', 'on'), 'theta_e');
end

function add_feedback_to_dq_adapter(model, cfg)
add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/feedback_for_control_selector'], ...
    'Position', [45 365 60 540], ...
    'OutputSignals', 'ia,ib,ic,wm,theta_e');

add_rate_transition(model, 'ia_feedback_rt_50us', [105 365 145 395], cfg);
add_rate_transition(model, 'ib_feedback_rt_50us', [105 405 145 435], cfg);
add_rate_transition(model, 'ic_feedback_rt_50us', [105 445 145 475], cfg);
add_rate_transition(model, 'wm_feedback_rt_50us', [105 485 145 515], cfg);
add_rate_transition(model, 'theta_e_feedback_rt_50us', [105 525 145 555], cfg);

add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/motor_measurement_bus_creator'], ...
    'Position', [215 365 230 555], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.motorInputBusName, ...
    'NonVirtualBus', 'on');

add_block('simulink/Signal Routing/Bus Selector', [model '/dq_current_selector'], ...
    'Position', [675 360 690 465], ...
    'OutputSignals', 'id,iq');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/id_meas_to_pi_type'], ...
    'Position', [730 365 805 395], ...
    'OutDataTypeStr', cfg.currentPiCurrentTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/iq_meas_to_pi_type'], ...
    'Position', [730 415 805 445], ...
    'OutDataTypeStr', cfg.currentPiCurrentTypeName);

add_block('simulink/Math Operations/Gain', [model '/omega_e_calc'], ...
    'Position', [215 595 285 625], ...
    'Gain', 'motor.pole_pairs', ...
    'OutDataTypeStr', cfg.currentPiSpeedTypeName);

add_line(model, 'feedback_bus_creator/1', 'feedback_for_control_selector/1', ...
    'autorouting', 'on');
add_line(model, 'feedback_for_control_selector/1', 'ia_feedback_rt_50us/1', ...
    'autorouting', 'on');
add_line(model, 'feedback_for_control_selector/2', 'ib_feedback_rt_50us/1', ...
    'autorouting', 'on');
add_line(model, 'feedback_for_control_selector/3', 'ic_feedback_rt_50us/1', ...
    'autorouting', 'on');
add_line(model, 'feedback_for_control_selector/4', 'wm_feedback_rt_50us/1', ...
    'autorouting', 'on');
add_line(model, 'feedback_for_control_selector/5', 'theta_e_feedback_rt_50us/1', ...
    'autorouting', 'on');

name_line(add_line(model, 'ia_feedback_rt_50us/1', ...
    'motor_measurement_bus_creator/1', 'autorouting', 'on'), 'ia');
name_line(add_line(model, 'ib_feedback_rt_50us/1', ...
    'motor_measurement_bus_creator/2', 'autorouting', 'on'), 'ib');
name_line(add_line(model, 'ic_feedback_rt_50us/1', ...
    'motor_measurement_bus_creator/3', 'autorouting', 'on'), 'ic');
name_line(add_line(model, 'theta_e_feedback_rt_50us/1', ...
    'motor_measurement_bus_creator/4', 'autorouting', 'on'), 'theta_e');
add_line(model, 'motor_measurement_bus_creator/1', ...
    'MotorClarkeParkStep/1', 'autorouting', 'on');
add_line(model, 'MotorClarkeParkStep/1', 'dq_current_selector/1', ...
    'autorouting', 'on');
add_line(model, 'dq_current_selector/1', 'id_meas_to_pi_type/1', ...
    'autorouting', 'on');
add_line(model, 'dq_current_selector/2', 'iq_meas_to_pi_type/1', ...
    'autorouting', 'on');
add_line(model, 'wm_feedback_rt_50us/1', 'omega_e_calc/1', 'autorouting', 'on');
end

function add_pi_input_adapter(model, cfg)
add_block('simulink/Signal Routing/Bus Creator', [model '/pi_input_bus_creator'], ...
    'Position', [300 80 315 305], ...
    'Inputs', '6', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.currentPiInputBusName, ...
    'NonVirtualBus', 'on');

name_line(add_line(model, 'id_ref_to_pi_type/1', ...
    'pi_input_bus_creator/1', 'autorouting', 'on'), 'id_ref');
name_line(add_line(model, 'iq_ref_zero/1', ...
    'pi_input_bus_creator/2', 'autorouting', 'on'), 'iq_ref');
name_line(add_line(model, 'id_meas_to_pi_type/1', ...
    'pi_input_bus_creator/3', 'autorouting', 'on'), 'id_meas');
name_line(add_line(model, 'iq_meas_to_pi_type/1', ...
    'pi_input_bus_creator/4', 'autorouting', 'on'), 'iq_meas');
name_line(add_line(model, 'omega_e_calc/1', ...
    'pi_input_bus_creator/5', 'autorouting', 'on'), 'omega_e');
name_line(add_line(model, 'vdc_ctrl/1', ...
    'pi_input_bus_creator/6', 'autorouting', 'on'), 'vdc');
end

function add_dq_voltage_to_duty_cmd_adapter(model, cfg)
add_block('simulink/Signal Routing/Bus Selector', [model '/pi_output_selector'], ...
    'Position', [675 125 690 230], ...
    'OutputSignals', 'vd_ref,vq_ref');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/vd_ref_to_motor_voltage'], ...
    'Position', [730 130 805 160], ...
    'OutDataTypeStr', cfg.voltageTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/vq_ref_to_motor_voltage'], ...
    'Position', [730 180 805 210], ...
    'OutDataTypeStr', cfg.voltageTypeName);

add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/dq_voltage_cmd_bus_creator'], ...
    'Position', [820 125 835 310], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.openLoopCmdBusName, ...
    'NonVirtualBus', 'on');

add_line(model, 'CurrentPiStep/1', 'pi_output_selector/1', 'autorouting', 'on');
add_line(model, 'pi_output_selector/1', 'vd_ref_to_motor_voltage/1', ...
    'autorouting', 'on');
add_line(model, 'pi_output_selector/2', 'vq_ref_to_motor_voltage/1', ...
    'autorouting', 'on');

name_line(add_line(model, 'vd_ref_to_motor_voltage/1', ...
    'dq_voltage_cmd_bus_creator/1', 'autorouting', 'on'), 'vd');
name_line(add_line(model, 'vq_ref_to_motor_voltage/1', ...
    'dq_voltage_cmd_bus_creator/2', 'autorouting', 'on'), 'vq');
name_line(add_line(model, 'theta_e_feedback_rt_50us/1', ...
    'dq_voltage_cmd_bus_creator/3', 'autorouting', 'on'), 'theta_e');
name_line(add_line(model, 'vdc_to_motor_voltage/1', ...
    'dq_voltage_cmd_bus_creator/4', 'autorouting', 'on'), 'vdc');
end

function connect_current_loop(model)
add_line(model, 'pi_input_bus_creator/1', 'CurrentPiStep/1', ...
    'autorouting', 'on');
add_line(model, 'dq_voltage_cmd_bus_creator/1', 'DqToAbcDutyStep/1', ...
    'autorouting', 'on');
end

function add_log_outputs(model)
add_scalar_logger(model, 'log_id_ref', [230 35 315 65], 'id_ref_to_pi_type/1');
add_scalar_logger(model, 'log_iq_ref', [230 645 315 675], 'iq_ref_zero/1');
add_scalar_logger(model, 'log_id_meas', [840 360 930 390], 'id_meas_to_pi_type/1');
add_scalar_logger(model, 'log_iq_meas', [840 410 930 440], 'iq_meas_to_pi_type/1');
add_scalar_logger(model, 'log_vd_ref', [730 75 820 105], 'pi_output_selector/1');
add_scalar_logger(model, 'log_vq_ref', [730 230 820 260], 'pi_output_selector/2');
add_scalar_logger(model, 'log_da', [1140 35 1220 65], 'phase_duty_selector/1');
add_scalar_logger(model, 'log_db', [1140 75 1220 105], 'phase_duty_selector/2');
add_scalar_logger(model, 'log_dc', [1140 245 1220 275], 'phase_duty_selector/3');
add_scalar_logger(model, 'log_wm', [1995 330 2075 360], 'wm_to_float/1');
add_scalar_logger(model, 'log_theta_e', [1995 370 2075 400], 'theta_m_to_theta_e/1');

add_block('simulink/Sinks/Scope', [model '/Current Loop Scope'], ...
    'Position', [960 360 1035 440], ...
    'NumInputPorts', '1');
add_block('simulink/Signal Routing/Mux', [model '/current_scope_mux'], ...
    'Position', [940 360 945 440], ...
    'Inputs', '3');
add_line(model, 'id_ref_to_pi_type/1', 'current_scope_mux/1', ...
    'autorouting', 'on');
add_line(model, 'id_meas_to_pi_type/1', 'current_scope_mux/2', ...
    'autorouting', 'on');
add_line(model, 'iq_meas_to_pi_type/1', 'current_scope_mux/3', ...
    'autorouting', 'on');
add_line(model, 'current_scope_mux/1', 'Current Loop Scope/1', ...
    'autorouting', 'on');
end

function add_rate_transition(model, block_name, position, cfg)
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/' block_name], ...
    'Position', position, ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', cfg.sampleTime);
end

function add_scalar_logger(model, variable_name, position, src_port)
add_block('simulink/Sinks/To Workspace', [model '/' variable_name], ...
    'Position', position, ...
    'VariableName', variable_name, ...
    'SaveFormat', 'Timeseries');
add_line(model, src_port, [variable_name '/1'], 'autorouting', 'on');
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
