%% Build visible green-joint 1615 MIT mode harness
%
% Output model:
%   green_joint_mit_mode_1615_harness.slx
%
% Scope:
%   TestSupervisor / MIT setpoint
%     -> green_joint_mit_impedance_model Model Reference
%     -> first-order current-loop approximation
%     -> 1615 output-side mechanical plant
%
% This harness is simulation-only. The MIT algorithm itself is not copied
% here; it is referenced from green_joint_mit_impedance_mbd.

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(script_dir);
mit_mbd_dir = fullfile(repo_dir, 'green_joint_mit_impedance_mbd');

previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

run(fullfile(script_dir, 'setup_green_joint_mit_mode_1615_harness.m'));

if ~strcmp(string(GJDT_MotorType), "1615")
    warning('This harness is named 1615 but GJDT_MOTOR_TYPE=%s.', ...
        string(GJDT_MotorType));
end

if ~contains(path, mit_mbd_dir)
    addpath(mit_mbd_dir);
end

mit_model = 'green_joint_mit_impedance_model';
mit_model_file = fullfile(mit_mbd_dir, [mit_model '.slx']);
mit_dictionary = fullfile(mit_mbd_dir, ...
    'green_joint_mit_impedance_interface.sldd');

if ~exist(mit_model_file, 'file') || ~exist(mit_dictionary, 'file')
    run(fullfile(mit_mbd_dir, 'build_green_joint_mit_impedance_model.m'));
    cd(script_dir);
    run(fullfile(script_dir, 'setup_green_joint_mit_mode_1615_harness.m'));
end

model = 'green_joint_mit_mode_1615_harness';
model_file = fullfile(script_dir, [model '.slx']);

if should_open_existing_model_from_desktop(model_file)
    load_system(model_file);
    open_system(model);
    fprintf(['MATLAB Desktop detected. Opened existing MIT harness ' ...
        'without rebuilding:\n  %s\n'], model_file);
    fprintf(['To rebuild safely, close the model and run from matlab -batch, ' ...
        'or set GJ_DT_ALLOW_UNSAFE_REBUILD=1.\n']);
    return;
end

assert_safe_rebuild_environment(model_file);

if bdIsLoaded(model)
    close_system(model, 0);
end

if exist(model_file, 'file')
    delete(model_file);
end

load_system(mit_model_file);

new_system(model);
set_param(model, ...
    'DataDictionary', 'green_joint_mit_impedance_interface.sldd', ...
    'StopTime', 'GJDT_MIT_StopTime_s', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'GJDT_Ts', ...
    'ParameterPrecisionLossMsg', 'none', ...
    'Description', ['Visible MIT 1615 harness. TestSupervisor and plant ', ...
    'are simulation-only; MIT algorithm is referenced from MBD core.']);

add_test_supervisor(model);
add_mit_input_adapter(model);
add_mit_controller(model, mit_model);
add_current_and_mechanical_plant(model);
add_logs_and_scopes(model);
connect_model(model);
add_model_annotations(model);

save_system(model, model_file);

fprintf('Built green-joint MIT mode 1615 harness:\n  %s\n', model_file);
fprintf('\nRun from MATLAB Desktop:\n');
fprintf('  run(''%s'')\n', fullfile(script_dir, ...
    'setup_green_joint_mit_mode_1615_harness.m'));
fprintf('  open_system(''%s'')\n', model_file);
fprintf('  sim(''%s'')\n', model);

function add_test_supervisor(model)
subsystem = [model '/TestSupervisor'];
add_clean_subsystem(subsystem, [40 95 205 285]);

add_block('simulink/Sources/Step', [subsystem '/pos_target_step'], ...
    'Position', [45 35 105 65], ...
    'Time', 'GJDT_MIT_PosStepTime_s', ...
    'Before', 'single(0)', ...
    'After', 'GJDT_MIT_PosTarget_Rad', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJMitAngle');
add_block('simulink/Sources/Constant', [subsystem '/vel_target'], ...
    'Position', [45 85 105 115], ...
    'Value', 'GJDT_MIT_VelTarget_RadS', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJMitSpeed');
add_block('simulink/Sources/Constant', [subsystem '/ff_torque'], ...
    'Position', [45 135 105 165], ...
    'Value', 'GJDT_MIT_FfTorque_Nm', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJMitTorque');
add_block('simulink/Sources/Constant', [subsystem '/mit_kp_current'], ...
    'Position', [45 185 105 215], ...
    'Value', 'GJDT_MIT_Kp_APerRad', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJMitGain');
add_block('simulink/Sources/Constant', [subsystem '/mit_kd_current'], ...
    'Position', [45 235 105 265], ...
    'Value', 'GJDT_MIT_Kd_APerRadS', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJMitGain');
add_block('simulink/Sources/Constant', [subsystem '/iq_limit'], ...
    'Position', [45 285 105 315], ...
    'Value', 'GJDT_MIT_IqLimit_A', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJMitCurrent');

out_names = {'pos_target_rad', 'vel_target_rad_s', 'ff_torque_nm', ...
    'mit_kp_a_per_rad', 'mit_kd_a_per_rad_s', 'iq_limit_a'};
for i = 1:numel(out_names)
    add_block('simulink/Sinks/Out1', [subsystem '/' out_names{i}], ...
        'Position', [205 25 + (i - 1) * 50 255 45 + (i - 1) * 50]);
end

add_line(subsystem, 'pos_target_step/1', 'pos_target_rad/1', ...
    'autorouting', 'on');
add_line(subsystem, 'vel_target/1', 'vel_target_rad_s/1', ...
    'autorouting', 'on');
add_line(subsystem, 'ff_torque/1', 'ff_torque_nm/1', 'autorouting', 'on');
add_line(subsystem, 'mit_kp_current/1', 'mit_kp_a_per_rad/1', ...
    'autorouting', 'on');
add_line(subsystem, 'mit_kd_current/1', 'mit_kd_a_per_rad_s/1', ...
    'autorouting', 'on');
add_line(subsystem, 'iq_limit/1', 'iq_limit_a/1', 'autorouting', 'on');
end

function add_mit_input_adapter(model)
add_block('simulink/Math Operations/Gain', [model '/kp_current_to_physical'], ...
    'Position', [275 225 365 255], ...
    'Gain', 'GJDT_MIT_KtOutput_NmPerA', ...
    'OutDataTypeStr', 'T_GJMitGain');
add_block('simulink/Math Operations/Gain', [model '/kd_current_to_physical'], ...
    'Position', [275 275 365 305], ...
    'Gain', 'GJDT_MIT_KtOutput_NmPerA', ...
    'OutDataTypeStr', 'T_GJMitGain');
add_block('simulink/Sources/Constant', [model '/torque_to_iq_gain'], ...
    'Position', [285 325 365 355], ...
    'Value', 'GJDT_MIT_TorqueToIq_APerNm', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJMitGain');

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/pos_feedback_to_mit_type'], ...
    'Position', [275 125 365 155], ...
    'OutDataTypeStr', 'T_GJMitAngle');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/vel_feedback_to_mit_type'], ...
    'Position', [275 175 365 205], ...
    'OutDataTypeStr', 'T_GJMitSpeed');

add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/mit_input_bus_creator'], ...
    'Position', [430 70 445 380], ...
    'Inputs', '9', ...
    'UseBusObject', 'on', ...
    'BusObject', 'green_joint_mit_input_t', ...
    'NonVirtualBus', 'on');
end

function add_mit_controller(model, mit_model)
add_block('simulink/Ports & Subsystems/Model', ...
    [model '/GreenJointMitImpedanceModelRef'], ...
    'Position', [525 180 745 250], ...
    'ModelName', mit_model);
add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/mit_output_selector'], ...
    'Position', [805 180 825 250], ...
    'OutputSignals', 'iq_ref_a');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/iq_ref_to_double'], ...
    'Position', [875 198 945 228], ...
    'OutDataTypeStr', 'double');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/pos_target_to_double'], ...
    'Position', [1670 35 1750 65], ...
    'OutDataTypeStr', 'double');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/joint_pos_to_double'], ...
    'Position', [1670 170 1750 200], ...
    'OutDataTypeStr', 'double');
end

function add_current_and_mechanical_plant(model)
% First-order current loop approximation.
add_block('simulink/Discrete/Unit Delay', [model '/iq_actual_state'], ...
    'Position', [1070 320 1135 350], ...
    'InitialCondition', '0', ...
    'SampleTime', 'GJDT_Ts');
add_block('simulink/Math Operations/Sum', [model '/iq_ref_minus_actual'], ...
    'Position', [995 205 1025 250], ...
    'Inputs', '+-');
add_block('simulink/Math Operations/Gain', [model '/current_alpha'], ...
    'Position', [1065 210 1145 240], ...
    'Gain', 'GJDT_MIT_CurrentAlpha');
add_block('simulink/Math Operations/Sum', [model '/iq_actual_next'], ...
    'Position', [1195 260 1225 305], ...
    'Inputs', '++');

% Output-side mechanics.
add_block('simulink/Discrete/Unit Delay', [model '/joint_vel_state'], ...
    'Position', [1505 440 1570 470], ...
    'InitialCondition', '0', ...
    'SampleTime', 'GJDT_Ts');
add_block('simulink/Discrete/Unit Delay', [model '/joint_pos_state'], ...
    'Position', [1505 110 1570 140], ...
    'InitialCondition', '0', ...
    'SampleTime', 'GJDT_Ts');

add_block('simulink/Math Operations/Gain', [model '/iq_to_output_torque'], ...
    'Position', [1280 260 1380 290], ...
    'Gain', 'GJDT_MIT_KtOutput_NmPerA');
add_block('simulink/Math Operations/Gain', [model '/viscous_friction'], ...
    'Position', [1030 455 1135 485], ...
    'Gain', 'GJDT_MIT_BOutput_NmSPerRad');
add_block('simulink/Math Operations/Gain', [model '/vel_over_smoothing'], ...
    'Position', [1030 515 1135 545], ...
    'Gain', '1 / GJDT_MIT_FrictionSmoothing_RadS');
add_block('simulink/Math Operations/Trigonometric Function', [model '/tanh_velocity'], ...
    'Position', [1185 515 1245 545], ...
    'Operator', 'tanh');
add_block('simulink/Math Operations/Gain', [model '/coulomb_friction'], ...
    'Position', [1295 515 1400 545], ...
    'Gain', 'GJDT_MIT_TcOutput_Nm');
add_block('simulink/Sources/Constant', [model '/torque_bias'], ...
    'Position', [1295 575 1400 605], ...
    'Value', 'GJDT_MIT_TbiasOutput_Nm', ...
    'SampleTime', 'GJDT_Ts');
add_block('simulink/Math Operations/Sum', [model '/friction_sum'], ...
    'Position', [1450 495 1480 560], ...
    'Inputs', '+++');
add_block('simulink/Math Operations/Sum', [model '/net_torque'], ...
    'Position', [1450 285 1480 330], ...
    'Inputs', '+-');
add_block('simulink/Math Operations/Gain', [model '/output_accel'], ...
    'Position', [1525 295 1625 325], ...
    'Gain', '1 / GJDT_MIT_JOutput_KgM2');
add_block('simulink/Math Operations/Gain', [model '/vel_delta'], ...
    'Position', [1665 295 1745 325], ...
    'Gain', 'GJDT_Ts');
add_block('simulink/Math Operations/Sum', [model '/joint_vel_next'], ...
    'Position', [1790 360 1820 405], ...
    'Inputs', '++');
add_block('simulink/Math Operations/Gain', [model '/pos_delta'], ...
    'Position', [1665 120 1745 150], ...
    'Gain', 'GJDT_Ts');
add_block('simulink/Math Operations/Sum', [model '/joint_pos_next'], ...
    'Position', [1790 110 1820 155], ...
    'Inputs', '++');
end

function add_logs_and_scopes(model)
log_specs = { ...
    'pos_target_log', 'gjdt_mit_pos_target', [1905 35 1995 65]; ...
    'joint_pos_log', 'gjdt_mit_joint_pos', [1905 110 1995 140]; ...
    'joint_vel_log', 'gjdt_mit_joint_vel', [1905 440 1995 470]; ...
    'iq_ref_log', 'gjdt_mit_iq_ref', [1030 120 1120 150]; ...
    'iq_actual_log', 'gjdt_mit_iq_actual', [1280 330 1370 360]; ...
    'net_torque_log', 'gjdt_mit_net_torque', [1525 235 1625 265]};

for i = 1:size(log_specs, 1)
    add_block('simulink/Sinks/To Workspace', [model '/' log_specs{i, 1}], ...
        'Position', log_specs{i, 3}, ...
        'VariableName', log_specs{i, 2}, ...
        'SaveFormat', 'Structure With Time');
end

add_block('simulink/Signal Routing/Mux', [model '/MIT_Response_Mux'], ...
    'Position', [1905 205 1910 285], ...
    'Inputs', '3');
add_block('simulink/Sinks/Scope', [model '/MIT_Response_Scope'], ...
    'Position', [1955 215 2015 275], ...
    'NumInputPorts', '1');

add_block('simulink/Signal Routing/Mux', [model '/MIT_Current_Mux'], ...
    'Position', [1280 120 1285 190], ...
    'Inputs', '2');
add_block('simulink/Sinks/Scope', [model '/MIT_Current_Scope'], ...
    'Position', [1335 125 1395 185], ...
    'NumInputPorts', '1');
end

function connect_model(model)
% TestSupervisor outputs.
name_line(add_line(model, 'TestSupervisor/1', 'mit_input_bus_creator/1', ...
    'autorouting', 'on'), 'pos_target_rad');
name_line(add_line(model, 'TestSupervisor/2', 'mit_input_bus_creator/3', ...
    'autorouting', 'on'), 'vel_target_rad_s');
name_line(add_line(model, 'TestSupervisor/3', 'mit_input_bus_creator/5', ...
    'autorouting', 'on'), 'ff_torque_nm');
add_line(model, 'TestSupervisor/4', 'kp_current_to_physical/1', ...
    'autorouting', 'on');
add_line(model, 'TestSupervisor/5', 'kd_current_to_physical/1', ...
    'autorouting', 'on');
name_line(add_line(model, 'TestSupervisor/6', 'mit_input_bus_creator/9', ...
    'autorouting', 'on'), 'iq_limit_a');

% Feedback into MIT bus.
add_line(model, 'joint_pos_state/1', 'pos_feedback_to_mit_type/1', ...
    'autorouting', 'on');
add_line(model, 'joint_vel_state/1', 'vel_feedback_to_mit_type/1', ...
    'autorouting', 'on');
name_line(add_line(model, 'pos_feedback_to_mit_type/1', ...
    'mit_input_bus_creator/2', 'autorouting', 'on'), 'pos_feedback_rad');
name_line(add_line(model, 'vel_feedback_to_mit_type/1', ...
    'mit_input_bus_creator/4', 'autorouting', 'on'), 'vel_feedback_rad_s');
name_line(add_line(model, 'kp_current_to_physical/1', ...
    'mit_input_bus_creator/6', 'autorouting', 'on'), 'kp_nm_per_rad');
name_line(add_line(model, 'kd_current_to_physical/1', ...
    'mit_input_bus_creator/7', 'autorouting', 'on'), 'kd_nm_s_per_rad');
name_line(add_line(model, 'torque_to_iq_gain/1', ...
    'mit_input_bus_creator/8', 'autorouting', 'on'), ...
    'torque_to_iq_gain_a_per_nm');

% MIT controller.
add_line(model, 'mit_input_bus_creator/1', ...
    'GreenJointMitImpedanceModelRef/1', 'autorouting', 'on');
add_line(model, 'GreenJointMitImpedanceModelRef/1', ...
    'mit_output_selector/1', 'autorouting', 'on');
add_line(model, 'mit_output_selector/1', 'iq_ref_to_double/1', ...
    'autorouting', 'on');

% Current loop approximation.
add_line(model, 'iq_ref_to_double/1', 'iq_ref_minus_actual/1', ...
    'autorouting', 'on');
add_line(model, 'iq_actual_state/1', 'iq_ref_minus_actual/2', ...
    'autorouting', 'on');
add_line(model, 'iq_ref_minus_actual/1', 'current_alpha/1', ...
    'autorouting', 'on');
add_line(model, 'current_alpha/1', 'iq_actual_next/1', 'autorouting', 'on');
add_line(model, 'iq_actual_state/1', 'iq_actual_next/2', 'autorouting', 'on');
add_line(model, 'iq_actual_next/1', 'iq_actual_state/1', 'autorouting', 'on');

% Mechanical plant.
add_line(model, 'iq_actual_state/1', 'iq_to_output_torque/1', ...
    'autorouting', 'on');
add_line(model, 'iq_to_output_torque/1', 'net_torque/1', 'autorouting', 'on');
add_line(model, 'joint_vel_state/1', 'viscous_friction/1', ...
    'autorouting', 'on');
add_line(model, 'joint_vel_state/1', 'vel_over_smoothing/1', ...
    'autorouting', 'on');
add_line(model, 'vel_over_smoothing/1', 'tanh_velocity/1', ...
    'autorouting', 'on');
add_line(model, 'tanh_velocity/1', 'coulomb_friction/1', ...
    'autorouting', 'on');
add_line(model, 'viscous_friction/1', 'friction_sum/1', ...
    'autorouting', 'on');
add_line(model, 'coulomb_friction/1', 'friction_sum/2', ...
    'autorouting', 'on');
add_line(model, 'torque_bias/1', 'friction_sum/3', 'autorouting', 'on');
add_line(model, 'friction_sum/1', 'net_torque/2', 'autorouting', 'on');
add_line(model, 'net_torque/1', 'output_accel/1', 'autorouting', 'on');
add_line(model, 'output_accel/1', 'vel_delta/1', 'autorouting', 'on');
add_line(model, 'vel_delta/1', 'joint_vel_next/1', 'autorouting', 'on');
add_line(model, 'joint_vel_state/1', 'joint_vel_next/2', ...
    'autorouting', 'on');
add_line(model, 'joint_vel_next/1', 'joint_vel_state/1', ...
    'autorouting', 'on');
add_line(model, 'joint_vel_next/1', 'pos_delta/1', 'autorouting', 'on');
add_line(model, 'pos_delta/1', 'joint_pos_next/1', 'autorouting', 'on');
add_line(model, 'joint_pos_state/1', 'joint_pos_next/2', ...
    'autorouting', 'on');
add_line(model, 'joint_pos_next/1', 'joint_pos_state/1', ...
    'autorouting', 'on');

% Logs and scopes.
add_line(model, 'TestSupervisor/1', 'pos_target_to_double/1', ...
    'autorouting', 'on');
add_line(model, 'joint_pos_state/1', 'joint_pos_to_double/1', ...
    'autorouting', 'on');
add_line(model, 'pos_target_to_double/1', 'pos_target_log/1', ...
    'autorouting', 'on');
add_line(model, 'joint_pos_to_double/1', 'joint_pos_log/1', ...
    'autorouting', 'on');
add_line(model, 'joint_vel_state/1', 'joint_vel_log/1', 'autorouting', 'on');
add_line(model, 'iq_ref_to_double/1', 'iq_ref_log/1', 'autorouting', 'on');
add_line(model, 'iq_actual_state/1', 'iq_actual_log/1', 'autorouting', 'on');
add_line(model, 'net_torque/1', 'net_torque_log/1', 'autorouting', 'on');

add_line(model, 'pos_target_to_double/1', 'MIT_Response_Mux/1', ...
    'autorouting', 'on');
add_line(model, 'joint_pos_to_double/1', 'MIT_Response_Mux/2', ...
    'autorouting', 'on');
add_line(model, 'joint_vel_state/1', 'MIT_Response_Mux/3', ...
    'autorouting', 'on');
add_line(model, 'MIT_Response_Mux/1', 'MIT_Response_Scope/1', ...
    'autorouting', 'on');

add_line(model, 'iq_ref_to_double/1', 'MIT_Current_Mux/1', ...
    'autorouting', 'on');
add_line(model, 'iq_actual_state/1', 'MIT_Current_Mux/2', ...
    'autorouting', 'on');
add_line(model, 'MIT_Current_Mux/1', 'MIT_Current_Scope/1', ...
    'autorouting', 'on');
end

function add_model_annotations(model)
Simulink.Annotation(model, sprintf(['MIT mode 1615 harness\\n', ...
    'Output-side position/speed/torque -> MIT MBD -> motor-side iq_ref\\n', ...
    'Current loop and mechanics here are simulation-only plant approximations.']));
end

function add_clean_subsystem(subsystem, position)
add_block('simulink/Ports & Subsystems/Subsystem', subsystem, ...
    'Position', position);
lines = find_system(subsystem, 'SearchDepth', 1, 'FindAll', 'on', ...
    'Type', 'line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(subsystem, 'SearchDepth', 1, 'Type', 'Block');
for i = 2:numel(blocks)
    delete_block(blocks{i});
end
end

function assert_safe_rebuild_environment(model_file)
if strcmp(getenv('GJ_DT_ALLOW_UNSAFE_REBUILD'), '1')
    return;
end
if usejava('desktop')
    error(['This script rebuilds a generated .slx file. Run it from ' ...
        'matlab -batch, or set GJ_DT_ALLOW_UNSAFE_REBUILD=1 only after ' ...
        'closing the model in MATLAB Desktop.']);
end
if ~exist(model_file, 'file')
    return;
end
[status, output] = system(sprintf('lsof -F pc -- %s 2>/dev/null', ...
    shell_quote(model_file)));
if status ~= 0 || strlength(strtrim(string(output))) == 0
    return;
end
current_pid = feature('getpid');
lines = splitlines(strtrim(string(output)));
pid = NaN;
command_name = "";
holders = strings(0, 1);
for i = 1:numel(lines)
    line = lines(i);
    if startsWith(line, "p")
        pid = str2double(extractAfter(line, 1));
    elseif startsWith(line, "c")
        command_name = extractAfter(line, 1);
    end
    if ~isnan(pid) && command_name ~= ""
        if pid ~= current_pid && contains(command_name, "MATLAB")
            holders(end + 1, 1) = sprintf('%s held by PID %d (%s)', ...
                model_file, pid, command_name); %#ok<AGROW>
        end
        pid = NaN;
        command_name = "";
    end
end
if ~isempty(holders)
    error(['Another MATLAB process appears to hold the MIT harness. ' ...
        'Close it before rebuilding.\n%s'], strjoin(holders, newline));
end
end

function result = should_open_existing_model_from_desktop(model_file)
result = false;
if strcmp(getenv('GJ_DT_ALLOW_UNSAFE_REBUILD'), '1')
    return;
end
if usejava('desktop') && exist(model_file, 'file')
    result = true;
end
end

function quoted = shell_quote(text)
quoted = ['''' strrep(text, '''', '''"''"''') ''''];
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
