%% Build green-joint current-loop digital twin v1 with average motor model
%
% This model uses the repository's average-voltage motor-model pattern:
%
%   green_joint_current_loop_model Model Reference
%     -> DqToAbcDutyStep
%     -> Average-Value Inverter
%     -> Surface Mount PMSM
%     -> MotorClarkeParkStep feedback
%
% The controller core remains the green-joint PI-only MBD model reference.
% The inverter and PMSM are simulation plant blocks, not generated controller
% code.

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(script_dir);

green_joint_mbd_dir = fullfile(repo_dir, 'green_joint_current_loop_mbd');
speed_mbd_dir = fullfile(repo_dir, 'motor_speed_pi_mbd');
speed_estimator_mbd_dir = fullfile(repo_dir, 'motor_speed_estimator_mbd');
motor_float_dir = fullfile(repo_dir, 'motor_float_open_loop_mbd');
clarke_park_dir = fullfile(repo_dir, 'motor_clarke_park_struct');

previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);
run(fullfile(script_dir, 'setup_green_joint_current_loop_twin.m'));
addpath(speed_mbd_dir);
addpath(speed_estimator_mbd_dir);
addpath(motor_float_dir);
addpath(clarke_park_dir);

model = 'green_joint_average_motor_twin_model';
model_file = fullfile(script_dir, [model '.slx']);

if should_open_existing_model_from_desktop(model_file)
    load_system(model_file);
    open_system(model);
    fprintf(['MATLAB Desktop detected. Opened existing average motor twin ' ...
        'without rebuilding:\n  %s\n'], model_file);
    return;
end

assert_safe_rebuild_environment(script_dir, model_file);
ensure_source_models(green_joint_mbd_dir, speed_mbd_dir, ...
    speed_estimator_mbd_dir, motor_float_dir, clarke_park_dir);
create_average_motor_twin_dictionary(script_dir);

source_green_joint_model = 'green_joint_current_loop_model';
source_speed_model = 'speed_pi_model';
source_speed_estimator_model = 'speed_estimator_pll_model';
source_float_model = 'motor_float_open_loop_model';
source_clarke_park_model = 'motor_clarke_park_model';

if bdIsLoaded(model)
    close_system(model, 0);
end

if exist(model_file, 'file')
    delete(model_file);
end

load_system(fullfile(green_joint_mbd_dir, [source_green_joint_model '.slx']));
load_system(fullfile(speed_mbd_dir, [source_speed_model '.slx']));
load_system(fullfile(speed_estimator_mbd_dir, ...
    [source_speed_estimator_model '.slx']));
load_system(fullfile(motor_float_dir, [source_float_model '.slx']));
load_system(fullfile(clarke_park_dir, [source_clarke_park_model '.slx']));
load_system('mcbplantlib');
load_system('mcblib');

cleanup_sources = onCleanup(@() close_source_models({ ...
    source_green_joint_model, source_speed_model, ...
    source_speed_estimator_model, source_float_model, ...
    source_clarke_park_model}));

new_system(model);
set_param(model, ...
    'DataDictionary', 'green_joint_average_motor_twin_interface.sldd', ...
    'StopTime', 'GJDT_StopTime', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'GJDT_TsPlant', ...
    'ParameterPrecisionLossMsg', 'none');

add_reference_sources(model);
add_referenced_controller_and_reuse_blocks(model, source_green_joint_model, ...
    source_speed_model, source_speed_estimator_model, source_float_model, ...
    source_clarke_park_model);
add_green_joint_output_adapter(model);
add_average_inverter_and_pmsm(model);
add_feedback_path(model);
add_logs(model);
connect_model(model);

save_system(model, model_file);

fprintf('Built green-joint average motor digital twin model:\n  %s\n', ...
    model_file);

function add_reference_sources(model)
add_block('simulink/Sources/Constant', [model '/id_ref'], ...
    'Position', [45 65 105 95], ...
    'Value', 'GJDT_IdRef_A', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJCurrent');

add_block('simulink/Sources/Step', [model '/iq_ref_step'], ...
    'Position', [45 120 105 150], ...
    'Time', 'GJDT_IqStepTime_s', ...
    'Before', 'GJDT_IqBefore_A', ...
    'After', 'GJDT_IqAfter_A', ...
    'SampleTime', 'GJDT_Ts');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/iq_ref_to_current'], ...
    'Position', [130 120 205 150], ...
    'OutDataTypeStr', 'T_GJCurrent');

add_block('simulink/Sources/Step', [model '/joint_speed_ref_step'], ...
    'Position', [45 185 105 215], ...
    'Time', 'GJDT_SpeedRefStepTime_s', ...
    'Before', 'GJDT_SpeedRefBefore_rad_s', ...
    'After', 'GJDT_SpeedRefAfter_rad_s', ...
    'SampleTime', 'GJDT_TsSpeed');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/speed_ref_to_speed_pi'], ...
    'Position', [130 185 205 215], ...
    'OutDataTypeStr', 'T_SpeedPiSpeed');

add_block('simulink/Sources/Constant', [model '/speed_iq_limit'], ...
    'Position', [45 235 105 265], ...
    'Value', 'GJDT_SpeedIqLimit_A', ...
    'SampleTime', 'GJDT_TsSpeed', ...
    'OutDataTypeStr', 'T_SpeedPiCurrent');

add_block('simulink/Sources/Constant', [model '/use_speed_loop'], ...
    'Position', [210 215 270 245], ...
    'Value', 'GJDT_UseSpeedLoop', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'boolean');

add_block('simulink/Sources/Constant', [model '/speed_estimator_reset'], ...
    'Position', [1995 155 2055 185], ...
    'Value', 'uint8(0)', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_SpeedEstimatorReset');

add_block('simulink/Sources/Constant', [model '/vbus_ctrl'], ...
    'Position', [45 280 105 310], ...
    'Value', 'GJDT_Vbus_V', ...
    'SampleTime', 'GJDT_Ts', ...
    'OutDataTypeStr', 'T_GJVoltage');

add_block('simulink/Sources/Constant', [model '/Vdc_plant'], ...
    'Position', [1115 280 1175 310], ...
    'Value', 'GJDT_Vbus_V', ...
    'SampleTime', 'GJDT_TsPlant', ...
    'OutDataTypeStr', 'T_GJVoltage');

add_block('simulink/Sources/Constant', [model '/LoadTorque'], ...
    'Position', [1115 555 1185 585], ...
    'Value', 'inverter.load_torque', ...
    'SampleTime', 'GJDT_TsPlant', ...
    'OutDataTypeStr', 'double');

add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/loop_input_bus_creator'], ...
    'Position', [300 65 315 315], ...
    'Inputs', '5', ...
    'UseBusObject', 'on', ...
    'BusObject', 'green_joint_current_loop_input_t', ...
    'NonVirtualBus', 'on');

add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/speed_input_bus_creator'], ...
    'Position', [300 180 315 285], ...
    'Inputs', '3', ...
    'UseBusObject', 'on', ...
    'BusObject', 'speed_pi_input_t', ...
    'NonVirtualBus', 'on');
end

function add_referenced_controller_and_reuse_blocks(model, source_green_joint_model, ...
        source_speed_model, source_speed_estimator_model, source_float_model, ...
        source_clarke_park_model)
add_block('simulink/Ports & Subsystems/Model', ...
    [model '/SpeedPiModelRef'], ...
    'Position', [390 255 610 335], ...
    'ModelName', source_speed_model);

add_block('simulink/Ports & Subsystems/Model', ...
    [model '/SpeedEstimatorPllModelRef'], ...
    'Position', [2140 95 2360 175], ...
    'ModelName', source_speed_estimator_model);

add_block('simulink/Ports & Subsystems/Model', ...
    [model '/GreenJointCurrentLoopModelRef'], ...
    'Position', [390 130 610 230], ...
    'ModelName', source_green_joint_model);

add_block([source_float_model '/DqToAbcDutyStep'], ...
    [model '/DqToAbcDutyStep'], ...
    'Position', [850 125 1065 235]);

add_block([source_clarke_park_model '/MotorClarkeParkStep'], ...
    [model '/MotorClarkeParkStep'], ...
    'Position', [400 475 615 580]);
end

function add_green_joint_output_adapter(model)
add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/loop_output_selector'], ...
    'Position', [660 85 680 285], ...
    'OutputSignals', 'vd_cmd,vq_cmd,voltage_mag,vd_norm,vq_norm,voltage_mag_norm');

add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/speed_output_selector'], ...
    'Position', [660 300 680 350], ...
    'OutputSignals', 'iq_ref');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/SpeedIqRef_RateTransition_50us'], ...
    'Position', [705 315 750 345], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_Ts');
add_block('simulink/Signal Routing/Switch', [model '/iq_ref_source_switch'], ...
    'Position', [250 115 290 165], ...
    'Criteria', 'u2 ~= 0', ...
    'Threshold', '0.5');

add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/dq_voltage_cmd_bus_creator'], ...
    'Position', [745 125 760 310], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', 'open_loop_cmd_t', ...
    'NonVirtualBus', 'on');

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/vd_cmd_to_motor_voltage'], ...
    'Position', [700 125 735 155], ...
    'OutDataTypeStr', 'T_MotorVoltage');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/vq_cmd_to_motor_voltage'], ...
    'Position', [700 175 735 205], ...
    'OutDataTypeStr', 'T_MotorVoltage');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/vbus_to_motor_voltage'], ...
    'Position', [700 270 735 300], ...
    'OutDataTypeStr', 'T_MotorVoltage');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/theta_e_to_motor_angle'], ...
    'Position', [710 335 745 365], ...
    'OutDataTypeStr', 'T_MotorAngle');

add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/ThetaE_RateTransition_50us'], ...
    'Position', [660 335 695 365], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_Ts');
end

function add_average_inverter_and_pmsm(model)
add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/phase_duty_selector'], ...
    'Position', [1095 125 1110 235], ...
    'OutputSignals', 'da,db,dc');
add_block('simulink/Signal Routing/Mux', [model '/phase_duty_mux'], ...
    'Position', [1140 145 1145 225], ...
    'Inputs', '3');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/PhaseDuty_RateTransition_25us'], ...
    'Position', [1175 165 1210 205], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_TsPlant');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/Vdc_RateTransition_25us'], ...
    'Position', [1200 280 1240 310], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_TsPlant');

add_block('mcbplantlib/Average-Value Inverter', [model '/Average Inverter'], ...
    'Position', [1265 125 1445 230]);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/Vabc_to_double'], ...
    'Position', [1475 170 1525 210], ...
    'OutDataTypeStr', 'double');
add_block('mcblib/Electrical Systems/Motors/Surface Mount PMSM', ...
    [model '/Surface Mount PMSM'], ...
    'Position', [1560 160 1770 320]);
set_param([model '/Surface Mount PMSM'], ...
    'port_config', 'Torque', ...
    'sim_type', 'Discrete', ...
    'Ts', 'GJDT_TsPlant', ...
    'P', 'motor.pole_pairs', ...
    'Rs', 'motor.Rs', ...
    'Ldq_', 'motor.Ld', ...
    'lambda_pm', 'motor.psi_f', ...
    'mechanical', '[motor.J, motor.B, 0]', ...
    'idq0', '[0 0]', ...
    'theta_init', '0', ...
    'omega_init', '0');
end

function add_feedback_path(model)
add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/plant_info_selector'], ...
    'Position', [1815 130 1830 180], ...
    'OutputSignals', 'MtrPos');
add_block('simulink/Signal Routing/Demux', [model '/iabc_demux'], ...
    'Position', [1815 215 1820 295], ...
    'Outputs', '3');

add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/MotorAngle_RateTransition_50us'], ...
    'Position', [1870 95 1940 125], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_Ts');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/motor_angle_to_speed_estimator_angle'], ...
    'Position', [1975 95 2050 125], ...
    'OutDataTypeStr', 'T_SpeedEstimatorAngle');
add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/speed_estimator_input_bus_creator'], ...
    'Position', [2085 95 2100 185], ...
    'Inputs', '2', ...
    'UseBusObject', 'on', ...
    'BusObject', 'speed_estimator_input_t', ...
    'NonVirtualBus', 'on');
add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/speed_estimator_output_selector'], ...
    'Position', [2400 90 2420 210], ...
    'OutputSignals', ...
    'joint_speed_est_rad_s,motor_speed_mech_rad_s,motor_speed_elec_rad_s,theta_hat_rad');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/joint_speed_est_to_speed_pi'], ...
    'Position', [2445 90 2520 120], ...
    'OutDataTypeStr', 'T_SpeedPiSpeed');

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ia_to_current'], ...
    'Position', [1870 220 1940 245], ...
    'OutDataTypeStr', 'T_GJCurrent');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ib_to_current'], ...
    'Position', [1870 255 1940 280], ...
    'OutDataTypeStr', 'T_GJCurrent');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ic_to_current'], ...
    'Position', [1870 290 1940 315], ...
    'OutDataTypeStr', 'T_GJCurrent');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ia_to_motor_current'], ...
    'Position', [105 455 140 485], ...
    'OutDataTypeStr', 'T_MotorCurrent');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ib_to_motor_current'], ...
    'Position', [105 495 140 525], ...
    'OutDataTypeStr', 'T_MotorCurrent');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/ic_to_motor_current'], ...
    'Position', [105 535 140 565], ...
    'OutDataTypeStr', 'T_MotorCurrent');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/theta_e_to_motor_angle_feedback'], ...
    'Position', [105 580 140 610], ...
    'OutDataTypeStr', 'T_MotorAngle');
add_block('simulink/Math Operations/Gain', [model '/theta_m_to_theta_e'], ...
    'Position', [1870 140 1940 170], ...
    'Gain', 'motor.pole_pairs', ...
    'OutDataTypeStr', 'T_GJFloat');
add_block('simulink/Math Operations/Gain', [model '/wm_to_float'], ...
    'Position', [1870 335 1940 365], ...
    'Gain', '1', ...
    'OutDataTypeStr', 'T_GJFloat');
add_block('simulink/Math Operations/Gain', [model '/motor_speed_to_joint_speed'], ...
    'Position', [1870 380 1940 410], ...
    'Gain', '1 / motor.gear_ratio', ...
    'OutDataTypeStr', 'T_SpeedPiSpeed');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/JointSpeed_RateTransition_TsSpeed'], ...
    'Position', [1980 380 2025 410], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_TsSpeed');

add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/ia_feedback_rt_50us'], ...
    'Position', [45 455 90 485], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_Ts');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/ib_feedback_rt_50us'], ...
    'Position', [45 495 90 525], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_Ts');
add_block('simulink/Signal Attributes/Rate Transition', ...
    [model '/ic_feedback_rt_50us'], ...
    'Position', [45 535 90 565], ...
    'Integrity', 'on', ...
    'Deterministic', 'on', ...
    'OutPortSampleTimeOpt', 'Specify', ...
    'OutPortSampleTime', 'GJDT_Ts');

add_block('simulink/Signal Routing/Bus Creator', ...
    [model '/motor_measurement_bus_creator'], ...
    'Position', [180 455 195 610], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', 'motor_t', ...
    'NonVirtualBus', 'on');

add_block('simulink/Signal Routing/Bus Selector', ...
    [model '/dq_current_selector'], ...
    'Position', [650 475 670 580], ...
    'OutputSignals', 'id,iq');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/id_to_gj_current'], ...
    'Position', [715 475 790 505], ...
    'OutDataTypeStr', 'T_GJCurrent');
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [model '/iq_to_gj_current'], ...
    'Position', [715 525 790 555], ...
    'OutDataTypeStr', 'T_GJCurrent');
end

function add_logs(model)
log_specs = { ...
    'iq_ref_log', 'gjavg_iq_ref', [1535 90 1610 120]; ...
    'speed_ref_log', 'gjavg_speed_ref', [1535 130 1610 160]; ...
    'id_log', 'gjavg_id', [835 475 910 505]; ...
    'iq_log', 'gjavg_iq', [835 525 910 555]; ...
    'vd_log', 'gjavg_vd', [690 35 765 65]; ...
    'vq_log', 'gjavg_vq', [690 245 765 275]; ...
    'voltage_mag_norm_log', 'gjavg_voltage_mag_norm', [690 285 765 315]; ...
    'wm_log', 'gjavg_wm', [1985 335 2060 365]; ...
    'joint_speed_log', 'gjavg_joint_speed', [2065 380 2145 410]};
log_specs = [log_specs; { ...
    'joint_speed_ideal_log', 'gjavg_joint_speed_ideal', [1985 425 2085 455]; ...
    'speed_est_motor_log', 'gjavg_speed_est_motor', [2460 125 2560 155]; ...
    'speed_est_elec_log', 'gjavg_speed_est_elec', [2460 165 2560 195]; ...
    'speed_est_theta_hat_log', 'gjavg_speed_est_theta_hat', [2460 205 2560 235]}];

for i = 1:size(log_specs, 1)
    add_block('simulink/Sinks/To Workspace', [model '/' log_specs{i, 1}], ...
        'Position', log_specs{i, 3}, ...
        'VariableName', log_specs{i, 2}, ...
        'SaveFormat', 'Structure With Time');
end
end

function connect_model(model)
name_line(add_line(model, 'id_ref/1', 'loop_input_bus_creator/1', ...
    'autorouting', 'on'), 'id_ref');
add_line(model, 'iq_ref_step/1', 'iq_ref_to_current/1', 'autorouting', 'on');
add_line(model, 'joint_speed_ref_step/1', ...
    'speed_ref_to_speed_pi/1', 'autorouting', 'on');
name_line(add_line(model, 'speed_ref_to_speed_pi/1', ...
    'speed_input_bus_creator/1', 'autorouting', 'on'), 'wm_ref');
name_line(add_line(model, 'JointSpeed_RateTransition_TsSpeed/1', ...
    'speed_input_bus_creator/2', 'autorouting', 'on'), 'wm_meas');
name_line(add_line(model, 'speed_iq_limit/1', ...
    'speed_input_bus_creator/3', 'autorouting', 'on'), 'iq_limit');
add_line(model, 'speed_input_bus_creator/1', 'SpeedPiModelRef/1', ...
    'autorouting', 'on');
add_line(model, 'SpeedPiModelRef/1', 'speed_output_selector/1', ...
    'autorouting', 'on');
add_line(model, 'speed_output_selector/1', ...
    'SpeedIqRef_RateTransition_50us/1', 'autorouting', 'on');
add_line(model, 'SpeedIqRef_RateTransition_50us/1', ...
    'iq_ref_source_switch/1', 'autorouting', 'on');
add_line(model, 'use_speed_loop/1', ...
    'iq_ref_source_switch/2', 'autorouting', 'on');
add_line(model, 'iq_ref_to_current/1', ...
    'iq_ref_source_switch/3', 'autorouting', 'on');
name_line(add_line(model, 'iq_ref_source_switch/1', ...
    'loop_input_bus_creator/2', 'autorouting', 'on'), 'iq_ref');
name_line(add_line(model, 'id_to_gj_current/1', ...
    'loop_input_bus_creator/3', 'autorouting', 'on'), 'id_fbk');
name_line(add_line(model, 'iq_to_gj_current/1', ...
    'loop_input_bus_creator/4', 'autorouting', 'on'), 'iq_fbk');
name_line(add_line(model, 'vbus_ctrl/1', ...
    'loop_input_bus_creator/5', 'autorouting', 'on'), 'vbus');

add_line(model, 'loop_input_bus_creator/1', ...
    'GreenJointCurrentLoopModelRef/1', 'autorouting', 'on');
add_line(model, 'GreenJointCurrentLoopModelRef/1', ...
    'loop_output_selector/1', 'autorouting', 'on');

add_line(model, 'loop_output_selector/1', 'vd_cmd_to_motor_voltage/1', ...
    'autorouting', 'on');
add_line(model, 'loop_output_selector/2', 'vq_cmd_to_motor_voltage/1', ...
    'autorouting', 'on');
add_line(model, 'vbus_ctrl/1', 'vbus_to_motor_voltage/1', ...
    'autorouting', 'on');
add_line(model, 'ThetaE_RateTransition_50us/1', ...
    'theta_e_to_motor_angle/1', 'autorouting', 'on');

name_line(add_line(model, 'vd_cmd_to_motor_voltage/1', ...
    'dq_voltage_cmd_bus_creator/1', 'autorouting', 'on'), 'vd');
name_line(add_line(model, 'vq_cmd_to_motor_voltage/1', ...
    'dq_voltage_cmd_bus_creator/2', 'autorouting', 'on'), 'vq');
name_line(add_line(model, 'theta_e_to_motor_angle/1', ...
    'dq_voltage_cmd_bus_creator/3', 'autorouting', 'on'), 'theta_e');
name_line(add_line(model, 'vbus_to_motor_voltage/1', ...
    'dq_voltage_cmd_bus_creator/4', 'autorouting', 'on'), 'vdc');
add_line(model, 'dq_voltage_cmd_bus_creator/1', ...
    'DqToAbcDutyStep/1', 'autorouting', 'on');

add_line(model, 'DqToAbcDutyStep/1', 'phase_duty_selector/1', ...
    'autorouting', 'on');
add_line(model, 'phase_duty_selector/1', 'phase_duty_mux/1', ...
    'autorouting', 'on');
add_line(model, 'phase_duty_selector/2', 'phase_duty_mux/2', ...
    'autorouting', 'on');
add_line(model, 'phase_duty_selector/3', 'phase_duty_mux/3', ...
    'autorouting', 'on');
add_line(model, 'phase_duty_mux/1', ...
    'PhaseDuty_RateTransition_25us/1', 'autorouting', 'on');
add_line(model, 'PhaseDuty_RateTransition_25us/1', ...
    'Average Inverter/1', 'autorouting', 'on');
add_line(model, 'Vdc_plant/1', 'Vdc_RateTransition_25us/1', ...
    'autorouting', 'on');
add_line(model, 'Vdc_RateTransition_25us/1', ...
    'Average Inverter/2', 'autorouting', 'on');
add_line(model, 'Average Inverter/1', 'Vabc_to_double/1', ...
    'autorouting', 'on');
add_line(model, 'Vabc_to_double/1', 'Surface Mount PMSM/2', ...
    'autorouting', 'on');
add_line(model, 'LoadTorque/1', 'Surface Mount PMSM/1', ...
    'autorouting', 'on');

add_line(model, 'Surface Mount PMSM/1', 'plant_info_selector/1', ...
    'autorouting', 'on');
add_line(model, 'plant_info_selector/1', 'theta_m_to_theta_e/1', ...
    'autorouting', 'on');
add_line(model, 'plant_info_selector/1', ...
    'MotorAngle_RateTransition_50us/1', 'autorouting', 'on');
add_line(model, 'MotorAngle_RateTransition_50us/1', ...
    'motor_angle_to_speed_estimator_angle/1', 'autorouting', 'on');
name_line(add_line(model, 'motor_angle_to_speed_estimator_angle/1', ...
    'speed_estimator_input_bus_creator/1', 'autorouting', 'on'), ...
    'motor_angle_rad');
name_line(add_line(model, 'speed_estimator_reset/1', ...
    'speed_estimator_input_bus_creator/2', 'autorouting', 'on'), ...
    'reset');
add_line(model, 'speed_estimator_input_bus_creator/1', ...
    'SpeedEstimatorPllModelRef/1', 'autorouting', 'on');
add_line(model, 'SpeedEstimatorPllModelRef/1', ...
    'speed_estimator_output_selector/1', 'autorouting', 'on');
add_line(model, 'speed_estimator_output_selector/1', ...
    'joint_speed_est_to_speed_pi/1', 'autorouting', 'on');
add_line(model, 'joint_speed_est_to_speed_pi/1', ...
    'JointSpeed_RateTransition_TsSpeed/1', 'autorouting', 'on');
add_line(model, 'theta_m_to_theta_e/1', 'ThetaE_RateTransition_50us/1', ...
    'autorouting', 'on');
add_line(model, 'Surface Mount PMSM/2', 'iabc_demux/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/1', 'ia_to_current/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/2', 'ib_to_current/1', 'autorouting', 'on');
add_line(model, 'iabc_demux/3', 'ic_to_current/1', 'autorouting', 'on');
add_line(model, 'ia_to_current/1', 'ia_feedback_rt_50us/1', ...
    'autorouting', 'on');
add_line(model, 'ib_to_current/1', 'ib_feedback_rt_50us/1', ...
    'autorouting', 'on');
add_line(model, 'ic_to_current/1', 'ic_feedback_rt_50us/1', ...
    'autorouting', 'on');
add_line(model, 'ia_feedback_rt_50us/1', 'ia_to_motor_current/1', ...
    'autorouting', 'on');
add_line(model, 'ib_feedback_rt_50us/1', 'ib_to_motor_current/1', ...
    'autorouting', 'on');
add_line(model, 'ic_feedback_rt_50us/1', 'ic_to_motor_current/1', ...
    'autorouting', 'on');
add_line(model, 'ThetaE_RateTransition_50us/1', ...
    'theta_e_to_motor_angle_feedback/1', 'autorouting', 'on');

name_line(add_line(model, 'ia_to_motor_current/1', ...
    'motor_measurement_bus_creator/1', 'autorouting', 'on'), 'ia');
name_line(add_line(model, 'ib_to_motor_current/1', ...
    'motor_measurement_bus_creator/2', 'autorouting', 'on'), 'ib');
name_line(add_line(model, 'ic_to_motor_current/1', ...
    'motor_measurement_bus_creator/3', 'autorouting', 'on'), 'ic');
name_line(add_line(model, 'theta_e_to_motor_angle_feedback/1', ...
    'motor_measurement_bus_creator/4', 'autorouting', 'on'), 'theta_e');
add_line(model, 'motor_measurement_bus_creator/1', ...
    'MotorClarkeParkStep/1', 'autorouting', 'on');
add_line(model, 'MotorClarkeParkStep/1', 'dq_current_selector/1', ...
    'autorouting', 'on');
add_line(model, 'dq_current_selector/1', 'id_to_gj_current/1', ...
    'autorouting', 'on');
add_line(model, 'dq_current_selector/2', 'iq_to_gj_current/1', ...
    'autorouting', 'on');

add_line(model, 'iq_ref_source_switch/1', 'iq_ref_log/1', 'autorouting', 'on');
add_line(model, 'id_to_gj_current/1', 'id_log/1', 'autorouting', 'on');
add_line(model, 'iq_to_gj_current/1', 'iq_log/1', 'autorouting', 'on');
add_line(model, 'loop_output_selector/1', 'vd_log/1', 'autorouting', 'on');
add_line(model, 'loop_output_selector/2', 'vq_log/1', 'autorouting', 'on');
add_line(model, 'loop_output_selector/6', 'voltage_mag_norm_log/1', ...
    'autorouting', 'on');
add_line(model, 'Surface Mount PMSM/3', 'wm_to_float/1', 'autorouting', 'on');
add_line(model, 'Surface Mount PMSM/3', 'motor_speed_to_joint_speed/1', ...
    'autorouting', 'on');
add_line(model, 'wm_to_float/1', 'wm_log/1', 'autorouting', 'on');
add_line(model, 'JointSpeed_RateTransition_TsSpeed/1', ...
    'joint_speed_log/1', 'autorouting', 'on');
add_line(model, 'motor_speed_to_joint_speed/1', ...
    'joint_speed_ideal_log/1', 'autorouting', 'on');
add_line(model, 'speed_estimator_output_selector/2', ...
    'speed_est_motor_log/1', 'autorouting', 'on');
add_line(model, 'speed_estimator_output_selector/3', ...
    'speed_est_elec_log/1', 'autorouting', 'on');
add_line(model, 'speed_estimator_output_selector/4', ...
    'speed_est_theta_hat_log/1', 'autorouting', 'on');
add_line(model, 'speed_ref_to_speed_pi/1', 'speed_ref_log/1', ...
    'autorouting', 'on');
end

function ensure_source_models(green_joint_mbd_dir, speed_mbd_dir, ...
        speed_estimator_mbd_dir, motor_float_dir, clarke_park_dir)
source_specs = { ...
    fullfile(green_joint_mbd_dir, 'green_joint_current_loop_model.slx'), ...
    fullfile(green_joint_mbd_dir, 'build_green_joint_current_loop_model.m'); ...
    fullfile(speed_mbd_dir, 'speed_pi_model.slx'), ...
    fullfile(speed_mbd_dir, 'build_speed_pi_model.m'); ...
    fullfile(speed_estimator_mbd_dir, 'speed_estimator_pll_model.slx'), ...
    fullfile(speed_estimator_mbd_dir, 'build_speed_estimator_pll_model.m'); ...
    fullfile(motor_float_dir, 'motor_float_open_loop_model.slx'), ...
    fullfile(motor_float_dir, 'build_motor_float_open_loop_model.m'); ...
    fullfile(clarke_park_dir, 'motor_clarke_park_model.slx'), ...
    fullfile(clarke_park_dir, 'build_motor_clarke_park_model.m')};

for i = 1:size(source_specs, 1)
    if ~exist(source_specs{i, 1}, 'file')
        run(source_specs{i, 2});
    end
end
end

function create_average_motor_twin_dictionary(script_dir)
dictionary_file = fullfile(script_dir, ...
    'green_joint_average_motor_twin_interface.sldd');

try
    Simulink.data.dictionary.closeAll('-discard');
catch
end

if exist(dictionary_file, 'file')
    delete(dictionary_file);
end

dd = Simulink.data.dictionary.create(dictionary_file);
cleanup_dd = onCleanup(@() close(dd));
addDataSource(dd, 'green_joint_current_loop_interface.sldd');
addDataSource(dd, 'speed_pi_interface.sldd');
addDataSource(dd, 'speed_estimator_pll_interface.sldd');
design_data = getSection(dd, 'Design Data');

type_header = 'green_joint_average_motor_twin_types.h';

upsert_alias_type(design_data, 'T_MotorFloat', 'single', type_header);
upsert_alias_type(design_data, 'T_MotorVoltage', 'single', type_header);
upsert_alias_type(design_data, 'T_MotorAngle', 'single', type_header);
upsert_alias_type(design_data, 'T_MotorCurrent', 'single', type_header);
upsert_alias_type(design_data, 'T_MotorSpeed', 'single', type_header);
upsert_alias_type(design_data, 'T_MotorTorque', 'single', type_header);
upsert_alias_type(design_data, 'T_DutyRatio', 'single', type_header);

upsert_bus_type(design_data, 'motor_t', type_header, { ...
    {'ia', 'T_MotorCurrent'}; ...
    {'ib', 'T_MotorCurrent'}; ...
    {'ic', 'T_MotorCurrent'}; ...
    {'theta_e', 'T_MotorAngle'}});

upsert_bus_type(design_data, 'motor_dq_t', type_header, { ...
    {'i_alpha', 'T_MotorCurrent'}; ...
    {'i_beta', 'T_MotorCurrent'}; ...
    {'id', 'T_MotorCurrent'}; ...
    {'iq', 'T_MotorCurrent'}});

upsert_bus_type(design_data, 'open_loop_cmd_t', type_header, { ...
    {'vd', 'T_MotorVoltage'}; ...
    {'vq', 'T_MotorVoltage'}; ...
    {'theta_e', 'T_MotorAngle'}; ...
    {'vdc', 'T_MotorVoltage'}});

upsert_bus_type(design_data, 'phase_duty_t', type_header, { ...
    {'da', 'T_DutyRatio'}; ...
    {'db', 'T_DutyRatio'}; ...
    {'dc', 'T_DutyRatio'}});

saveChanges(dd);
end

function upsert_alias_type(section, type_name, base_type, header_file)
alias_type = Simulink.AliasType(base_type);
alias_type.DataScope = 'Exported';
alias_type.HeaderFile = header_file;

entry = find(section, 'Name', type_name);
if isempty(entry)
    addEntry(section, type_name, alias_type);
else
    setValue(entry(1), alias_type);
end
end

function upsert_bus_type(section, bus_name, header_file, element_specs)
bus_elements = repmat(Simulink.BusElement, numel(element_specs), 1);
for i = 1:numel(element_specs)
    bus_elements(i).Name = element_specs{i}{1};
    bus_elements(i).DataType = element_specs{i}{2};
    bus_elements(i).Dimensions = 1;
end

bus_type = Simulink.Bus;
bus_type.Elements = bus_elements;
bus_type.DataScope = 'Exported';
bus_type.HeaderFile = header_file;

entry = find(section, 'Name', bus_name);
if isempty(entry)
    addEntry(section, bus_name, bus_type);
else
    setValue(entry(1), bus_type);
end
end

function upsert_parameter(section, name, value, data_type, storage_class)
parameter = Simulink.Parameter(value);
parameter.DataType = data_type;
parameter.CoderInfo.StorageClass = storage_class;

entry = find(section, 'Name', name);
if isempty(entry)
    addEntry(section, name, parameter);
else
    setValue(entry(1), parameter);
end
end

function assert_safe_rebuild_environment(script_dir, model_file)
if strcmp(getenv('GJ_DT_ALLOW_UNSAFE_REBUILD'), '1')
    return;
end

if usejava('desktop')
    error(['This script rebuilds a generated .slx file. Run it from ' ...
        'matlab -batch, or set GJ_DT_ALLOW_UNSAFE_REBUILD=1 only after ' ...
        'closing the model in MATLAB Desktop.']);
end

if ~exist(model_file, 'file')
    return;
end

[status, output] = system(sprintf('lsof -F pc -- %s 2>/dev/null', ...
    shell_quote(model_file)));
if status ~= 0 || strlength(strtrim(string(output))) == 0
    return;
end

current_pid = feature('getpid');
lines = splitlines(strtrim(string(output)));
pid = NaN;
command_name = "";
holders = strings(0, 1);
for i = 1:numel(lines)
    line = lines(i);
    if startsWith(line, "p")
        pid = str2double(extractAfter(line, 1));
    elseif startsWith(line, "c")
        command_name = extractAfter(line, 1);
    end

    if ~isnan(pid) && command_name ~= ""
        if pid ~= current_pid && contains(command_name, "MATLAB")
            holders(end + 1, 1) = sprintf('%s held by PID %d (%s)', ...
                model_file, pid, command_name); %#ok<AGROW>
        end
        pid = NaN;
        command_name = "";
    end
end

if ~isempty(holders)
    error(['Another MATLAB process appears to hold the average motor twin. ' ...
        'Close it before rebuilding.\n%s'], strjoin(holders, newline));
end
end

function result = should_open_existing_model_from_desktop(model_file)
result = false;
if strcmp(getenv('GJ_DT_ALLOW_UNSAFE_REBUILD'), '1')
    return;
end

if usejava('desktop') && exist(model_file, 'file')
    result = true;
end
end

function close_source_models(model_names)
for i = 1:numel(model_names)
    if bdIsLoaded(model_names{i})
        close_system(model_names{i}, 0);
    end
end
end

function quoted = shell_quote(text)
quoted = ['''' strrep(text, '''', '''"''"''') ''''];
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
