%% Design green-joint speed-loop PI gains from physical motor parameters
%
% This script does not rebuild any Simulink model. It only calculates speed
% PI gains from physical units and writes a design table for later harness use.
%
% Speed PI equation:
%   iq_pre_sat = Kp_speed * (wm_ref - wm_meas) + integrator
%   iq_ref = clamp(iq_pre_sat, -iq_limit, iq_limit)
%   integrator_next = integrator + Ts * ...
%       (Ki_speed * speed_error + Kaw_speed * (iq_ref - iq_pre_sat))

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

run(fullfile(script_dir, 'setup_green_joint_current_loop_twin.m'));

rotor_inertia_kg_mm2 = motor.rotor_inertia_kg_mm2;
rotor_inertia_kg_m2 = motor.rotor_inertia_kg_m2;
gear_ratio = motor.gear_ratio;
output_load_inertia_kg_m2 = motor.output_load_inertia_kg_m2;
output_equiv_inertia_kg_m2 = motor.output_equivalent_inertia_kg_m2;
output_viscous_damping_nm_s_per_rad = ...
    motor.output_viscous_damping_nm_s_per_rad;

% Firmware speed loop uses output-side joint speed as wm_ref/wm_meas and
% outputs motor-side Iq. Therefore the PI plant is:
%   (J_output/N) * d(w_joint)/dt + (B_output/N) * w_joint = Kt * Iq
% Do not use raw output inertia directly in the motor-current PI gains.
speed_loop_equiv_inertia_kg_m2 = motor.speed_loop_equiv_inertia_kg_m2;
speed_loop_equiv_damping_nm_s_per_rad = ...
    motor.speed_loop_equiv_damping_nm_s_per_rad;

% green-joint runs the 20 kHz current ISR every 50 us. The high-performance
% speed-loop target calls the speed loop every 2 current-loop ISR ticks, so
% the production speed-loop period is 100 us.
Ts_speed_s = GJDT_TsSpeed;
zeta = 1.0;
speed_bandwidth_candidates_hz = [10; 20; 30; 40; 60; 80; 100; 150];
selected_speed_bandwidth_hz = 20;
production_candidate_bandwidth_hz = 40;

torque_constant_nm_per_a = motor.torque_constant;

current_loop_time_constant_s = 1 / ...
    (2 * pi * GJDT_CurrentBandwidth_Hz);
speed_loop_delay_s = 1.5 * Ts_speed_s;
delay_limited_speed_bandwidth_hz = 1 / ...
    (2 * pi * 3 * (current_loop_time_constant_s + speed_loop_delay_s));

wc_rad_s = 2 * pi * speed_bandwidth_candidates_hz;
kp_speed = (2 * zeta .* wc_rad_s .* speed_loop_equiv_inertia_kg_m2 - ...
    speed_loop_equiv_damping_nm_s_per_rad) ./ torque_constant_nm_per_a;
ki_speed = wc_rad_s .^ 2 .* speed_loop_equiv_inertia_kg_m2 ./ ...
    torque_constant_nm_per_a;
kaw_speed = wc_rad_s;
closed_loop_tau_ms = 1 ./ wc_rad_s * 1e3;

initial_iq_limit_a = 0.1;
speed_step_ref_rad_s = 4;
initial_p_current_a = kp_speed * speed_step_ref_rad_s;
accel_at_iq_limit_rad_s2 = torque_constant_nm_per_a * ...
    initial_iq_limit_a / speed_loop_equiv_inertia_kg_m2;
ideal_time_to_step_ms = speed_step_ref_rad_s / ...
    accel_at_iq_limit_rad_s2 * 1e3;

design_table = table( ...
    speed_bandwidth_candidates_hz, ...
    wc_rad_s, ...
    kp_speed, ...
    ki_speed, ...
    kaw_speed, ...
    closed_loop_tau_ms, ...
    initial_p_current_a, ...
    'VariableNames', { ...
    'speed_bandwidth_hz', ...
    'wc_rad_s', ...
    'Kp_speed_A_per_radps', ...
    'Ki_speed_A_per_rad', ...
    'Kaw_speed_1_per_s', ...
    'closed_loop_tau_ms', ...
    'initial_p_current_for_step_A'});

results_dir = fullfile(script_dir, 'results');
if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end
result_file = fullfile(results_dir, ...
    'green_joint_speed_loop_design_j0p034kgmm2.csv');
writetable(design_table, result_file);

selected_index = find(speed_bandwidth_candidates_hz == ...
    selected_speed_bandwidth_hz, 1);
candidate_index = find(speed_bandwidth_candidates_hz == ...
    production_candidate_bandwidth_hz, 1);

GJDT_MotorInertiaRotor_kg_mm2 = rotor_inertia_kg_mm2;
GJDT_MotorInertiaRotor_kg_m2 = rotor_inertia_kg_m2;
GJDT_MotorGearRatio = gear_ratio;
GJDT_OutputLoadInertia_kg_m2 = output_load_inertia_kg_m2;
GJDT_OutputEquivalentInertia_kg_m2 = output_equiv_inertia_kg_m2;
GJDT_OutputViscousDamping_Nm_s_per_rad = ...
    output_viscous_damping_nm_s_per_rad;
GJDT_SpeedLoopEquivalentInertia_kg_m2 = speed_loop_equiv_inertia_kg_m2;
GJDT_SpeedLoopEquivalentDamping_Nm_s_per_rad = ...
    speed_loop_equiv_damping_nm_s_per_rad;
GJDT_TsSpeed = Ts_speed_s;
GJDT_SpeedBandwidth_Hz = selected_speed_bandwidth_hz;
GJDT_SpeedKp = single(kp_speed(selected_index));
GJDT_SpeedKi = single(ki_speed(selected_index));
GJDT_SpeedKaw = single(kaw_speed(selected_index));
GJDT_SpeedIqLimit_A = single(initial_iq_limit_a);

fprintf('\nGreen-joint speed-loop design:\n');
fprintf('  rotor inertia          = %.9g kg*mm^2\n', ...
    rotor_inertia_kg_mm2);
fprintf('  rotor inertia          = %.9g kg*m^2\n', ...
    rotor_inertia_kg_m2);
fprintf('  gear ratio             = %.9g\n', gear_ratio);
fprintf('  output load inertia    = %.9g kg*m^2\n', ...
    output_load_inertia_kg_m2);
fprintf('  output equivalent J    = %.9g kg*m^2\n', ...
    output_equiv_inertia_kg_m2);
fprintf('  output viscous B       = %.9g N*m*s/rad\n', ...
    output_viscous_damping_nm_s_per_rad);
fprintf('  speed-loop equiv J     = %.9g kg*m^2\n', ...
    speed_loop_equiv_inertia_kg_m2);
fprintf('  speed-loop equiv B     = %.9g N*m*s/rad\n', ...
    speed_loop_equiv_damping_nm_s_per_rad);
fprintf('  torque constant        = %.9g N*m/A\n', ...
    torque_constant_nm_per_a);
fprintf('  current-loop bandwidth = %.6g Hz\n', ...
    GJDT_CurrentBandwidth_Hz);
fprintf('  delay-limited speed BW = %.6g Hz\n', ...
    delay_limited_speed_bandwidth_hz);
fprintf('\nSelected safe bring-up design:\n');
fprintf('  speed bandwidth        = %.6g Hz\n', ...
    selected_speed_bandwidth_hz);
fprintf('  Kp_speed               = %.9g A/(rad/s)\n', ...
    kp_speed(selected_index));
fprintf('  Ki_speed               = %.9g A/rad\n', ...
    ki_speed(selected_index));
fprintf('  Kaw_speed              = %.9g 1/s\n', ...
    kaw_speed(selected_index));
fprintf('  iq_limit initial       = %.6g A\n', ...
    initial_iq_limit_a);
fprintf('  P current at %.6grad/s = %.9g A\n', ...
    speed_step_ref_rad_s, ...
    initial_p_current_a(selected_index));
fprintf('\nProduction candidate after hardware validation:\n');
fprintf('  speed bandwidth        = %.6g Hz\n', ...
    production_candidate_bandwidth_hz);
fprintf('  Kp_speed               = %.9g A/(rad/s)\n', ...
    kp_speed(candidate_index));
fprintf('  Ki_speed               = %.9g A/rad\n', ...
    ki_speed(candidate_index));
fprintf('  Kaw_speed              = %.9g 1/s\n', ...
    kaw_speed(candidate_index));
fprintf('\nCurrent limit sanity:\n');
fprintf('  %.3g A ideal accel      = %.9g rad/s^2\n', ...
    initial_iq_limit_a, accel_at_iq_limit_rad_s2);
fprintf('  ideal time to %.6grad/s = %.9g ms\n', ...
    speed_step_ref_rad_s, ideal_time_to_step_ms);
fprintf('\nWrote design table:\n  %s\n', result_file);
