%% Verify green-joint module variant contract against MBD setup values
%
% This is a lightweight bridge check between green-joint firmware variant JSON
% and the MATLAB/MBD parameter setup. It does not rebuild models or generate C.

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(script_dir);
workspace_dir = fileparts(repo_dir);
firmware_dir = fullfile(workspace_dir, 'green-joint');

run(fullfile(script_dir, 'setup_green_joint_current_loop_twin.m'));
cfg = evalin('base', 'GJDT_ModuleConfig');

assert_close(double(evalin('base', 'GJDT_GearRatio')), ...
    cfg.gear_ratio, 1e-9, 'gear_ratio');
assert_close(double(evalin('base', 'GJDT_Rs_Ohm')), ...
    cfg.phase_resistance_ohm, 1e-9, 'phase_resistance_ohm');
assert_close(double(evalin('base', 'GJDT_Ld_H')), ...
    cfg.phase_inductance_h, 1e-12, 'phase_inductance_h');
assert_close(double(evalin('base', 'GJDT_CurDKp')), ...
    cfg.current_loop.cur_d_kp, 1e-6, 'CurDKp');
assert_close(double(evalin('base', 'GJDT_CurDKi')), ...
    cfg.current_loop.cur_d_ki, 1e-3, 'CurDKi');
assert_close(double(evalin('base', 'GJDT_CurQKp')), ...
    cfg.current_loop.cur_q_kp, 1e-6, 'CurQKp');
assert_close(double(evalin('base', 'GJDT_CurQKi')), ...
    cfg.current_loop.cur_q_ki, 1e-3, 'CurQKi');
assert_close(double(evalin('base', 'GJDT_OutputEquivalentInertia_kg_m2')), ...
    cfg.mechanics.output_equivalent_inertia_kg_m2, 1e-12, ...
    'output_equivalent_inertia_kg_m2');
assert_close(double(evalin('base', 'GJDT_OutputViscousDamping_Nm_s_per_rad')), ...
    cfg.mechanics.output_viscous_damping_nm_s_per_rad, 1e-12, ...
    'output_viscous_damping_nm_s_per_rad');
assert_close(double(evalin('base', 'GJDT_OutputCoulombFriction_Nm')), ...
    cfg.mechanics.output_coulomb_friction_nm, 1e-12, ...
    'output_coulomb_friction_nm');
assert_close(double(evalin('base', 'GJDT_OutputTorqueBias_Nm')), ...
    cfg.mechanics.output_torque_bias_nm, 1e-12, ...
    'output_torque_bias_nm');

run(fullfile(script_dir, 'design_green_joint_speed_loop.m'));
script_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(script_dir);
workspace_dir = fileparts(repo_dir);
firmware_dir = fullfile(workspace_dir, 'green-joint');
cfg = evalin('base', 'GJDT_ModuleConfig');
assert_close(double(evalin('base', 'GJDT_SpeedKp')), ...
    cfg.speed_loop.speed_kp, 5e-7, 'SpeedKp');
assert_close(double(evalin('base', 'GJDT_SpeedKi')), ...
    cfg.speed_loop.speed_ki, 5e-5, 'SpeedKi');
assert_close(double(evalin('base', 'GJDT_SpeedKaw')), ...
    cfg.speed_loop.speed_kaw, 5e-5, 'SpeedKaw');

fprintf('Green-joint module variant contract verified:\n');
fprintf('  firmware dir = %s\n', firmware_dir);
fprintf('  module       = %s\n', string(cfg.module_name));
fprintf('  gear ratio   = %.9g\n', cfg.gear_ratio);
fprintf('  phase R/L    = %.9g ohm / %.9g H\n', ...
    cfg.phase_resistance_ohm, cfg.phase_inductance_h);
fprintf('  current PI   = Kp %.9g, Ki %.9g\n', ...
    cfg.current_loop.cur_d_kp, cfg.current_loop.cur_d_ki);
fprintf('  output J/B   = %.9g kg*m^2 / %.9g N*m*s/rad\n', ...
    cfg.mechanics.output_equivalent_inertia_kg_m2, ...
    cfg.mechanics.output_viscous_damping_nm_s_per_rad);
fprintf('  speed PI     = Kp %.9g, Ki %.9g, Kaw %.9g\n', ...
    cfg.speed_loop.speed_kp, cfg.speed_loop.speed_ki, ...
    cfg.speed_loop.speed_kaw);

function assert_close(actual, expected, tolerance, name)
if abs(actual - expected) > tolerance
    error('%s mismatch: actual %.12g expected %.12g tolerance %.12g', ...
        name, actual, expected, tolerance);
end
end
