%% Build PWM dead-time sampling-window MBD module
%
% Architecture:
%   pwm_phase_duty_t
%     -> DeadtimeSamplingWindowStep
%     -> pwm_sampling_status_t
%
% The algorithm is intentionally implemented with Simulink primitive blocks:
%
%   T_low_ideal = max((1 - duty) * T_pwm, 0)
%   T_usable    = max(T_low_ideal - DeadTimeTotal_s - AdcSettleTime_s, 0)
%   valid       = T_usable >= MinValidWindow_s

clear; clc;

cfg = customer_interface_config();
script_dir = fileparts(mfilename('fullpath'));
cfg.dictionaryFile = fullfile(script_dir, cfg.dictionaryName);
assignin('base', 'pwm_deadtime_sampling_config', cfg);

previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

defaults = default_pwm_sampling_params();
assignin('base', 'pwm_sampling_defaults', defaults);
assignin('base', 'pwm_sampling_test', defaults.test);

model = cfg.modelName;
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end

close_open_data_dictionaries();
create_pwm_sampling_data_dictionary(cfg, defaults);

if exist(model_file, 'file')
    delete(model_file);
end

new_system(model);
set_param(model, 'DataDictionary', cfg.dictionaryName);
set_param(model, ...
    'StopTime', 'pwm_sampling_defaults.simcfg.stop_time', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'pwm_sampling_defaults.simcfg.Ts_step', ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'InlineParams', 'on');

set_param(model, ...
    'CodeInterfacePackaging', 'Reusable function', ...
    'ModelReferenceNumInstancesAllowed', 'Multi');

add_test_sources(model, cfg);
add_sampling_subsystem(model, cfg);
add_output_sinks(model, cfg);

set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built PWM dead-time sampling MBD model:\n  %s\n', model_file);

function cfg = customer_interface_config()
cfg.modelName = 'pwm_deadtime_sampling_model';
cfg.functionName = 'DeadtimeSamplingWindowStep';
cfg.sampleTime = 'pwm_sampling_defaults.simcfg.Ts_step';

cfg.dictionaryName = 'pwm_deadtime_sampling_interface.sldd';
cfg.typeHeaderFile = 'pwm_deadtime_sampling_types.h';
cfg.rebuildDictionary = true;

cfg.floatBaseType = 'single';
cfg.boolBaseType = 'boolean';
cfg.realTypeName = 'T_PwmSamplingFloat';
cfg.dutyTypeName = 'T_PwmDuty';
cfg.timeTypeName = 'T_PwmTime';
cfg.validTypeName = 'T_PwmSampleValid';

cfg.inputBusName = 'pwm_phase_duty_t';
cfg.outputBusName = 'pwm_sampling_status_t';
end

function defaults = default_pwm_sampling_params()
defaults.simcfg.stop_time = 50e-6;
defaults.simcfg.Ts_step = 50e-6;

defaults.PwmPeriod_s = single(50e-6);
defaults.DeadTime_s = single(500e-9);
defaults.DeadTimeTotal_s = single(2 * defaults.DeadTime_s);
defaults.AdcSettleTime_s = single(1.0e-6);
defaults.MinValidWindow_s = single(2.5e-6);

defaults.test.da = single(0.05);
defaults.test.db = single(0.95);
defaults.test.dc = single(0.50);
end

function close_open_data_dictionaries()
try
    Simulink.data.dictionary.closeAll('-discard');
catch err
    warning('Could not close open data dictionaries before rebuild: %s', ...
        err.message);
end
end

function create_pwm_sampling_data_dictionary(cfg, defaults)
dd = open_or_create_data_dictionary(cfg);
design_data = getSection(dd, 'Design Data');

upsert_alias_type(design_data, cfg.realTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.dutyTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.timeTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.validTypeName, cfg.boolBaseType, cfg.typeHeaderFile);

upsert_bus_type(design_data, cfg.inputBusName, cfg.typeHeaderFile, { ...
    {'da', cfg.dutyTypeName}; ...
    {'db', cfg.dutyTypeName}; ...
    {'dc', cfg.dutyTypeName}});

upsert_bus_type(design_data, cfg.outputBusName, cfg.typeHeaderFile, { ...
    {'ideal_low_a_s', cfg.timeTypeName}; ...
    {'ideal_low_b_s', cfg.timeTypeName}; ...
    {'ideal_low_c_s', cfg.timeTypeName}; ...
    {'usable_low_a_s', cfg.timeTypeName}; ...
    {'usable_low_b_s', cfg.timeTypeName}; ...
    {'usable_low_c_s', cfg.timeTypeName}; ...
    {'sample_valid_a', cfg.validTypeName}; ...
    {'sample_valid_b', cfg.validTypeName}; ...
    {'sample_valid_c', cfg.validTypeName}; ...
    {'all_samples_valid', cfg.validTypeName}; ...
    {'min_usable_low_s', cfg.timeTypeName}});

upsert_parameter(design_data, 'PwmPeriod_s', defaults.PwmPeriod_s, cfg.timeTypeName);
upsert_parameter(design_data, 'DeadTimeTotal_s', defaults.DeadTimeTotal_s, cfg.timeTypeName);
upsert_parameter(design_data, 'AdcSettleTime_s', defaults.AdcSettleTime_s, cfg.timeTypeName);
upsert_parameter(design_data, 'MinValidWindow_s', defaults.MinValidWindow_s, cfg.timeTypeName);

saveChanges(dd);
close(dd);
end

function dd = open_or_create_data_dictionary(cfg)
if isfield(cfg, 'rebuildDictionary') && cfg.rebuildDictionary && exist(cfg.dictionaryFile, 'file')
    delete(cfg.dictionaryFile);
end

if exist(cfg.dictionaryFile, 'file')
    dd = Simulink.data.dictionary.open(cfg.dictionaryFile);
else
    dd = Simulink.data.dictionary.create(cfg.dictionaryFile);
end
end

function upsert_alias_type(section, type_name, base_type, header_file)
alias_type = Simulink.AliasType(base_type);
alias_type.DataScope = 'Exported';
alias_type.HeaderFile = header_file;

entry = find(section, 'Name', type_name);
if isempty(entry)
    addEntry(section, type_name, alias_type);
else
    setValue(entry(1), alias_type);
end
end

function upsert_bus_type(section, bus_name, header_file, element_specs)
bus_elements = repmat(Simulink.BusElement, numel(element_specs), 1);
for i = 1:numel(element_specs)
    bus_elements(i).Name = element_specs{i}{1};
    bus_elements(i).DataType = element_specs{i}{2};
    bus_elements(i).Dimensions = 1;
end

bus_type = Simulink.Bus;
bus_type.Elements = bus_elements;
bus_type.DataScope = 'Exported';
bus_type.HeaderFile = header_file;

entry = find(section, 'Name', bus_name);
if isempty(entry)
    addEntry(section, bus_name, bus_type);
else
    setValue(entry(1), bus_type);
end
end

function upsert_parameter(section, name, value, data_type)
parameter = Simulink.Parameter(double(value));
parameter.DataType = data_type;
parameter.CoderInfo.StorageClass = 'Auto';

entry = find(section, 'Name', name);
if isempty(entry)
    addEntry(section, name, parameter);
else
    setValue(entry(1), parameter);
end
end

function add_test_sources(model, cfg)
source_specs = { ...
    'da', 'pwm_sampling_test.da', [45 70 115 95]; ...
    'db', 'pwm_sampling_test.db', [45 115 115 140]; ...
    'dc', 'pwm_sampling_test.dc', [45 160 115 185]};

for i = 1:size(source_specs, 1)
    add_typed_constant(model, source_specs{i, 1}, source_specs{i, 2}, ...
        cfg.dutyTypeName, source_specs{i, 3}, cfg.sampleTime);
end

add_block('simulink/Signal Routing/Bus Creator', [model '/duty_bus_creator'], ...
    'Position', [170 65 190 190], ...
    'Inputs', '3', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.inputBusName, ...
    'NonVirtualBus', 'on');

names = {'da', 'db', 'dc'};
for i = 1:numel(names)
    name_line(add_line(model, [names{i} '/1'], ...
        sprintf('duty_bus_creator/%d', i), 'autorouting', 'on'), names{i});
end
end

function add_sampling_subsystem(model, cfg)
subsystem = [model '/' cfg.functionName];
add_clean_subsystem(subsystem, [275 95 500 165]);

set_param(subsystem, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function', ...
    'RTWFcnNameOpts', 'User specified', ...
    'RTWFcnName', cfg.functionName, ...
    'RTWFileNameOpts', 'User specified', ...
    'RTWFileName', cfg.functionName);

add_block('simulink/Sources/In1', [subsystem '/duty_in'], ...
    'Position', [35 130 65 150], ...
    'OutDataTypeStr', ['Bus: ' cfg.inputBusName], ...
    'BusOutputAsStruct', 'on', ...
    'PortDimensions', '1');

add_block('simulink/Signal Routing/Bus Selector', [subsystem '/select_duty'], ...
    'Position', [110 97 150 183], ...
    'OutputSignals', 'da,db,dc');

add_time_constant(subsystem, 'zero_s', '0', [120 245 180 270], cfg.timeTypeName);
add_time_constant(subsystem, 'one', '1', [120 290 180 315], cfg.realTypeName);
add_time_constant(subsystem, 'PwmPeriod_s', 'PwmPeriod_s', [120 335 205 360], cfg.timeTypeName);
add_time_constant(subsystem, 'DeadTimeTotal_s', 'DeadTimeTotal_s', [120 380 225 405], cfg.timeTypeName);
add_time_constant(subsystem, 'AdcSettleTime_s', 'AdcSettleTime_s', [120 425 235 450], cfg.timeTypeName);
add_time_constant(subsystem, 'MinValidWindow_s', 'MinValidWindow_s', [120 470 235 495], cfg.timeTypeName);

add_line(subsystem, 'duty_in/1', 'select_duty/1', 'autorouting', 'on');

fields = {'a', 'b', 'c'};
selector_ports = [1 2 3];
ideal_sources = cell(1, 3);
usable_sources = cell(1, 3);
valid_sources = cell(1, 3);
for i = 1:numel(fields)
    y0 = 60 + (i - 1) * 125;
    [ideal_sources{i}, usable_sources{i}, valid_sources{i}] = ...
        add_phase_window_path(subsystem, fields{i}, selector_ports(i), y0, cfg);
end

add_block('simulink/Math Operations/MinMax', [subsystem '/min_usable_low_s'], ...
    'Position', [720 405 760 455], ...
    'Function', 'min', ...
    'Inputs', '3', ...
    'OutDataTypeStr', cfg.timeTypeName);
for i = 1:3
    add_line(subsystem, usable_sources{i}, sprintf('min_usable_low_s/%d', i), ...
        'autorouting', 'on');
end

add_block('simulink/Logic and Bit Operations/Logical Operator', [subsystem '/all_samples_valid'], ...
    'Position', [720 505 760 555], ...
    'Operator', 'AND', ...
    'Inputs', '3', ...
    'OutDataTypeStr', cfg.validTypeName);
for i = 1:3
    add_line(subsystem, valid_sources{i}, sprintf('all_samples_valid/%d', i), ...
        'autorouting', 'on');
end

add_block('simulink/Signal Routing/Bus Creator', [subsystem '/status_bus_creator'], ...
    'Position', [865 80 895 580], ...
    'Inputs', '11', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.outputBusName, ...
    'NonVirtualBus', 'on');

output_signals = { ...
    'ideal_low_a_s', ideal_sources{1}; ...
    'ideal_low_b_s', ideal_sources{2}; ...
    'ideal_low_c_s', ideal_sources{3}; ...
    'usable_low_a_s', usable_sources{1}; ...
    'usable_low_b_s', usable_sources{2}; ...
    'usable_low_c_s', usable_sources{3}; ...
    'sample_valid_a', valid_sources{1}; ...
    'sample_valid_b', valid_sources{2}; ...
    'sample_valid_c', valid_sources{3}; ...
    'all_samples_valid', 'all_samples_valid/1'; ...
    'min_usable_low_s', 'min_usable_low_s/1'};

for i = 1:size(output_signals, 1)
    name_line(add_line(subsystem, output_signals{i, 2}, ...
        sprintf('status_bus_creator/%d', i), 'autorouting', 'on'), ...
        output_signals{i, 1});
end

add_block('simulink/Sinks/Out1', [subsystem '/status_out'], ...
    'Position', [965 320 995 340], ...
    'OutDataTypeStr', ['Bus: ' cfg.outputBusName], ...
    'PortDimensions', '1');
add_line(subsystem, 'status_bus_creator/1', 'status_out/1', 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(subsystem);

add_line(model, 'duty_bus_creator/1', [cfg.functionName '/1'], 'autorouting', 'on');
end

function [ideal_src, usable_src, valid_src] = add_phase_window_path(subsystem, phase, selector_port, y0, cfg)
prefix = ['phase_' phase '_'];

add_block('simulink/Math Operations/Sum', [subsystem '/' prefix 'one_minus_duty'], ...
    'Position', [215 y0 245 y0+35], ...
    'Inputs', '+-', ...
    'OutDataTypeStr', cfg.realTypeName);
add_line(subsystem, 'one/1', [prefix 'one_minus_duty/1'], 'autorouting', 'on');
add_line(subsystem, sprintf('select_duty/%d', selector_port), ...
    [prefix 'one_minus_duty/2'], 'autorouting', 'on');

add_block('simulink/Math Operations/Product', [subsystem '/' prefix 'ideal_low_calc'], ...
    'Position', [300 y0 335 y0+35], ...
    'Inputs', '**', ...
    'OutDataTypeStr', cfg.timeTypeName);
add_line(subsystem, [prefix 'one_minus_duty/1'], [prefix 'ideal_low_calc/1'], ...
    'autorouting', 'on');
add_line(subsystem, 'PwmPeriod_s/1', [prefix 'ideal_low_calc/2'], ...
    'autorouting', 'on');

add_block('simulink/Math Operations/MinMax', [subsystem '/' prefix 'ideal_low_nonnegative'], ...
    'Position', [385 y0 425 y0+35], ...
    'Function', 'max', ...
    'Inputs', '2', ...
    'OutDataTypeStr', cfg.timeTypeName);
add_line(subsystem, [prefix 'ideal_low_calc/1'], [prefix 'ideal_low_nonnegative/1'], ...
    'autorouting', 'on');
add_line(subsystem, 'zero_s/1', [prefix 'ideal_low_nonnegative/2'], ...
    'autorouting', 'on');

add_block('simulink/Math Operations/Sum', [subsystem '/' prefix 'minus_deadtime'], ...
    'Position', [475 y0 505 y0+35], ...
    'Inputs', '+-', ...
    'OutDataTypeStr', cfg.timeTypeName);
add_line(subsystem, [prefix 'ideal_low_nonnegative/1'], [prefix 'minus_deadtime/1'], ...
    'autorouting', 'on');
add_line(subsystem, 'DeadTimeTotal_s/1', [prefix 'minus_deadtime/2'], ...
    'autorouting', 'on');

add_block('simulink/Math Operations/MinMax', [subsystem '/' prefix 'after_deadtime_nonnegative'], ...
    'Position', [555 y0 595 y0+35], ...
    'Function', 'max', ...
    'Inputs', '2', ...
    'OutDataTypeStr', cfg.timeTypeName);
add_line(subsystem, [prefix 'minus_deadtime/1'], [prefix 'after_deadtime_nonnegative/1'], ...
    'autorouting', 'on');
add_line(subsystem, 'zero_s/1', [prefix 'after_deadtime_nonnegative/2'], ...
    'autorouting', 'on');

add_block('simulink/Math Operations/Sum', [subsystem '/' prefix 'minus_settle'], ...
    'Position', [645 y0 675 y0+35], ...
    'Inputs', '+-', ...
    'OutDataTypeStr', cfg.timeTypeName);
add_line(subsystem, [prefix 'after_deadtime_nonnegative/1'], [prefix 'minus_settle/1'], ...
    'autorouting', 'on');
add_line(subsystem, 'AdcSettleTime_s/1', [prefix 'minus_settle/2'], ...
    'autorouting', 'on');

add_block('simulink/Math Operations/MinMax', [subsystem '/' prefix 'usable_low_nonnegative'], ...
    'Position', [725 y0 765 y0+35], ...
    'Function', 'max', ...
    'Inputs', '2', ...
    'OutDataTypeStr', cfg.timeTypeName);
add_line(subsystem, [prefix 'minus_settle/1'], [prefix 'usable_low_nonnegative/1'], ...
    'autorouting', 'on');
add_line(subsystem, 'zero_s/1', [prefix 'usable_low_nonnegative/2'], ...
    'autorouting', 'on');

add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [subsystem '/' prefix 'sample_valid'], ...
    'Position', [805 y0+5 840 y0+30], ...
    'Operator', '>=');
add_line(subsystem, [prefix 'usable_low_nonnegative/1'], [prefix 'sample_valid/1'], ...
    'autorouting', 'on');
add_line(subsystem, 'MinValidWindow_s/1', [prefix 'sample_valid/2'], ...
    'autorouting', 'on');

ideal_src = [prefix 'ideal_low_nonnegative/1'];
usable_src = [prefix 'usable_low_nonnegative/1'];
valid_src = [prefix 'sample_valid/1'];
end

function add_output_sinks(model, cfg)
add_block('simulink/Sinks/Out1', [model '/status_out'], ...
    'Position', [610 120 640 140], ...
    'OutDataTypeStr', ['Bus: ' cfg.outputBusName], ...
    'PortDimensions', '1');
add_line(model, [cfg.functionName '/1'], 'status_out/1', 'autorouting', 'on');

add_block('simulink/Signal Routing/Bus Selector', [model '/status_selector'], ...
    'Position', [585 215 635 435], ...
    'OutputSignals', ['ideal_low_a_s,ideal_low_b_s,ideal_low_c_s,' ...
    'usable_low_a_s,usable_low_b_s,usable_low_c_s,' ...
    'sample_valid_a,sample_valid_b,sample_valid_c,' ...
    'all_samples_valid,min_usable_low_s']);
add_line(model, [cfg.functionName '/1'], 'status_selector/1', 'autorouting', 'on');

fields = { ...
    'ideal_low_a_s'; 'ideal_low_b_s'; 'ideal_low_c_s'; ...
    'usable_low_a_s'; 'usable_low_b_s'; 'usable_low_c_s'; ...
    'sample_valid_a'; 'sample_valid_b'; 'sample_valid_c'; ...
    'all_samples_valid'; 'min_usable_low_s'};

for i = 1:numel(fields)
    y = 205 + (i - 1) * 35;
    add_block('simulink/Sinks/To Workspace', [model '/' fields{i}], ...
        'Position', [710 y 800 y+22], ...
        'VariableName', fields{i}, ...
        'SaveFormat', 'Structure With Time');
    add_line(model, sprintf('status_selector/%d', i), [fields{i} '/1'], ...
        'autorouting', 'on');
end

Simulink.BlockDiagram.arrangeSystem(model);
end

function add_clean_subsystem(path, position)
add_block('simulink/Ports & Subsystems/Subsystem', path, ...
    'Position', position);

try
    delete_line(path, 'In1/1', 'Out1/1');
catch
end

if exist_block([path '/In1'])
    delete_block([path '/In1']);
end
if exist_block([path '/Out1'])
    delete_block([path '/Out1']);
end
end

function tf = exist_block(block_path)
try
    get_param(block_path, 'Handle');
    tf = true;
catch
    tf = false;
end
end

function add_typed_constant(model, name, value, data_type, position, sample_time)
add_block('simulink/Sources/Constant', [model '/' name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', sample_time);
end

function add_time_constant(model, name, value, position, data_type)
add_block('simulink/Sources/Constant', [model '/' name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', '-1');
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
