%% Build green-joint speed-estimator PLL MBD module

clc;

cfg = customer_interface_config();
script_dir = fileparts(mfilename('fullpath'));
cfg.dictionaryFile = fullfile(script_dir, cfg.dictionaryName);
assignin('base', 'speed_estimator_pll_config', cfg);

previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

defaults = default_speed_estimator_params();
assignin('base', 'speed_estimator_pll_defaults', defaults);
assignin('base', 'speed_estimator_pll_simcfg', defaults.simcfg);
assignin('base', 'speed_estimator_pll_test', defaults.test);

model = cfg.modelName;
model_file = fullfile(script_dir, [model '.slx']);

if bdIsLoaded(model)
    set_param(model, 'Dirty', 'off');
    close_system(model, 0);
end

close_open_data_dictionaries();
create_speed_estimator_data_dictionary(cfg, defaults);

if exist(model_file, 'file')
    delete(model_file);
end

new_system(model);
set_param(model, 'DataDictionary', cfg.dictionaryName);
set_param(model, ...
    'StopTime', '0.010', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(defaults.simcfg.sample_time_s, '%.12g'), ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'ParameterPrecisionLossMsg', 'none', ...
    'InlineParams', 'off', ...
    'CodeInterfacePackaging', 'Reusable function', ...
    'ModelReferenceNumInstancesAllowed', 'Multi');

add_speed_estimator_subsystem(model, cfg);
add_root_interface(model, cfg);

set_param(model, 'SimulationCommand', 'update');
save_system(model, model_file);

fprintf('Built speed-estimator PLL MBD model:\n  %s\n', model_file);

function cfg = customer_interface_config()
cfg.modelName = 'speed_estimator_pll_model';
cfg.sampleTime = '50e-6';
cfg.dictionaryName = 'speed_estimator_pll_interface.sldd';
cfg.typeHeaderFile = 'speed_estimator_pll_types.h';

cfg.floatTypeName = 'T_SpeedEstimatorFloat';
cfg.angleTypeName = 'T_SpeedEstimatorAngle';
cfg.speedTypeName = 'T_SpeedEstimatorSpeed';
cfg.gainTypeName = 'T_SpeedEstimatorGain';
cfg.resetTypeName = 'T_SpeedEstimatorReset';

cfg.inputBusName = 'speed_estimator_input_t';
cfg.outputBusName = 'speed_estimator_output_t';

cfg.floatBaseType = 'single';
cfg.resetBaseType = 'uint8';
end

function defaults = default_speed_estimator_params()
defaults.simcfg.sample_time_s = 50e-6;
defaults.pll_bandwidth_hz = 360.0;
defaults.pll_damping = 1.0;
omega_n = 2 * pi * defaults.pll_bandwidth_hz;
defaults.PllKp = single(2 * defaults.pll_damping * omega_n);
defaults.PllKi = single(omega_n * omega_n);
defaults.GearRatio = single(183.35);
defaults.InvGearRatio = single(1.0 / double(defaults.GearRatio));
defaults.PolePairs = single(2.0);
defaults.encoder_counts = single(65536.0);
defaults.encoder_offset_rad = single(0.0);
defaults.ZeroSpeedThresholdRadS = single( ...
    0.5 * defaults.simcfg.sample_time_s * double(defaults.PllKi) * ...
    (2 * pi / double(defaults.encoder_counts)));
defaults.test.speed_before_rad_s = single(0.0);
defaults.test.speed_after_rad_s = single(900.0);
defaults.test.stop_time = 0.030;
defaults.test.step_time = 0.005;
end

function close_open_data_dictionaries()
try
    Simulink.data.dictionary.closeAll('-discard');
catch err
    warning('Could not close open data dictionaries before rebuild: %s', ...
        err.message);
end
end

function create_speed_estimator_data_dictionary(cfg, defaults)
dd = open_or_create_data_dictionary(cfg);
design_data = getSection(dd, 'Design Data');

upsert_alias_type(design_data, cfg.floatTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.angleTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.speedTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.gainTypeName, cfg.floatBaseType, cfg.typeHeaderFile);
upsert_alias_type(design_data, cfg.resetTypeName, cfg.resetBaseType, cfg.typeHeaderFile);

upsert_bus_type(design_data, cfg.inputBusName, cfg.typeHeaderFile, { ...
    {'motor_angle_rad', cfg.angleTypeName}; ...
    {'reset', cfg.resetTypeName}});

upsert_bus_type(design_data, cfg.outputBusName, cfg.typeHeaderFile, { ...
    {'joint_speed_est_rad_s', cfg.speedTypeName}; ...
    {'motor_speed_mech_rad_s', cfg.speedTypeName}; ...
    {'motor_speed_elec_rad_s', cfg.speedTypeName}; ...
    {'theta_hat_rad', cfg.angleTypeName}});

upsert_parameter(design_data, 'PllKp', defaults.PllKp, cfg.gainTypeName);
upsert_parameter(design_data, 'PllKi', defaults.PllKi, cfg.gainTypeName);
upsert_parameter(design_data, 'SpeedEstimatorSampleTime', ...
    single(defaults.simcfg.sample_time_s), cfg.floatTypeName);
upsert_parameter(design_data, 'GearRatio', defaults.GearRatio, cfg.floatTypeName);
upsert_parameter(design_data, 'InvGearRatio', defaults.InvGearRatio, cfg.floatTypeName);
upsert_parameter(design_data, 'PolePairs', defaults.PolePairs, cfg.floatTypeName);
upsert_parameter(design_data, 'EncoderOffsetRad', ...
    defaults.encoder_offset_rad, cfg.angleTypeName);
upsert_parameter(design_data, 'ZeroSpeedThresholdRadS', ...
    defaults.ZeroSpeedThresholdRadS, cfg.speedTypeName);

saveChanges(dd);
close(dd);
end

function dd = open_or_create_data_dictionary(cfg)
if exist(cfg.dictionaryFile, 'file')
    dd = Simulink.data.dictionary.open(cfg.dictionaryFile);
else
    dd = Simulink.data.dictionary.create(cfg.dictionaryFile);
end
end

function upsert_alias_type(section, type_name, base_type, header_file)
alias_type = Simulink.AliasType(base_type);
alias_type.DataScope = 'Exported';
alias_type.HeaderFile = header_file;
entry = find(section, 'Name', type_name);
if isempty(entry)
    addEntry(section, type_name, alias_type);
else
    setValue(entry(1), alias_type);
end
end

function upsert_bus_type(section, bus_name, header_file, element_specs)
bus_elements = repmat(Simulink.BusElement, numel(element_specs), 1);
for i = 1:numel(element_specs)
    bus_elements(i).Name = element_specs{i}{1};
    bus_elements(i).DataType = element_specs{i}{2};
    bus_elements(i).Dimensions = 1;
end
bus_type = Simulink.Bus;
bus_type.Elements = bus_elements;
bus_type.DataScope = 'Exported';
bus_type.HeaderFile = header_file;
entry = find(section, 'Name', bus_name);
if isempty(entry)
    addEntry(section, bus_name, bus_type);
else
    setValue(entry(1), bus_type);
end
end

function upsert_parameter(section, name, value, data_type)
parameter = Simulink.Parameter(double(value));
parameter.DataType = data_type;
parameter.CoderInfo.StorageClass = 'Auto';
entry = find(section, 'Name', name);
if isempty(entry)
    addEntry(section, name, parameter);
else
    setValue(entry(1), parameter);
end
end

function add_root_interface(model, cfg)
add_block('simulink/Sources/In1', [model '/speed_estimator_in'], ...
    'Position', [55 120 85 140], ...
    'OutDataTypeStr', ['Bus: ' cfg.inputBusName], ...
    'BusOutputAsStruct', 'on', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Sinks/Out1', [model '/speed_estimator_out'], ...
    'Position', [520 120 550 140], ...
    'OutDataTypeStr', ['Bus: ' cfg.outputBusName]);

add_line(model, 'speed_estimator_in/1', 'SpeedEstimatorPllStep/1', ...
    'autorouting', 'on');
add_line(model, 'SpeedEstimatorPllStep/1', 'speed_estimator_out/1', ...
    'autorouting', 'on');
end

function add_speed_estimator_subsystem(model, cfg)
subsystem = [model '/SpeedEstimatorPllStep'];
add_clean_subsystem(subsystem, [225 85 415 185]);

set_param(subsystem, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function', ...
    'RTWFcnNameOpts', 'User specified', ...
    'RTWFcnName', 'SpeedEstimatorPllStep', ...
    'RTWFileNameOpts', 'User specified', ...
    'RTWFileName', 'SpeedEstimatorPllStep');

add_block('simulink/Sources/In1', [subsystem '/speed_estimator_in'], ...
    'Position', [35 145 65 165], ...
    'OutDataTypeStr', ['Bus: ' cfg.inputBusName], ...
    'BusOutputAsStruct', 'on');
add_block('simulink/Sinks/Out1', [subsystem '/speed_estimator_out'], ...
    'Position', [1240 145 1270 165], ...
    'OutDataTypeStr', ['Bus: ' cfg.outputBusName]);

add_block('simulink/Signal Routing/Bus Selector', [subsystem '/input_selector'], ...
    'Position', [105 105 120 195], ...
    'OutputSignals', 'motor_angle_rad,reset');

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [subsystem '/motor_angle_to_angle'], ...
    'Position', [160 95 215 125], ...
    'OutDataTypeStr', cfg.angleTypeName);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [subsystem '/reset_to_reset'], ...
    'Position', [160 175 215 205], ...
    'OutDataTypeStr', cfg.resetTypeName);

add_wrap_0_to_2pi_subsystem(subsystem, 'wrap_measured_angle', ...
    [245 80 335 140], cfg);
add_wrap_0_to_2pi_subsystem(subsystem, 'wrap_predicted_angle', ...
    [505 80 595 140], cfg);
add_wrap_pi_subsystem(subsystem, 'wrap_angle_error', ...
    [675 80 765 140], cfg);
add_wrap_0_to_2pi_subsystem(subsystem, 'wrap_corrected_angle', ...
    [910 80 1000 140], cfg);

add_block('simulink/Discrete/Unit Delay', [subsystem '/omega_state'], ...
    'Position', [360 210 430 240], ...
    'InitialCondition', '0', ...
    'SampleTime', cfg.sampleTime);

add_block('simulink/Discrete/Unit Delay', [subsystem '/theta_state'], ...
    'Position', [360 35 430 65], ...
    'InitialCondition', 'EncoderOffsetRad', ...
    'SampleTime', cfg.sampleTime);

add_block('simulink/Math Operations/Gain', [subsystem '/omega_to_theta_delta'], ...
    'Position', [360 125 430 155], ...
    'Gain', 'SpeedEstimatorSampleTime', ...
    'ParamDataTypeStr', cfg.floatTypeName, ...
    'OutDataTypeStr', cfg.angleTypeName);

add_block('simulink/Math Operations/Sum', [subsystem '/theta_predict_sum'], ...
    'Position', [460 65 490 110], ...
    'Inputs', '++', ...
    'OutDataTypeStr', cfg.angleTypeName, ...
    'AccumDataTypeStr', cfg.angleTypeName);

add_block('simulink/Math Operations/Sum', [subsystem '/angle_error_sum'], ...
    'Position', [625 75 655 120], ...
    'Inputs', '+-', ...
    'OutDataTypeStr', cfg.angleTypeName, ...
    'AccumDataTypeStr', cfg.angleTypeName);

add_block('simulink/Math Operations/Gain', [subsystem '/kp_gain'], ...
    'Position', [790 70 850 100], ...
    'Gain', 'PllKp', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.angleTypeName);

add_block('simulink/Math Operations/Gain', [subsystem '/theta_correction_delta'], ...
    'Position', [790 115 850 145], ...
    'Gain', 'SpeedEstimatorSampleTime', ...
    'ParamDataTypeStr', cfg.floatTypeName, ...
    'OutDataTypeStr', cfg.angleTypeName);

add_block('simulink/Math Operations/Sum', [subsystem '/theta_correct_sum'], ...
    'Position', [870 75 900 120], ...
    'Inputs', '++', ...
    'OutDataTypeStr', cfg.angleTypeName, ...
    'AccumDataTypeStr', cfg.angleTypeName);

add_block('simulink/Math Operations/Gain', [subsystem '/ki_gain'], ...
    'Position', [790 205 850 235], ...
    'Gain', 'PllKi', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.speedTypeName);

add_block('simulink/Math Operations/Gain', [subsystem '/omega_correction_delta'], ...
    'Position', [885 205 945 235], ...
    'Gain', 'SpeedEstimatorSampleTime', ...
    'ParamDataTypeStr', cfg.floatTypeName, ...
    'OutDataTypeStr', cfg.speedTypeName);

add_block('simulink/Math Operations/Sum', [subsystem '/omega_update_sum'], ...
    'Position', [980 200 1010 245], ...
    'Inputs', '++', ...
    'OutDataTypeStr', cfg.speedTypeName, ...
    'AccumDataTypeStr', cfg.speedTypeName);

add_block('simulink/Math Operations/Abs', [subsystem '/abs_omega_update'], ...
    'Position', [1040 200 1070 230]);
add_typed_constant(subsystem, 'zero_speed', [1040 255 1100 280], ...
    'single(0)', cfg.speedTypeName, cfg.sampleTime);
add_block('simulink/Signal Routing/Switch', [subsystem '/zero_speed_snap_switch'], ...
    'Position', [1120 205 1170 255], ...
    'Criteria', 'u2 > Threshold', ...
    'Threshold', 'ZeroSpeedThresholdRadS');

add_block('simulink/Signal Routing/Switch', [subsystem '/omega_reset_switch'], ...
    'Position', [1045 305 1095 355], ...
    'Criteria', 'u2 ~= 0');

add_block('simulink/Signal Routing/Switch', [subsystem '/theta_reset_switch'], ...
    'Position', [1045 80 1095 130], ...
    'Criteria', 'u2 ~= 0');

add_block('simulink/Math Operations/Gain', [subsystem '/inv_gear_gain'], ...
    'Position', [1120 45 1180 75], ...
    'Gain', 'InvGearRatio', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.speedTypeName);

add_block('simulink/Math Operations/Gain', [subsystem '/polepair_gain'], ...
    'Position', [1120 145 1180 175], ...
    'Gain', 'PolePairs', ...
    'ParamDataTypeStr', cfg.gainTypeName, ...
    'OutDataTypeStr', cfg.speedTypeName);

add_block('simulink/Signal Routing/Bus Creator', [subsystem '/output_bus_creator'], ...
    'Position', [1200 45 1215 175], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.outputBusName, ...
    'NonVirtualBus', 'on');

add_line(subsystem, 'speed_estimator_in/1', 'input_selector/1', 'autorouting', 'on');
add_line(subsystem, 'input_selector/1', 'motor_angle_to_angle/1', 'autorouting', 'on');
add_line(subsystem, 'input_selector/2', 'reset_to_reset/1', 'autorouting', 'on');
add_line(subsystem, 'motor_angle_to_angle/1', 'wrap_measured_angle/1', 'autorouting', 'on');
add_line(subsystem, 'theta_state/1', 'theta_predict_sum/1', 'autorouting', 'on');
add_line(subsystem, 'omega_state/1', 'omega_to_theta_delta/1', 'autorouting', 'on');
add_line(subsystem, 'omega_to_theta_delta/1', 'theta_predict_sum/2', 'autorouting', 'on');
add_line(subsystem, 'theta_predict_sum/1', 'wrap_predicted_angle/1', 'autorouting', 'on');
add_line(subsystem, 'wrap_measured_angle/1', 'angle_error_sum/1', 'autorouting', 'on');
add_line(subsystem, 'wrap_predicted_angle/1', 'angle_error_sum/2', 'autorouting', 'on');
add_line(subsystem, 'angle_error_sum/1', 'wrap_angle_error/1', 'autorouting', 'on');
add_line(subsystem, 'wrap_angle_error/1', 'kp_gain/1', 'autorouting', 'on');
add_line(subsystem, 'kp_gain/1', 'theta_correction_delta/1', 'autorouting', 'on');
add_line(subsystem, 'wrap_predicted_angle/1', 'theta_correct_sum/1', 'autorouting', 'on');
add_line(subsystem, 'theta_correction_delta/1', 'theta_correct_sum/2', 'autorouting', 'on');
add_line(subsystem, 'theta_correct_sum/1', 'wrap_corrected_angle/1', 'autorouting', 'on');
add_line(subsystem, 'wrap_angle_error/1', 'ki_gain/1', 'autorouting', 'on');
add_line(subsystem, 'ki_gain/1', 'omega_correction_delta/1', 'autorouting', 'on');
add_line(subsystem, 'omega_state/1', 'omega_update_sum/1', 'autorouting', 'on');
add_line(subsystem, 'omega_correction_delta/1', 'omega_update_sum/2', 'autorouting', 'on');
add_line(subsystem, 'omega_update_sum/1', 'abs_omega_update/1', 'autorouting', 'on');
add_line(subsystem, 'omega_update_sum/1', 'zero_speed_snap_switch/1', 'autorouting', 'on');
add_line(subsystem, 'abs_omega_update/1', 'zero_speed_snap_switch/2', 'autorouting', 'on');
add_line(subsystem, 'zero_speed/1', 'zero_speed_snap_switch/3', 'autorouting', 'on');
add_line(subsystem, 'zero_speed/1', 'omega_reset_switch/1', 'autorouting', 'on');
add_line(subsystem, 'reset_to_reset/1', 'omega_reset_switch/2', 'autorouting', 'on');
add_line(subsystem, 'zero_speed_snap_switch/1', 'omega_reset_switch/3', 'autorouting', 'on');
add_line(subsystem, 'wrap_measured_angle/1', 'theta_reset_switch/1', 'autorouting', 'on');
add_line(subsystem, 'reset_to_reset/1', 'theta_reset_switch/2', 'autorouting', 'on');
add_line(subsystem, 'wrap_corrected_angle/1', 'theta_reset_switch/3', 'autorouting', 'on');
add_line(subsystem, 'omega_reset_switch/1', 'omega_state/1', 'autorouting', 'on');
add_line(subsystem, 'theta_reset_switch/1', 'theta_state/1', 'autorouting', 'on');
add_line(subsystem, 'omega_reset_switch/1', 'inv_gear_gain/1', 'autorouting', 'on');
add_line(subsystem, 'omega_reset_switch/1', 'polepair_gain/1', 'autorouting', 'on');
name_line(add_line(subsystem, 'inv_gear_gain/1', ...
    'output_bus_creator/1', 'autorouting', 'on'), 'joint_speed_est_rad_s');
name_line(add_line(subsystem, 'omega_reset_switch/1', ...
    'output_bus_creator/2', 'autorouting', 'on'), 'motor_speed_mech_rad_s');
name_line(add_line(subsystem, 'polepair_gain/1', ...
    'output_bus_creator/3', 'autorouting', 'on'), 'motor_speed_elec_rad_s');
name_line(add_line(subsystem, 'theta_reset_switch/1', ...
    'output_bus_creator/4', 'autorouting', 'on'), 'theta_hat_rad');
add_line(subsystem, 'output_bus_creator/1', 'speed_estimator_out/1', 'autorouting', 'on');
end

function add_wrap_0_to_2pi_subsystem(parent, name, position, cfg)
subsystem = [parent '/' name];
add_clean_subsystem(subsystem, position);

add_block('simulink/Sources/In1', [subsystem '/u'], ...
    'Position', [35 35 65 55], ...
    'OutDataTypeStr', cfg.angleTypeName);
wrap_block = [subsystem '/wrap_0_to_2pi_loop'];
add_block('simulink/User-Defined Functions/MATLAB Function', wrap_block, ...
    'Position', [130 35 250 85]);
add_block('simulink/Sinks/Out1', [subsystem '/y'], ...
    'Position', [305 55 335 75], ...
    'OutDataTypeStr', cfg.angleTypeName);

set_matlab_function_code(wrap_block, wrap_0_to_2pi_loop_code());

add_line(subsystem, 'u/1', 'wrap_0_to_2pi_loop/1', 'autorouting', 'on');
add_line(subsystem, 'wrap_0_to_2pi_loop/1', 'y/1', 'autorouting', 'on');
end

function add_wrap_pi_subsystem(parent, name, position, cfg)
subsystem = [parent '/' name];
add_clean_subsystem(subsystem, position);

add_block('simulink/Sources/In1', [subsystem '/u'], ...
    'Position', [35 50 65 70], ...
    'OutDataTypeStr', cfg.angleTypeName);
wrap_block = [subsystem '/wrap_pi_loop'];
add_block('simulink/User-Defined Functions/MATLAB Function', wrap_block, ...
    'Position', [135 45 285 95]);
add_block('simulink/Sinks/Out1', [subsystem '/y'], ...
    'Position', [480 65 510 85], ...
    'OutDataTypeStr', cfg.angleTypeName);

set_matlab_function_code(wrap_block, wrap_pi_loop_code());

add_line(subsystem, 'u/1', 'wrap_pi_loop/1', 'autorouting', 'on');
add_line(subsystem, 'wrap_pi_loop/1', 'y/1', 'autorouting', 'on');
end

function add_clean_subsystem(subsystem, position)
add_block('simulink/Ports & Subsystems/Subsystem', subsystem, ...
    'Position', position);
lines = find_system(subsystem, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(subsystem, 'SearchDepth', 1, 'Type', 'Block');
for i = 2:numel(blocks)
    delete_block(blocks{i});
end
end

function add_typed_constant(model, block_name, position, value, data_type, sample_time)
add_block('simulink/Sources/Constant', [model '/' block_name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', sample_time);
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end

function set_matlab_function_code(block_path, code)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block_path);
if isempty(chart)
    error('Could not find MATLAB Function chart: %s', block_path);
end
chart.Script = code;
end

function code = wrap_0_to_2pi_loop_code()
code = sprintf([ ...
    'function y = wrap_0_to_2pi_loop(u)\n' ...
    '%%#codegen\n' ...
    'two_pi = single(6.2831853071795864769);\n' ...
    'y = single(u);\n' ...
    'while y >= two_pi\n' ...
    '    y = y - two_pi;\n' ...
    'end\n' ...
    'while y < single(0.0)\n' ...
    '    y = y + two_pi;\n' ...
    'end\n' ...
    'end\n']);
end

function code = wrap_pi_loop_code()
code = sprintf([ ...
    'function y = wrap_pi_loop(u)\n' ...
    '%%#codegen\n' ...
    'pi_v = single(3.1415926535897932385);\n' ...
    'y = wrap_0_to_2pi_loop(single(u) + pi_v) - pi_v;\n' ...
    'end\n\n' ...
    'function y = wrap_0_to_2pi_loop(u)\n' ...
    '%%#codegen\n' ...
    'two_pi = single(6.2831853071795864769);\n' ...
    'y = single(u);\n' ...
    'while y >= two_pi\n' ...
    '    y = y - two_pi;\n' ...
    'end\n' ...
    'while y < single(0.0)\n' ...
    '    y = y + two_pi;\n' ...
    'end\n' ...
    'end\n']);
end
