%% Smoke test for speed_estimator_pll_model

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
previous_dir = pwd;
cleanup_dir = onCleanup(@() cd(previous_dir));
cd(script_dir);

run(fullfile(script_dir, 'build_speed_estimator_pll_model.m'));

cfg = evalin('base', 'speed_estimator_pll_config');
model = cfg.modelName;
model_file = fullfile(script_dir, [model '.slx']);

load_system(model_file);
harness = build_speed_estimator_smoke_harness(cfg, model);
cleanup_harness = onCleanup(@() close_model_without_saving(harness));

sim_out = sim(harness, 'ReturnWorkspaceOutputs', 'on', 'SaveOutput', 'off');

theta = sim_out.get('log_theta').Data;
motor_speed = sim_out.get('log_motor_speed').Data;
joint_speed = sim_out.get('log_joint_speed').Data;
reset = sim_out.get('log_reset').Data;

defaults = evalin('base', 'speed_estimator_pll_defaults');
expected_motor_speed = double(defaults.test.speed_after_rad_s);
settled = sim_out.get('log_motor_speed').Time >= 0.020;
final_motor_speed = mean(double(motor_speed(settled)));
final_error = expected_motor_speed - final_motor_speed;

fprintf('\nSpeed-estimator PLL smoke test result:\n');
fprintf('  theta range            = [%.6g, %.6g] rad\n', ...
    min(theta), max(theta));
fprintf('  reset asserted samples = %d\n', nnz(reset ~= 0));
fprintf('  final motor speed      = %.6g rad/s\n', final_motor_speed);
fprintf('  final speed error      = %.6g rad/s\n', final_error);
fprintf('  final joint speed      = %.6g rad/s\n', mean(double(joint_speed(settled))));

all_values = [double(theta(:)); double(motor_speed(:)); double(joint_speed(:))];
if any(~isfinite(all_values))
    error('Speed-estimator PLL smoke test failed: non-finite value detected.');
end
if abs(final_error) > 10.0
    error('Speed-estimator PLL smoke test failed: final speed error too large.');
end

fprintf('Speed-estimator PLL smoke test passed.\n');

close_model_without_saving(harness);
clear cleanup_harness;

function harness = build_speed_estimator_smoke_harness(cfg, referenced_model)
harness = 'speed_estimator_pll_smoke_harness';
if bdIsLoaded(harness)
    close_system(harness, 0);
end

new_system(harness);
set_param(harness, ...
    'DataDictionary', cfg.dictionaryName, ...
    'StopTime', 'speed_estimator_pll_defaults.test.stop_time', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'speed_estimator_pll_simcfg.sample_time_s', ...
    'ParameterPrecisionLossMsg', 'none');

add_block('simulink/Sources/Clock', [harness '/clock'], ...
    'Position', [45 55 75 75]);
add_block('simulink/Sources/Step', [harness '/speed_step'], ...
    'Position', [45 120 95 150], ...
    'Time', 'speed_estimator_pll_defaults.test.step_time', ...
    'Before', 'speed_estimator_pll_defaults.test.speed_before_rad_s', ...
    'After', 'speed_estimator_pll_defaults.test.speed_after_rad_s', ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Discrete/Discrete-Time Integrator', ...
    [harness '/angle_integrator'], ...
    'Position', [155 116 225 154], ...
    'gainval', '1', ...
    'InitialCondition', '0', ...
    'SampleTime', cfg.sampleTime, ...
    'OutDataTypeStr', cfg.angleTypeName);
add_block('simulink/Math Operations/Math Function', ...
    [harness '/angle_wrap'], ...
    'Position', [270 118 320 152], ...
    'Operator', 'mod');
add_typed_constant(harness, 'two_pi', [255 175 325 200], ...
    'single(2*pi)', cfg.angleTypeName, cfg.sampleTime);
add_block('simulink/Sources/Constant', [harness '/reset'], ...
    'Position', [255 235 325 260], ...
    'Value', 'uint8(0)', ...
    'OutDataTypeStr', cfg.resetTypeName, ...
    'SampleTime', cfg.sampleTime);
add_block('simulink/Signal Routing/Bus Creator', ...
    [harness '/input_bus_creator'], ...
    'Position', [380 125 395 260], ...
    'Inputs', '2', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.inputBusName, ...
    'NonVirtualBus', 'on');
add_block('simulink/Ports & Subsystems/Model', ...
    [harness '/SpeedEstimatorPllModelRef'], ...
    'Position', [465 150 655 235], ...
    'ModelName', referenced_model);
add_block('simulink/Signal Routing/Bus Selector', ...
    [harness '/output_selector'], ...
    'Position', [710 145 725 260], ...
    'OutputSignals', ...
    'joint_speed_est_rad_s,motor_speed_mech_rad_s,motor_speed_elec_rad_s,theta_hat_rad');

add_scalar_logger(harness, 'log_theta', [365 70 445 100], 'angle_wrap/1');
add_scalar_logger(harness, 'log_reset', [365 280 445 310], 'reset/1');
add_scalar_logger(harness, 'log_joint_speed', [800 150 900 180], ...
    'output_selector/1');
add_scalar_logger(harness, 'log_motor_speed', [800 195 900 225], ...
    'output_selector/2');

add_line(harness, 'speed_step/1', 'angle_integrator/1', 'autorouting', 'on');
add_line(harness, 'angle_integrator/1', 'angle_wrap/1', 'autorouting', 'on');
add_line(harness, 'two_pi/1', 'angle_wrap/2', 'autorouting', 'on');
name_line(add_line(harness, 'angle_wrap/1', 'input_bus_creator/1', ...
    'autorouting', 'on'), 'motor_angle_rad');
name_line(add_line(harness, 'reset/1', 'input_bus_creator/2', ...
    'autorouting', 'on'), 'reset');
add_line(harness, 'input_bus_creator/1', 'SpeedEstimatorPllModelRef/1', ...
    'autorouting', 'on');
add_line(harness, 'SpeedEstimatorPllModelRef/1', 'output_selector/1', ...
    'autorouting', 'on');
end

function add_typed_constant(model, block_name, position, value, data_type, sample_time)
add_block('simulink/Sources/Constant', [model '/' block_name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', sample_time);
end

function add_scalar_logger(model, variable_name, position, src_port)
add_block('simulink/Sinks/To Workspace', [model '/' variable_name], ...
    'Position', position, ...
    'VariableName', variable_name, ...
    'SaveFormat', 'Timeseries');
add_line(model, src_port, [variable_name '/1'], 'autorouting', 'on');
end

function close_model_without_saving(model)
if bdIsLoaded(model)
    set_param(model, 'Dirty', 'off');
    close_system(model, 0);
end
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
