%% Build a top-level integration model that connects two modules by Bus
%
% OpenLoopMotorInputStep -> motor_t -> MotorClarkeParkStep -> motor_dq_t
%
% The important idea is that both modules use the same data dictionary
% contract. The upstream module output type is "Bus: motor_t", and the
% downstream Clarke/Park module input type is also "Bus: motor_t".

clc;

script_dir = fileparts(mfilename('fullpath'));
run(fullfile(script_dir, 'build_motor_clarke_park_model.m'));

cfg = evalin('base', 'motor_clarke_park_codegen_config');
source_model = cfg.modelName;
source_model_file = fullfile(script_dir, [source_model '.slx']);

load_system(source_model_file);

top_model = 'motor_open_loop_integration_model';
top_model_file = fullfile(script_dir, [top_model '.slx']);

if bdIsLoaded(top_model)
    close_system(top_model, 0);
end

if exist(top_model_file, 'file')
    delete(top_model_file);
end

new_system(top_model);
set_param(top_model, 'DataDictionary', cfg.dictionaryName);

set_param(top_model, ...
    'StopTime', '0.001', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', cfg.sampleTime, ...
    'SystemTargetFile', 'ert.tlc', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'TargetHWDeviceType', 'ARM Compatible->ARM Cortex', ...
    'GenerateReport', 'on', ...
    'RTWVerbose', 'on', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SupportContinuousTime', 'off', ...
    'InlineParams', 'on');

set_param(top_model, ...
    'CodeInterfacePackaging', 'Reusable function', ...
    'ModelReferenceNumInstancesAllowed', 'Multi');

add_open_loop_motor_input_subsystem(top_model, cfg);

add_block([source_model '/' cfg.functionName], ...
    [top_model '/' cfg.functionName], ...
    'Position', [365 105 550 195]);

add_block('simulink/Sinks/Out1', [top_model '/dq_out'], ...
    'Position', [745 145 775 165], ...
    'OutDataTypeStr', ['Bus: ' cfg.outputBusName]);

add_block('simulink/Signal Routing/Bus Selector', [top_model '/dq_selector'], ...
    'Position', [615 75 630 235], ...
    'OutputSignals', 'i_alpha,i_beta,id,iq');

add_display(top_model, 'i_alpha_display', [695 70 785 100]);
add_display(top_model, 'i_beta_display', [695 110 785 140]);
add_display(top_model, 'id_display', [695 190 785 220]);
add_display(top_model, 'iq_display', [695 230 785 260]);

add_line(top_model, 'OpenLoopMotorInputStep/1', ...
    [cfg.functionName '/1'], 'autorouting', 'on');
add_line(top_model, [cfg.functionName '/1'], 'dq_out/1', 'autorouting', 'on');
add_line(top_model, [cfg.functionName '/1'], 'dq_selector/1', 'autorouting', 'on');
add_line(top_model, 'dq_selector/1', 'i_alpha_display/1', 'autorouting', 'on');
add_line(top_model, 'dq_selector/2', 'i_beta_display/1', 'autorouting', 'on');
add_line(top_model, 'dq_selector/3', 'id_display/1', 'autorouting', 'on');
add_line(top_model, 'dq_selector/4', 'iq_display/1', 'autorouting', 'on');

set_param(top_model, 'SimulationCommand', 'update');
save_system(top_model, top_model_file);

fprintf('Built integration Simulink model:\n  %s\n', top_model_file);

function add_open_loop_motor_input_subsystem(model, cfg)
subsystem = [model '/OpenLoopMotorInputStep'];

add_block('simulink/Ports & Subsystems/Subsystem', subsystem, ...
    'Position', [95 95 275 195]);
delete_line(subsystem, 'In1/1', 'Out1/1');
delete_block([subsystem '/In1']);
delete_block([subsystem '/Out1']);

set_param(subsystem, ...
    'TreatAsAtomicUnit', 'on', ...
    'RTWSystemCode', 'Reusable function', ...
    'RTWFcnNameOpts', 'User specified', ...
    'RTWFcnName', 'OpenLoopMotorInputStep', ...
    'RTWFileNameOpts', 'User specified', ...
    'RTWFileName', 'OpenLoopMotorInputStep');

add_typed_constant(subsystem, 'ia', [45 45 95 75], ...
    '1.0', cfg.currentTypeName, cfg.sampleTime);
add_typed_constant(subsystem, 'ib', [45 95 95 125], ...
    '-0.5', cfg.currentTypeName, cfg.sampleTime);
add_typed_constant(subsystem, 'ic', [45 145 95 175], ...
    '-0.5', cfg.currentTypeName, cfg.sampleTime);
add_typed_constant(subsystem, 'theta_e', [45 195 95 225], ...
    '0.5235987755982988', cfg.angleTypeName, cfg.sampleTime);

add_block('simulink/Signal Routing/Bus Creator', ...
    [subsystem '/motor_bus_creator'], ...
    'Position', [165 50 180 220], ...
    'Inputs', '4', ...
    'UseBusObject', 'on', ...
    'BusObject', cfg.inputBusName, ...
    'NonVirtualBus', 'on');

add_block('simulink/Sinks/Out1', [subsystem '/motor_out'], ...
    'Position', [250 125 280 145], ...
    'OutDataTypeStr', ['Bus: ' cfg.inputBusName]);

name_line(add_line(subsystem, 'ia/1', 'motor_bus_creator/1', ...
    'autorouting', 'on'), 'ia');
name_line(add_line(subsystem, 'ib/1', 'motor_bus_creator/2', ...
    'autorouting', 'on'), 'ib');
name_line(add_line(subsystem, 'ic/1', 'motor_bus_creator/3', ...
    'autorouting', 'on'), 'ic');
name_line(add_line(subsystem, 'theta_e/1', 'motor_bus_creator/4', ...
    'autorouting', 'on'), 'theta_e');
add_line(subsystem, 'motor_bus_creator/1', 'motor_out/1', ...
    'autorouting', 'on');
end

function add_typed_constant(model, block_name, position, value, data_type, sample_time)
add_block('simulink/Sources/Constant', [model '/' block_name], ...
    'Position', position, ...
    'Value', value, ...
    'OutDataTypeStr', data_type, ...
    'SampleTime', sample_time);
end

function add_display(model, block_name, position)
add_block('simulink/Sinks/Display', [model '/' block_name], ...
    'Position', position);
end

function name_line(line_handle, signal_name)
set_param(line_handle, 'Name', signal_name);
end
